CTSRD-CHERI/cheribsd

contrib/binutils/opcodes/mips-opc.c
lib/csu/cheri/abicall.s
lib/libc/mips/gen/_setjmp_c.S
lib/libc/mips/gen/setjmp_c.S
lib/libc/mips/sys/cerror.S
lib/libc/mips/sys/ptrace.S
lib/libcheri/mips64/cheri_class.h
libexec/rtld-cheri-elf/mips/rtld_start.S

Merge change to CJALR assembly argument order from its own branch to the 'master' branch now that the compiler and external binutils are updated.

Revise CheriBSD assembly and GNU assembler to swap arguments to

---

lib/csu/common/ignore_init.c

After this commit I can successfully link and run a static CheriABI
helloworld binary with LLD

Work around lld emitting undefined symbols for the init/fini arrays

---

sys/mips/include/atomic.h

This is needed e.g. for postgres while the compiler builtin atomics are broken.
This should be correct but I have not tested it at runtime.

Implement atomic_fcmpset() for __CHERI_PURE_CAPABILITY

---

lib/libcheri/libcheri_ccall.c
lib/libcheri/libcheri_sandbox.c
lib/libcheri/libcheri_sandbox_loader.c
lib/libcheri/libcheri_sandbox_methods.c
lib/libcheri/libcheri_stat.c
lib/libcheri/libcheri_system.c
lib/libcheri/mips/libcheri_ccall_trampoline.S

It still crashes when running cheriabitest -a, but we get much further now.

Partially fix libcheri

---

share/mk/bsd.cheri.mk
sys/compat/cheriabi/cheriabi_misc.c
sys/compat/freebsd64/freebsd64_process.c
sys/kern/sys_process.c
sys/sys/ptrace.h
usr.bin/truss/Makefile
usr.bin/truss/setup.c
usr.bin/truss/syscall.h
usr.bin/truss/syscalls.c
usr.bin/truss/truss.h

This fixes both mips64 and purecap truss to trace both mips64 and purecap processes.

Fix truss under CheriABI

---

sys/mips/beri/asm_beri_mp.S
sys/mips/beri/beri_mp.c
sys/mips/beri/files.beri

Follow other MIPS' lead and just do everything in registers.
Tested by booting on dual core.

[UPSTREAM] mips/beri: avoid stack in early MP boot

---

sys/mips/cheri/cheriabi_machdep.c
sys/mips/include/cheri_machdep.h
sys/mips/include/cpu.h
sys/mips/mips/freebsd32_machdep.c
sys/mips/mips/pm_machdep.c
sys/mips/mips/vm_machdep.c

mcontext.mc_pc was being used incorrectly.

Fix problem introduced in #346

---

sys/cddl/dev/dtrace/mips/dtrace_subr.c
sys/mips/mips/pm_machdep.c

The changes in `pm_machdep.c` should be checked carefully.

Fix cheri-mips DTrace compilation

---

sys/compat/cheriabi/cheriabi_mmap.c
sys/kern/sysv_shm.c
sys/mips/cheri/cheri.c
sys/mips/cheri/cheriabi_machdep.c
sys/mips/include/proc.h
sys/mips/mips/pm_machdep.c
sys/mips/mips/vm_machdep.c
sys/sys/proc.h
sys/vm/vm_mmap.c

These are a couple more cleanups as a follow-on to #371.  After this I would probably want to just push the first RISC-V cheri batch as a PR.

More non-RISC-V cleanups

---

sys/riscv/include/atomic.h

This allows the header to also work in pure-capability mode and could
potentially allow for improved optimizations.
There might be some bugs here since I didn't try running anything but at least it compiles.

Rewrite riscv/atomic.h using the __atomic compiler builtins

---

contrib/subrepo-cheri-c-tests/clang-purecap/clang_purecap_input.c
contrib/subrepo-cheri-c-tests/clang-purecap/clang_purecap_output.c

See https://github.com/CTSRD-CHERI/llvm-project/pull/371

Catch up with LLVM CHERI input/output annotations

---

lib/libmalloc_simple/heap.c
lib/libmalloc_simple/malloc.c
lib/libsimple_printf/Makefile
lib/libsimple_printf/Makefile.inc
lib/libsimple_printf/mips/write.S
lib/libsimple_printf/riscv/write.S
lib/libsimple_printf/simple_printf.c
lib/libsimple_printf/simple_printf.h
lib/libthr/thread/Makefile.inc
lib/libthr/thread/thr_exit.c
lib/libthr/thread/thr_list.c
lib/libthr/thread/thr_printf.c
lib/libthr/thread/thr_private.h

This allows using %#p to print capability details, which can be very useful
for debugging.

Use libsimple_printf for libthr

---

CMakeLists.txt
bin/cheritest/cheritest_syscall.c
contrib/subrepo-cheri-c-tests/clang-hybrid/clang_hybrid_cursor.c
contrib/subrepo-cheri-c-tests/clang-hybrid/clang_hybrid_cursor_trivial.c
share/mk/bsd.sys.mk
sys/conf/kern.post.mk

Let's see if jenkins tests this PR.

Changes for upcoming clang merge

---

CMakeLists.txt
bin/cheritest/cheritest.c

This should allow us to display the results in Jenkins. xmllint and
junitparse appear to be happy with the resulting out.

Add a -x flag to cheritest to emit JUnit XML

---

lib/libcheri/mips/libcheri_system_md.h
sys/amd64/linux/linux_proto.h
sys/amd64/linux32/linux32_proto.h
sys/arm/linux/linux_proto.h
sys/arm64/linux/linux_proto.h
sys/compat/cloudabi32/cloudabi32_proto.h
sys/compat/cloudabi64/cloudabi64_proto.h
sys/compat/freebsd32/freebsd32_proto.h
sys/compat/freebsd64/freebsd64_proto.h
sys/conf/options.mips
sys/i386/linux/linux_proto.h
sys/mips/cheri/cheri.c
sys/mips/cheri/cheriabi_machdep.c
sys/mips/conf/std.CHERI
sys/mips/conf/std.CHERI128
sys/mips/include/cheri.h
sys/mips/include/cheriasm.h
sys/mips/include/cherireg.h
sys/mips/include/frame.h
sys/sys/sysproto.h
sys/tools/makesyscalls.lua

A pass at removing 256-bit support from the kernel.

Remove kernel support for 256-bit.

---

contrib/jemalloc/include/jemalloc/internal/jemalloc_internal_defs.h
sys/conf/kern.post.mk

Also includes an unrelated commit so I don't forget about it.

Fix jemalloc

---

Jenkinsfile

[Jenkins] Initial attempt at running cheritest in Jenkins

---

sys/kern/kern_thread.c
sys/sys/proc.h
sys/vm/vm_extern.h
sys/vm/vm_glue.c
sys/vm/vm_kern.h
sys/vm/vm_swapout.c

kstack merge

---

lib/libc/db/mpool/Makefile.inc
lib/libc/gen/Makefile.inc
lib/libc/iconv/Makefile.inc
lib/libc/posix1e/Makefile.inc
lib/libc/secure/Makefile.inc
lib/libgcc_s/Makefile
lib/libprocstat/Makefile
libexec/rtld-cheri-elf/Makefile
share/man/man5/src.conf.5
share/mk/bsd.lib.mk
share/mk/bsd.opts.mk
share/mk/bsd.symver.mk
tools/build/cross-build/include/common/sys/cdefs.h
tools/build/options/WITHOUT_SYMVER

Fix crossbuild bootstrap after MK_SYMVER removal

---

sys/mips/mips/sys_machdep.c
sys/vm/vm_mmap.c

Fix a few cheriabitest failures turned up by #488.

Native abi fixes

---

sys/vm/vm_map.c

Not sure how this was working before.

Reservation delete fix

---

sys/kern/uipc_syscalls.c

The userspace msghdr is massaged into a kernel one, used, and then
copied back to userspace, but we need to reinstate the original
userspace msg_iov, otherwise a future call with the same struct will
give a kernel address (or capability) there and fail. This commit
reinstates that behaviour from upstream, and reorders the code to match
upstream, so our only diffs are for copy*cap, __capability and
__cheri_tocap.
This fixes ping spewing "ping: recvmsg: Invalid argument" after one
packet for both freebsd64 and purecap.

Fix sys_recvmsg not reinstating userspace's msg_iov (#498)

---

sys/mips/mips/elf_machdep.c

This fixes a few issues Jess pointed out in an earlier change.

Mips elf brand

---

contrib/subrepo-cheri-c-tests/Makefile
lib/libc/mips/string/Makefile.inc
lib/libmilter/Makefile
lib/libsmdb/Makefile
libexec/rtld-cheri-elf/mips/Makefile.inc
share/mk/bsd.cheri.mk
share/mk/bsd.compat.mk
sys/mips/conf/std.CHERI
tools/tools/syscall_timing/st-build.sh
usr.bin/mail/Makefile
usr.sbin/sendmail/Makefile
usr.sbin/ypbind/Makefile

Fix triple warnings

---

bin/cheriabitest-dynamic-mt/Makefile
bin/cheriabitest-dynamic/Makefile
bin/cheriabitest-mt/Makefile
bin/cheriabitest/Makefile
bin/cheritest/Makefile
bin/cheritest/cheritest.c
bin/cheritest/cheritest.h
bin/cheritest/cheritest_sentries.c
bin/cheritest/cheritest_vm.c

Alex suggested there should be some tests for function pointers being sentries.  I've added a couple trivial ones.

Add some trivial tests that function pointers are sentries, etc.

---

lib/libc/sys/Makefile.inc
lib/libc/sys/fcntl.c
lib/libc/sys/ioctl.c
lib/libc/sys/open.c
lib/libc/sys/openat.c
share/skel/dot.login
share/skel/dot.profile
usr.bin/login/motd.template

Fixes https://github.com/CTSRD-CHERI/FETT/issues/13
Also a couple UX improvements.

Fix _openat with a mode argument.

---

sys/arm64/arm64/elf_machdep.c
sys/arm64/arm64/machdep.c
sys/arm64/arm64/trap.c
sys/arm64/arm64/uio_machdep.c
sys/arm64/arm64/undefined.c
sys/arm64/arm64/vm_machdep.c

Catch up with KPI changes needed when building a hybrid aarm64 kernel.

Clean up capability use in the arm64 code

---

lib/libufs/sblock.c
sbin/dumpfs/dumpfs.c
sbin/fsck_ffs/setup.c
sbin/growfs/growfs.c
sbin/newfs/mkfs.c
sys/geom/journal/g_journal_ufs.c
sys/geom/label/g_label_ufs.c
sys/sys/param.h
sys/ufs/ffs/ffs_alloc.c
sys/ufs/ffs/ffs_snapshot.c
sys/ufs/ffs/ffs_subr.c
sys/ufs/ffs/ffs_vfsops.c
sys/ufs/ffs/fs.h
usr.sbin/makefs/ffs/ffs_alloc.c
usr.sbin/makefs/ffs/mkfs.c
usr.sbin/pkg/config.c

Also some minor macro improvements required for some UFS changes I decided not to merge just yet.

Only store one kernel/application pointer in the superblock

---

sys/kern/subr_intr.c
sys/kern/subr_witness.c
sys/kern/sys_generic.c
sys/kern/sys_kbounce.c
sys/mips/mips/pm_machdep.c
sys/sys/systm.h

Minor cleanup of left-over kernel-side changes.

Cheri purecap kernel cleanup2

---

sys/compat/freebsd64/freebsd64_misc.c
sys/compat/freebsd64/freebsd64_signal.c
sys/compat/freebsd64/freebsd64_uipc.c
sys/dev/md/md.c
sys/dev/virtio/pci/virtio_pci.c
sys/kern/kern_cpuset.c
sys/kern/kern_umtx.c
sys/mips/cheri/cheri_memcpy_c.S
sys/mips/include/ucontext.h
sys/mips/mips/exception.S
sys/mips/mips/freebsd64_machdep.c
sys/mips/mips/intr_machdep.c
sys/netinet6/in6_var.h

Integrate minor purecap-kernel changes into dev.

Integrate minor purecap-kernel changes into dev.

---

sys/kern/makesyscalls.sh
sys/mips/include/pte.h
sys/riscv/riscv/freebsd64_machdep.c
sys/riscv/riscv/machdep.c
sys/vm/vm_object.c

While working on #405, I did some trivial tidying up that can go independently of that PR.

Trivial tidying from capdirty

---

sys/cheri/cheri_syscall.c
sys/mips/mips/freebsd64_machdep.c
sys/mips/mips/pm_machdep.c
sys/riscv/include/cheri.h
sys/riscv/include/sbi.h
sys/riscv/riscv/freebsd64_machdep.c
sys/riscv/riscv/in_cksum.c
sys/riscv/riscv/machdep.c

These are some fixes from the purecap kernel branch that are not purecap-specific.  I haven't built them standalone yet though, so need to let them run through CI.  (I have run a hybrid kernel from the purecap branch with these changes, it just had several other changes as well)

Riscv purecap fixes

---

lib/libufs/sblock.c
sbin/dumpfs/dumpfs.c
sbin/fsck_ffs/setup.c
sbin/growfs/growfs.c
sbin/newfs/mkfs.c
stand/libsa/ufs.c
sys/geom/journal/g_journal_ufs.c
sys/geom/label/g_label_ufs.c
sys/riscv/conf/GENERIC
sys/sys/ucred.h
sys/ufs/ffs/ffs_alloc.c
sys/ufs/ffs/ffs_snapshot.c
sys/ufs/ffs/ffs_subr.c
sys/ufs/ffs/ffs_vfsops.c
sys/ufs/ffs/fs.h
usr.sbin/fstyp/ufs.c
usr.sbin/makefs/ffs/ffs_alloc.c
usr.sbin/makefs/ffs/mkfs.c
usr.sbin/mountd/mountd.c
usr.sbin/quot/quot.c

Bugfixes and improvements made rolling the next FETT snapshot.

Fett bugfixes

---

sys/mips/conf/std.BERI
sys/mips/mips/elf_machdep.c

Another day, another "how did nobody noticed this?".

MIPS_SHAREDPAGE on BERI (+ build-time check)

---

lib/libprocstat/core.c
share/mk/bsd.cpu.mk

A couple more 256-bit removals.

CHERI-256 tidying

---

share/man/man9/Makefile
share/man/man9/flag_captured.9
sys/kern/kern_flag.c

This is similar to flag_captured(2), but intended to be called from the
kernel.

Add a flag_captured(9) function.

---

sys/vm/vm_map.c

Preserve MAP_RESERVATIONS when forking.

---

sys/cheri/cheri_exec.c
sys/kern/init_main.c

Make it easier to tell which kind of kernel we have.

CHERI kernel type

---

lib/csu/mips64c128/Makefile
lib/csu/mips64c256/Makefile
lib/csu/mips64c256/crt.h
lib/csu/riscv64c/Makefile
share/mk/bsd.crunchgen.mk

Mostly this just trims some of the noise from a CheriBSD build under cheribuild.   The 256-bit csu one I noticed while working on the second change.

Compat cleanups

---

contrib/netbsd-tests/lib/libc/sys/t_getcontext.c
lib/libc/gen/elf_utils.c
lib/libc/mips/gen/makecontext.c
lib/libc/stdlib/strfmon.c
lib/libc/sys/fcntl.c
lib/libc/tests/resolv/resolv_test.c
lib/libc/tests/sys/sendfile_test.c
libexec/rtld-elf/rtld.c
sys/contrib/libnv/nvpair.c
tests/sys/vm/mlock_test.c
tests/sys/vm/page_fault_signal.c

This fixes something like 10-15 tests under purecap.  About half of these I can also upstream to FreeBSD.

Test fixes2

---

lib/Makefile
lib/libc/mips/string/jdw57_memcpy.c
lib/libjpeg/Makefile
libexec/rtld-elf/mips/reloc.c

Found by building MIPS o32 libraries.

32-bit Fixes

---

share/mk/bsd.cpu.mk

Another change from FreeBSD that will be useful for Morello to pass through Jenkins

Another cherry-picked change from FreeBSD

---

sys/kern/vfs_aio.c

Various fixes and diff-reductions in the AIO code after I tracked down a bug on the purecap kernel.

Aio purecap fixes

---

.clang-format
lib/libarchive/Makefile
lib/libarchive/Makefile.inc
lib/libarchive/tests/Makefile
lib/libc/sys/Makefile.inc
sbin/pfctl/tests/pfctl_test.sh
share/mk/bsd.lib.mk
share/mk/sys.mk
tools/build/make.py
tools/build/mk/Makefile.boot

Mostly to get the lorder.sh change and to resolve the merge conflicts in make.py

Backport more of my upstreamed changes

---

sys/mips/conf/std.BERI
sys/mips/conf/std.MALTA
sys/mips/mips/trap.c

Both commits should be upstreamed.

MIPS witness

---

usr.sbin/kldxref/ef.c
usr.sbin/kldxref/kldxref.c

Separating these out from the CheriBSD-specific commit in #714 as these can go in regardless of that.

Upstream cherry-picks for kldxref

---

bin/cheri_minimal_dynamic_exe/Makefile
bin/helloworld/Makefile
bin/helloworld_cxx/Makefile
bin/helloworld_static/Makefile
lib/csu/libcheri/Makefile
libexec/rtld-elf/tests/cheri/abi-mismatch/basic_purecap_lib/Makefile
libexec/rtld-elf/tests/cheri/abi-mismatch/dlopen-purecap/Makefile
libexec/rtld-elf/tests/cheri/plt/Makefile.inc
share/mk/bsd.compat.mk

These messages were annoying me so I decided to fix them and remove the hack.

NEED_COMPAT=CHERI cleanup

---

sys/riscv/riscv/locore.S
sys/riscv/riscv/machdep.c

A few small things I noticed during the last merge from dev.

Purecap merge fixes

---

share/mk/bsd.lib.mk

Another case of not releasing Option quickly enough after Option-3...

bsd.lib.mk: Fix rogue non-breaking space

---

libexec/rtld-elf/mips/rtld_machdep.h
libexec/rtld-elf/riscv/rtld_machdep.h
libexec/rtld-elf/rtld.c
sys/cheri/cheric.h

Tidy cheric.h

---

sys/kern/subr_bus.c

Lean heavily on devctl using ioctls of only a single form and covert
passed values to a struct devctl as well as converting the cmd. Things
would be slightly more complicated if we used dr_buffer, but it has no
consumers so we leave it alone for now.

freebsd32/64: add devctl compat

---

sys/cheri/cheric.h
sys/dev/pci/pci_user.c
sys/kern/imgact_aout.c
sys/kern/imgact_elf.c
sys/sys/pciio.h

This addresses most post-merge comments from @bsdjhb for #614

Multiple fixes over the reservation patch.

---

bin/cheri_pthreads/cheri_pthreads.c
bin/cheribsdtest/cheribsdtest_cheriabi.c
bin/cheribsdtest/cheribsdtest_registers.c
include/stddef.h
sys/sys/_stdint.h
sys/sys/_types.h
sys/sys/stdatomic.h
sys/sys/stddef.h

Add ptraddr_t and make limited use of it.
The big sed through the kernel will wait until we've merged purecap and morello.

add ptraddr t

---

contrib/libarchive/libarchive/test/test_fuzz.c
contrib/libarchive/libarchive/test/test_read_data_large.c
contrib/libarchive/libarchive/test/test_read_extract.c
contrib/libarchive/libarchive/test/test_read_large.c
contrib/libarchive/libarchive/test/test_read_pax_truncated.c
contrib/libarchive/libarchive/test/test_read_truncated.c
contrib/libarchive/libarchive/test/test_read_truncated_filter.c
contrib/libarchive/libarchive/test/test_write_format_7zip_large.c
contrib/libarchive/test_utils/test_utils.c
contrib/libarchive/test_utils/test_utils.h
lib/libarchive/Makefile
lib/libarchive/tests/Makefile
lib/libarchive/tests/functional_test.sh

I've tried to upstream these but the PR's are mostly being ignored.

Speedup libarchive tests

---

lib/csu/common-cheri/crt_init_globals.c

This extracts the MI CSU changes from morello-dev and folds in the MI parts of my fixes in #849 (with additional style fixes that I have now also pushed to that PR to keep the two branches in sync).

csu: Support hybrid ABI

---

sys/cheri/cheri.h
sys/cheri/cheri_otype.c
sys/cheri/cheri_sealcap.c
sys/cheri/cheri_usercap.c
sys/mips/cheri/cheri.c
sys/mips/mips/locore.S
sys/riscv/cheri/cheri_machdep.c

Pull in the non-purecap portion of #847

Rename global caps (non-purecap)

---

sys/compat/linuxkpi/common/include/linux/err.h
sys/compat/linuxkpi/common/include/linux/printk.h
sys/conf/kern.pre.mk
sys/conf/kmod.mk
sys/dev/hme/if_hme.c
sys/dev/mrsas/mrsas_ioctl.c
sys/dev/mxge/if_mxge.c
sys/dev/proto/proto_busdma.c
sys/dev/usb/controller/ehci.c
sys/dev/usb/controller/ohci.c
sys/dev/usb/controller/uhci.c
sys/dev/usb/controller/xhci.c
sys/dev/usb/usb_core.h
sys/dev/usb/usb_transfer.h
sys/fs/cuse/cuse.c
sys/fs/cuse/cuse_ioctl.h
sys/kern/firmw.S
sys/modules/Makefile
sys/net80211/ieee80211_output.c
sys/netgraph/ng_pppoe.c
sys/tools/fw_stub.awk

These are various fixes from enabling module builds for purecap kernels.  Several of those I hope to upstream to FreeBSD as well.  I haven't yet had a chance to test this, but will let CI chew on it.

Purecap kmod fixes

---

sys/dev/virtio/network/if_vtnet.c

Hopefully Arm get round to fixing these errata, but given they have not yet had a chance to look into it we will shortly need these workarounds in dev.

vtnet: FVP tunables

---

Jenkinsfile
share/mk/src.opts.mk
sys/arm/broadcom/bcm2835/bcm2835_vcio.c
sys/arm64/arm64/copyinout.S
sys/arm64/arm64/exception_morello.S
sys/arm64/arm64/identcpu.c
sys/arm64/arm64/locore.S
sys/arm64/arm64/machdep.c
sys/arm64/arm64/support.S
sys/arm64/arm64/swtch.S
sys/arm64/arm64/trap.c
sys/arm64/cheri/cheri_exception.c
sys/arm64/cheri/cheri_machdep.c
sys/arm64/conf/GENERIC-MORELLO
sys/arm64/include/_align.h
sys/arm64/include/armreg.h
sys/arm64/include/asm.h
sys/arm64/include/cheri.h
sys/arm64/include/cheric.h
sys/arm64/include/cherireg.h
sys/arm64/include/elf.h
sys/arm64/include/ucontext.h
sys/cheri/cherireg.h
sys/conf/files.arm64
sys/conf/kern.mk
sys/mips/include/cherireg.h
sys/netinet/netdump/netdump_client.c
sys/riscv/include/cherireg.h
sys/sys/iov.h

A collection of patches needed to build a Morello kernel. It should also run, but is missing most of the userspace support.

Initial core of Morello kernel support

---

sys/net/if.c

Perform translation if struct ifdrv in ifioctl.
While SIOCGDRVSPEC is technically an in/out ioctl, no consumers modify
it so just assert that nothing touches the ifd_len member.

Add compat support for SIOC[GS]DRVSPEC

---

sys/compat/linuxkpi/common/include/linux/err.h
sys/conf/kmod.mk
sys/dev/usb/controller/ehci.c
sys/dev/usb/controller/ohci.c
sys/dev/usb/controller/uhci.c
sys/dev/usb/controller/xhci.c
sys/dev/usb/usb_transfer.h
sys/kern/firmw.S

Changes to the previously-merged kmod purecap fixes made when upstreaming them to FreeBSD.

Kmod merge fixes

---

bin/cheribsdtest/cheribsdtest_fault.c
bin/cheribsdtest/cheribsdtest_registers.c
bin/cheribsdtest/cheribsdtest_sealcap.c
lib/geom/label/geom_label.c
lib/geom/part/geom_part.c
share/mk/bsd.compat.mk
share/mk/bsd.cpu.mk

Some cleanups plus a build fix found while reviewing the diff.

Misc morello updates

---

sys/mips/include/_bus.h
sys/mips/mips/busdma_machdep.c

This is addressing comments in https://github.com/CTSRD-CHERI/cheribsd/pull/833

Clenup MIPS bus types

---

sys/arm64/arm64/freebsd64_machdep.c
sys/arm64/arm64/genassym.c
sys/arm64/arm64/locore.S
sys/arm64/arm64/machdep.c
sys/arm64/arm64/swtch.S
sys/arm64/arm64/vm_machdep.c
sys/arm64/conf/GENERIC-MORELLO
sys/arm64/include/armreg.h
sys/arm64/include/frame.h
sys/arm64/include/md_var.h
sys/arm64/include/pcb.h
sys/arm64/include/reg.h
sys/arm64/include/ucontext.h
sys/conf/files.arm64
sys/conf/options.arm64

Add support for `COMPAT_FREEBSD64` on Morello. While here also handle user visible registers.

Morello freebsd64 support

---

sys/mips/include/_bus.h
sys/mips/mips/bus_space_generic.c
sys/mips/mips/busdma_machdep.c
sys/riscv/include/_bus.h
sys/riscv/riscv/bus_space_asm.S
sys/riscv/riscv/busdma_bounce.c
sys/riscv/riscv/pmap.c

Change the typedefs for `bus_addr_t` and `bus_space_handle_t`.
Introduce capability handling for busdma.

MD bus space changes

---

sys/compat/linuxkpi/common/include/linux/err.h
sys/ddb/db_sym.c
sys/net/vnet.h

I goofed these on my last merge from dev.

Recent mismerges

---

Jenkinsfile
sys/cheri/cheric.h
sys/cheri/cherireg.h
sys/mips/cheri/cheri.c
sys/mips/cheri/exception.S
sys/mips/cheri/locore.S
sys/mips/conf/std.CHERI_PURECAP
sys/mips/include/asm.h
sys/mips/include/cheri.h
sys/mips/include/proc.h
sys/mips/mips/machdep.c
sys/mips/mips/vm_machdep.c
sys/riscv/riscv/locore.S
sys/sys/elf64.h

This addresses some of the comments from https://github.com/CTSRD-CHERI/cheribsd/pull/879 back into the purecap kernel.

Cleanup locore MIPS and RISC-V

---

sys/cheri/cheric.h
sys/kern/kern_exec.c
sys/kern/kern_malloc.c
sys/kern/subr_vmem.c
sys/kern/sysv_shm.c
sys/vm/uma_core.c
sys/vm/vm_init.c
sys/vm/vm_kern.c
sys/vm/vm_map.c
sys/vm/vm_mmap.c

Address some comments from https://github.com/CTSRD-CHERI/cheribsd/pull/832

Tidy up cheric.h

---

sys/compat/cloudabi/cloudabi_mem.c
sys/compat/freebsd32/freebsd32_misc.c
sys/compat/freebsd64/freebsd64_mmap.c
sys/compat/linux/linux_mmap.c
sys/sys/syscallsubr.h
sys/vm/vm_mmap.c

A couple cleanups inspired by a chat with @jrtc27 a while ago. I plan to upstream the first two patches. I'm slightly conflicted about splitting them. What I've done it easier to describe this way, but will result in more conflicts when looping back later.

kern_mmap cleanup

---

contrib/netbsd-tests/lib/libm/t_cbrt.c
lib/msun/tests/ctrig_test.c
lib/msun/tests/fenv_test.c
lib/msun/tests/trig_test.c
libexec/rc/rc.d/auditd
sys/fs/nfs/nfsport.h
sys/fs/tmpfs/tmpfs_vnops.c
sys/kern/subr_sleepqueue.c
sys/netinet/ip_fw.h
sys/sys/queue.h
tests/sys/audit/utils.c

Backport upstreamed testsuite fixes

---

bin/cheribsdtest/cheribsdtest_registers.c
sys/cheri/cheri.h
sys/mips/cheri/cheriabi_machdep.c
sys/mips/cheri/hybridabi_machdep.c
sys/mips/include/cheri.h
sys/mips/include/pcb.h
sys/mips/include/proc.h
sys/mips/mips/freebsd64_machdep.c
sys/mips/mips/pm_machdep.c
sys/mips/mips/vm_machdep.c

This is an old branch I had posted a while ago.  It removes currently-unused bits from cheri_signal.

csig cleanup

---

sys/mips/cheri/copystr_c.S
sys/mips/cheri/support.S
sys/riscv/include/asm.h
sys/riscv/riscv/copyinout.S
sys/riscv/riscv/support.S

Implement assembly support routines for MIPS and RISCV

purecap kernel MD support routines

---

lib/libc/aarch64/Symbol.map
lib/libc/aarch64/gen/Makefile.inc
lib/libc/aarch64/static_tls.h
lib/libc/aarch64/string/Makefile.inc
lib/libc/gen/Symbol.map
lib/libc/gen/emutls.c
lib/libthr/arch/aarch64/include/pthread_md.h

Current changes in #927 relative to morello-dev.  Once #927 is done, I'll merge this into morello-dev before merging dev to minimize conflicts that need to be resolved.

Morello cleanups

---

libexec/rtld-elf/aarch64/reloc.c
libexec/rtld-elf/aarch64/rtld_machdep.h
libexec/rtld-elf/aarch64/rtld_start.S
libexec/rtld-elf/mips/reloc.c
libexec/rtld-elf/mips/rtld_machdep.h
libexec/rtld-elf/riscv/reloc.c
libexec/rtld-elf/riscv/rtld_machdep.h
libexec/rtld-elf/rtld.c
libexec/rtld-elf/rtld.h
sys/arm64/include/asm.h

Fixes hybrid lazy binding, implements purecap lazy binding, implements purecap IFUNCs (untested) and drops a bogus warning triggered by purecap landing pads.

Fix up Morello rtld bugs and missing features

---

bin/cheribsdtest/mips/cheribsdtest_md.h
lib/csu/aarch64/Makefile
lib/csu/mips/Makefile
lib/csu/mips/crt1_c.c
lib/csu/riscv/Makefile
lib/csu/riscv/crt1_c.c
libexec/rtld-elf/Makefile
libexec/rtld-elf/aarch64/reloc.c
libexec/rtld-elf/aarch64/rtld_machdep.h
libexec/rtld-elf/aarch64/rtld_start.S
libexec/rtld-elf/cheri/cheri_reloc.c
libexec/rtld-elf/cheri/cheri_reloc.h
libexec/rtld-elf/mips/Makefile.inc
libexec/rtld-elf/mips/cheri_plt.cpp
libexec/rtld-elf/mips/reloc.c
libexec/rtld-elf/mips/rtld_machdep.h
libexec/rtld-elf/riscv/Makefile.inc
libexec/rtld-elf/riscv/reloc.c
libexec/rtld-elf/riscv/rtld_machdep.h
libexec/rtld-elf/rtld.c
libexec/rtld-elf/rtld.h
libexec/rtld-elf/tests/cheri/abi-mismatch/dlopen-purecap/dlopen-purecap.c
sys/arm64/include/asm.h
sys/sys/elf_common.h

Includes a bunch of cleanups along the way, including some over and above what's already in morello-dev.

Morello RTLD

---

sys/geom/geom_ctl.c
sys/geom/geom_disk.c
sys/geom/geom_io.c
sys/kern/subr_intr.c
sys/sys/intr.h

- Update casts
- Update irq length type in subr_intr
- Use bus_dma_segment vaddr union type.

Purecap geom changes

---

sys/dev/ata/ata-lowlevel.c

- Use alignment macros.
- Set bounds on bio page transfers.

Purecap ata driver changes.

---

sys/cam/cam_iosched.h
sys/compat/cloudabi/cloudabi_vdso.c
sys/compat/linuxkpi/common/include/linux/gfp.h
sys/compat/linuxkpi/common/src/linux_compat.c
sys/compat/linuxkpi/common/src/linux_page.c
sys/conf/files.riscv
sys/dev/virtio/virtio_ring.h
sys/kern/kern_proc.c
sys/libkern/strlen.c
sys/vm/pmap.h
sys/vm/vm_init.c
sys/vm/vm_mmap.c
sys/vm/vm_page.c
sys/vm/vm_page.h
sys/vm/vm_reserv.c
sys/vm/vm_reserv.h

Also fix a couple of mismerges from previous PRs.

More pointer-as-integer fixes.

---

lib/libsysdecode/mktables

This way we'll decode VM_PROT_READ_CAP, ..._WRITE_CAP, and ..._PRIV_FLAG, too.

libsysdecode: permit _ in VM_PROT_(.*) names

---

sys/riscv/riscv/pmap.c

Brett correctly points out that my CAP-DIRTYABLE to CAP-CLEAN transition was
incorrect: merely atomically clearing CW in response to an old read of a
CD-clear PTE isn't going to do the right thing.  It might leave us with a CD-set
CW-clear PTE, which will cause all kinds of havoc later on.
Therefore, use a CAS when attempting this transition.  This might spuriously
fail if, for example, D or A transition, even if CD does not, but that's fine;
we can simply leave the mapping at CD-clear CW-bearing and fix it in the next
epoch.
For simplicity, move the CLG update to after the other updates to the PTE.
While here, drop an incorrect assertion, which would have failed if we'd raced D
or A getting set.

caprevoke: fix riscv pmap caploadgen update race w/ PTWs

---

sys/arm64/arm64/trap.c

Set machdep.log_user_cheri_exceptions to enable logging.

morello: add sysctl for logging user cheri exceptions

---

lib/libkvm/kvm_proc.c
sys/kern/imgact_elf.c
sys/kern/kern_proc.c
sys/kern/kern_prot.c
sys/kern/kern_sig.c
sys/kern/tty.c
sys/sys/proc.h

Should fix `panic: Assertion pgrp->pg_jobc > 0 failed at /Users/alex/cheri/cheribsd/sys/kern/kern_proc.c:828`

Cherry-pick upstream commits to fix assertion

---

sys/net/rtsock.c

The previous assumption of existing mbuf trailing space is wrong, instead we
use a slower path via m_copyback that should always work.

Fix wrong assumption in routing socket mbuf copy.

---

bin/sh/histedit.c
bin/sh/jobs.c
bin/sh/main.c
bin/sh/memalloc.c
bin/sh/myhistedit.h
bin/sh/sh.1
bin/sh/show.c
bin/sh/show.h
bin/sh/tests/execution/Makefile
bin/sh/tests/execution/shellproc7.0
bin/sh/trap.c
contrib/libedit/Makefile
contrib/libedit/chartype.h
contrib/libedit/common.c
contrib/libedit/filecomplete.c
contrib/libedit/filecomplete.h
contrib/libedit/history.c
contrib/libedit/map.c
contrib/libedit/readline.c
contrib/libedit/refresh.c
contrib/libedit/search.c
contrib/libedit/terminal.c
contrib/libedit/tty.c
lib/libedit/Makefile

This adds command completion in $PATH and makes sh(1) almost usable as an interactive shell.

Cherry-pick improvements to /bin/sh

---

sys/kern/capabilities.conf
sys/kern/init_sysent.c
sys/riscv/conf/CHERI-QEMU-FETT
sys/riscv/conf/FETT

Caprevoke FETT support

---

contrib/bmake/unit-tests/Makefile

Partially cherry-picked from 8e11a9b4250be3c3379c45fa820bff78d99d5946
CC: @dodsonmg

Fix some failing bmake unit tests during bootstrap

---

sys/arm64/arm64/gicv3_its.c
sys/cam/ata/ata_da.c
sys/dev/usb/controller/xhci.c
sys/dev/usb/controller/xhci.h
sys/dev/usb/storage/umass.c
sys/dev/usb/usb.h
sys/geom/label/g_label_msdosfs.c
usr.sbin/fstyp/msdosfs.c

Gathering any patches needed here; so far just the one, but more may come (i.e. don't merge this yet, let's batch them all up here as we find them). Deliberately branched off master to avoid issues with churn in dev.

Fixes for Morello board purecap kernel bring-up

---

lib/libc/gen/emutls.c

The main issue here is that index is a size_t, so checking for negative
values does not catch the -1, i.e. SIZE_MAX, stored whilst allocation is
in progress. The secnod issue is that, where the inner do-while loop to
see and correctly detect index < 0 / index == SIZE_MAX, it then does a
cpu_spinwait without re-loading the value of index, so will spin forever
(but of course we don't hit that due to the first bug).
Rewrite it with a simpler to understand implementation that does not
suffer from these bugs, whilst also being more efficient, since we don't
need to CAS 0 to -1 in a loop, just once.

libc: Fix bogus race handling code in emutls_index

---

sys/i386/i386/copyout.c
sys/i386/i386/elf_machdep.c
sys/i386/i386/exec_machdep.c
sys/i386/i386/genassym.c
sys/i386/include/pcb.h
sys/i386/include/sigframe.h
sys/kern/sys_kbounce.c
sys/ofed/drivers/infiniband/core/ib_uverbs_ioctl.c
sys/ofed/drivers/infiniband/core/uverbs.h
sys/sys/systm.h
sys/sys/ucontext.h
sys/vm/vm_map.c

Note the OFED one is partially due to the fact I'm just doing a plain 'make buildkernel' rather than using cheribuild (there is no cheribsd-i386 target).  (Though I do hope to eventually enable OFED on at least non-CHERI architectures)

I386 build fixes

---

sys/compat/linux/linux_vdso.c
sys/kern/imgact_elf.c
sys/kern/init_main.c
sys/kern/kern_exec.c
sys/vm/uma_core.c
sys/vm/vm_kern.c
sys/vm/vm_map.c
sys/vm/vm_map.h
sys/vm/vm_mmap.c

The commit log messages are hopefully sufficiently detailed. Verified using cheribsdtest with hybrid and purecap kernels.
Most of these are minor changes. The vmspace_fork() change is an important bug fix though. I'd be happy to split this into smaller PRs if that would be helpful.

Various small touch-ups for VM reservations

---

contrib/subrepo-cheri-libunwind/.gitrepo
contrib/subrepo-cheri-libunwind/src/UnwindRegistersRestore.S
contrib/subrepo-cheri-libunwind/src/UnwindRegistersSave.S

libunwind merge

---

COPYRIGHT
sys/sys/copyright.h

Claim collective copyrights for University of Cambridge and SRI
International over CheriBSD.

Claim collective copyrights

---

usr.bin/login/motd.template

- Minor rewording of the first sentence as it's not really a CHERI ISA per se anymore.
- Mention CHERI-CPU Slack.
- Use https for cheri-cpu.org.
- Minor non-essential reformatting and tidying.

Minor motd tweaks to mention the CHERI CPU Slack, reword things a bit.

---

usr.sbin/bsdinstall/partedit/part_wizard.c
usr.sbin/bsdinstall/scripts/auto
usr.sbin/bsdinstall/scripts/hostname

This is a draft; do not merge.
These started to address #1335.

Various simplications to bsdinstall on CheriBSD/Morello

---

sys/kern/sysv_shm.c

Otherwise we're rederiving from roots that will have the expected permissions.
Co-Authored by: John Baldwin <jhb@FreeBSD.org>

shmat: check CHERI perms only if given tagged cap

---

sys/vm/vm_map.c

Sort to reduce diffs to the coexecve branch.

vm: sort vm_map_entry_delete decleration

---

sys/arm64/arm64/efirt_machdep.c

efi phys to kva: return vm_pointer_t

efi phys to kva

---

bin/cheribsdtest/Makefile.cheribsdtest
bin/cheribsdtest/cheribsdtest.c
bin/cheribsdtest/cheribsdtest.h
bin/cheribsdtest/cheribsdtest_colocation.c
sys/kern/imgact_elf.c
sys/kern/kern_exec.c

This PR contains a merge of the coexecve branch onto cocall with a single test where the test runner discovers a service in a child process and cocalls into it.

simple cocall test

---

lib/libpmc/Makefile
lib/libpmc/libpmc.c
sys/dev/hwpmc/pmc_events.h

This should fix running pmcstat on Morello.
CC: @gvnn3

Cherry pick pmcstat fixes

---

sys/dev/drm/core/drm_file.c
sys/dev/drm/drmkpi/drmcompat_dma_buf.c

A couple fixes to issues I noted in #1303.

DRM stack fixes

---

sys/dev/drm/komeda/komeda_drv.c
sys/dev/drm/komeda/komeda_plane.c

This is a fix for the blinking screen.

Reset the DPU device on driver attach. Not on every plane change.

---

sys/vm/vm_mmap.c

this is needed for firefox.
tested with firefox 107 on cheribsd hybrid

sys/vm: In the implied PROT_MAX case, filter out requests based on prot.

---

lib/libcheri_caprevoke/libcheri_caprevoke.c
sys/arm64/arm64/cheri_revoke_machdep.c

A couple text fixes found while reading the code.

caprevoke tidying

---

tools/build/mk/OptionalObsoleteFiles.inc
usr.sbin/bsdinstall/scripts/Makefile
usr.sbin/bsdinstall/scripts/auto
usr.sbin/bsdinstall/scripts/cheri-desktop

Draft as this still has a couple of TODOs, but putting up for review so people can review wording and the general idea

CHERI desktop installer item

---

sys/conf/files
sys/conf/files.arm64
sys/dev/drm/komeda/komeda_drv.c
sys/dev/drm/komeda/komeda_pipeline.c
sys/dev/drm/komeda/komeda_pipeline.h
sys/dev/drm/panfrost/panfrost_drv.c
sys/dev/firmware/arm/mmio_sram.c
sys/dev/firmware/arm/mmio_sram_if.m
sys/dev/firmware/arm/scmi.c
sys/dev/firmware/arm/scmi.h
sys/dev/firmware/arm/scmi_clk.c
sys/dev/firmware/arm/scmi_clk.h
sys/dev/firmware/arm/scmi_protocols.h
sys/dev/firmware/arm/scmi_shmem.c
sys/dev/mailbox/arm/arm_doorbell.c
sys/dev/mailbox/arm/arm_doorbell.h
sys/dev/ofw/ofw_firmware.c

first draft. Tested on Morello

SCMI support

---

sys/compat/freebsd64/freebsd64_generic.c
sys/compat/freebsd64/freebsd64_mac.c
sys/compat/freebsd64/freebsd64_misc.c
sys/compat/freebsd64/freebsd64_mmap.c
sys/compat/freebsd64/freebsd64_process.c
sys/compat/freebsd64/freebsd64_signal.c
sys/compat/freebsd64/freebsd64_time.c
sys/compat/freebsd64/freebsd64_uipc.c
sys/compat/freebsd64/freebsd64_vfs.c

On large nop (removing a bunch of useless blank lines) and a couple line wrapping fixes.

Freebsd64 whitespace improvements

---

sys/contrib/subrepo-openzfs/.gitmodules

This is equivalent to 79e6eb5c018d44ee59c5b9b10755d116c860c366

OpenZFS remove submodules

---

sys/dev/drm/drmkpi/include/linux/rbtree.h

Aside from some cosmetic changes, this mostly fixes bugs in the support for "cached" trees.

drmkpi: Sync rbtree.h with linuxkpi.

---

lib/libthr/thread/thr_attr.c
lib/libthr/thread/thr_init.c
lib/libthr/thread/thr_private.h
lib/libthr/thread/thr_stack.c

Somewhat inspired by merging recent changes to add `_thr_main_stack*`.

libthr stack cleanups

---

sys/arm64/arm64/pmap.c
sys/riscv/riscv/pmap.c

pmap_extract_and_hold: Honor READ_CAP/WRITE_CAP permissions.

---

sys/arm64/include/_stdint.h
sys/riscv/include/_stdint.h

cherry pick arm64 and riscv fixes.

fix sig_atomic_t limits

---

sys/compat/linuxkpi/common/include/linux/device.h
sys/compat/linuxkpi/common/include/linux/kobject.h
sys/compat/linuxkpi/common/include/linux/mm.h
sys/compat/linuxkpi/common/include/linux/pci.h
sys/compat/linuxkpi/common/include/linux/scatterlist.h
sys/compat/linuxkpi/common/include/linux/types.h
sys/compat/linuxkpi/common/include/linux/workqueue.h
sys/compat/linuxkpi/common/include/linux/xarray.h
sys/compat/linuxkpi/common/include/net/mac80211.h
sys/compat/linuxkpi/common/src/linux_80211.c
sys/compat/linuxkpi/common/src/linux_80211.h
sys/compat/linuxkpi/common/src/linux_80211_macops.c
sys/compat/linuxkpi/common/src/linux_compat.c
sys/compat/linuxkpi/common/src/linux_page.c
sys/compat/linuxkpi/common/src/linux_skbuff.c
sys/contrib/dev/iwlwifi/fw/api/tx.h
sys/contrib/dev/iwlwifi/fw/error-dump.h
sys/contrib/dev/iwlwifi/fw/runtime.h
sys/contrib/dev/iwlwifi/iwl-trans.h
sys/contrib/dev/iwlwifi/mvm/mac80211.c
sys/contrib/dev/iwlwifi/mvm/mvm.h
sys/contrib/dev/iwlwifi/pcie/internal.h
sys/contrib/dev/rtw88/mac80211.c
sys/kern/subr_firmware.c
sys/kern/subr_pcpu.c
sys/modules/Makefile
sys/net80211/ieee80211_crypto_ccmp.c
sys/net80211/ieee80211_scan_sw.c
sys/netlink/netlink_message_writer.c
sys/netlink/netlink_message_writer.h

tested in hybrid/purecap with Intel AX200 (PCIe) adapter.

iwlwifi(4) support added

---

bin/cheribsdtest/cheribsdtest_vm.c
sys/arm64/arm64/locore.S
sys/arm64/arm64/pmap.c
sys/arm64/arm64/trap.c
sys/arm64/include/pte.h
sys/riscv/riscv/pmap.c
sys/riscv/riscv/trap.c
sys/sys/mman.h
sys/vm/swap_pager.c
sys/vm/vm_fault.c
sys/vm/vm_kern.c
sys/vm/vm_mmap.c
sys/vm/vm_page.c
sys/vm/vm_page.h

Candidate to merge support for capability dirty tracking in the VM system

Merge capdirty support

---

sys/riscv/riscv/pmap.c

Fixes: 4f93f53b1dd7b13ab268e47294c048262f5644c6

Fix typo discovered when merging dev to caprevoke

---

bin/cheribsdtest/cheribsdtest_ptrace.c
sys/arm64/arm64/elf_machdep.c
sys/arm64/arm64/pmap.c
sys/cheri/cheri_otype.c
sys/kern/kern_event.c
sys/kern/kern_exec.c
sys/kern/kern_sig.c
sys/kern/kern_time.c
sys/kern/vfs_aio.c
sys/vm/vm_fault.c
sys/vm/vm_map.c

Sync a couple things to the dev version and reduce the total amount of header additions.

caprevoke: diff reduction vs dev

---

bin/cheribsdtest/cheribsdtest.c
bin/cheribsdtest/cheribsdtest.h
bin/cheribsdtest/cheribsdtest_registers.c
bin/cheribsdtest/cheribsdtest_syscall.c
bin/cheribsdtest/cheribsdtest_vm.c
contrib/dlmalloc/dlmalloc_nonreuse.c
lib/libc/gen/tls_malloc.c
lib/libcheri_caprevoke/libcaprevoke.h
lib/libcheri_caprevoke/libcheri_caprevoke.c
lib/libmalloc_simple/heap.c
lib/libthr/thread/thr_init.c
libexec/rtld-elf/map_object.c
share/examples/cheribsdtest/run-many
sys/arm64/arm64/cheri_revoke_machdep_tests.c
sys/arm64/arm64/elf_machdep.c
sys/cheri/revoke.h
sys/kern/imgact_elf.c
sys/kern/kern_exec.c
sys/kern/kern_shutdown.c
sys/riscv/riscv/cheri_revoke_machdep_tests.c
sys/riscv/riscv/elf_machdep.c
sys/sys/_stdint.h
sys/sys/_types.h
sys/sys/elf.h
sys/sys/signal.h
sys/vm/vm_map.c

caprevoke: merge dev as of 2023-07-26

---

sys/dev/drm/bridges/tda19988/tda19988.c

The current implementation of tda19988_read_edid has an off-by-one error
in the second tda19988_read_edit_block call, failing to add 1 to turn
the extension index into a block number. This results in the first
extension being the base block again, the second extension being the
first extension, and so on. As a result, we miss the final extension and
reinterpret the base block as an extension if there are any extensions
present. This is probably harmless, as (outside of Wikipedia) extension
00h (the first byte of the base block header) isn't documented as being
assigned, and neither Linux nor FreeBSD seem to look for it, so it's
just treated as an unknown extension and ignored, but it does mean we
potentially miss useful information from the final extension.
Instead, use drm_do_get_edid …

tda19988: Don't buggily reimplement EDID retrieval

---

sys/kern/kern_exec.c

The stringspace used to hold argument and environment strings during
exec holds more than just strings. It also holds the ELF auxiliary,
argument, and environment vectors as well as other ancillary data
pointed to by the ELF auxiliary vector like the stack canary and page
sizes array. If userland passes the max amount of argument strings
data (ARG_MAX), exec_copyout_strings would underflow imgp->strings
when setting bounds on ustringp. On current CHERI RISC-V this causes
a kernel panic due to the faulting CSetBounds. On Morello an eventual
copyout fails due to overflowing bounds.
Add an extra page to the strings space to accomodate this extra space.
This is still not perfect as more than a page can be exhausted if
there are many short argument or environment strings resulting in very …

exec_map_stack: Include an extra page in the dedicated strings space

---

sys/kern/kern_proc.c

The argument and environment vectors are arrays of
`char * __capability` not arrays of `char *`.
This fixes kern.proc.args if the arguments are long enough to overflow
the p_args cache which in turn fixes the bin/pkill/pgrep-f_test:main
test which used an ARG_MAX command line.

Fix get_ps_strings for CHERI

---

sys/netlink/netlink_message_parser.h
sys/netlink/netlink_snl.h

- netlink: Allocate the linear buffer payload separately from the header
- netlink: Add bounds to sub-allocations from linear buffers

netlink bounds

---

sys/dev/drm/panfrost/panfrost_drv.c
sys/dev/drm/panfrost/panfrost_gem.c
sys/dev/drm/panfrost/panfrost_mmu.c

panfrost: change MTX_SPIN mutexes to MTX_DEF.
Tested with glxgears(1).

panfrost: change MTX_SPIN mutexes to MTX_DEF.

---

sys/riscv/riscv/exception.S
sys/riscv/riscv/trap.c

- riscv: Add 'c' prefixes/suffixes to register names in dump_regs
- riscv: Save gp in the trapframe in both modes

riscv64 panic cleanups

---

sys/dev/drm/core/include/uapi/drm/drm_mode.h

Fix drm_mode_atomic member type to match libdrm.

---

bin/cheribsdtest/cheribsdtest_vm.c
sys/kern/kern_event.c

Fix a null pointer dereference in kqueue revocation code

---

sys/arm64/arm64/pmap.c
sys/arm64/arm64/trap.c
sys/vm/vm_fault.c

No regression tests yet, but I've been writing one which tries to exercise load-cap fault handling on a superpage.

Several caprevoke fixes

---

bin/cheribsdtest/cheribsdtest_malloc.c
lib/libc/stdlib/malloc/mrs/mrs.c

Fix realloc() to return non-NULL with a size of 0 to fix sort and others (git grep?). Add test of this property.

mrs: realloc() compat fix

---

sys/dev/drm/bridges/tda19988/tda19988.c
sys/dev/drm/komeda/komeda_plane.c

Honour video-ports TDA19988 property to fix colours on Morello

---

bin/cheribsdtest/cheribsdtest_malloc.c
libexec/Makefile
libexec/malloc_is_revoking/Makefile
libexec/malloc_is_revoking/malloc_is_revoking.c

Add some tests of procctl and elf feature flags.

Revocation management tests

---

sys/arm64/arm64/elf_machdep.c

This fixes a problem I was seeing where vmm.ko's use of a DPCPU pointer was yielding exceptions due to `_DPCPU_PTR()` giving an invalid capability. It turned out that the R_MORELLO_RELATIVE relocation handler did not apply the transformation in elf_relocaddr() needed for `_DPCPU_PTR` to work. This patch tries to fix the problem.
I'm sure my handling of the addend here doesn't make sense, but I'm not sure what the right behaviour is. There is no addend in the particular relocation that was causing me problems. Probably I should pass `addr + addend` to elf_relocaddr() and continue to use `addr` as the base address when dealing with a DPCPU/VNET symbol?

Try to fix DPCPU/VNET relocations in purecap kernels

---

bin/cheribsdtest/cheribsdtest.h
bin/cheribsdtest/cheribsdtest_malloc.c
bin/cheribsdtest/cheribsdtest_util.c
bin/cheribsdtest/cheribsdtest_vm.c
lib/libprocstat/libprocstat.c

Improve handling of NOCAPREVOKE kernels

NOCAPREVOKE improvements

---

lib/libc/stdlib/malloc/mrs/mrs.3
sys/kern/imgact_elf.c
sys/sys/elf_common.h

Hopefully improve the previous mangled sentence.

mrs(3): improve text about AT_BSDFLAGS

---

usr.sbin/bhyve/Makefile
usr.sbin/bhyve/bhyve.8
usr.sbin/bhyve/bhyve_config.5
usr.sbin/bhyve/libslirp.h
usr.sbin/bhyve/net_backend_netgraph.c
usr.sbin/bhyve/net_backend_netmap.c
usr.sbin/bhyve/net_backend_slirp.c
usr.sbin/bhyve/net_backends.c
usr.sbin/bhyve/net_backends.h
usr.sbin/bhyve/net_backends_priv.h

Import the requisite commits from upstream, plus a couple of others to avoid conflicts in net_backends.c.

bhyve backports for slirp support

---

tools/build/mk/OptionalObsoleteFiles.inc
usr.sbin/bsdinstall/scripts/Makefile
usr.sbin/bsdinstall/scripts/auto
usr.sbin/bsdinstall/scripts/cheri-vm-support

NB: Such a package does not yet exist.

bsdinstall: Add new step to install cheri-vm-support metapackage

---

Jenkinsfile
release/scripts/make-manifest.sh

Fixes:	https://github.com/CTSRD-CHERI/cheribsd/issues/1878

Jenkinsfile: Build and ship -NOCAPREVOKE(-NODEBUG) kernels

---

sys/contrib/openzfs/module/os/freebsd/zfs/zio_crypt.c
sys/contrib/openzfs/module/os/linux/zfs/zio_crypt.c
sys/contrib/openzfs/module/zfs/dbuf.c
sys/contrib/openzfs/module/zfs/dnode.c
sys/contrib/subrepo-openzfs/module/os/freebsd/zfs/zio_crypt.c
sys/contrib/subrepo-openzfs/module/os/linux/zfs/zio_crypt.c
sys/contrib/subrepo-openzfs/module/zfs/dbuf.c
sys/contrib/subrepo-openzfs/module/zfs/dnode.c

- zfs: cherry-pick commit from master
- zfs: cherry-pick commit from master
- zfs: cherry-pick commit from master

Merge ZFS 14.0 EN fixes

---

contrib/mandoc/config.h
lib/libpmc/pmu-events/jevents.c

Two cherry-picks from upstream. Probably not super important but I was hitting it on my build system.

Fix Linux bootstrap with Clang 16

---

contrib/mandoc/config.h
lib/libpmc/pmu-events/jevents.c
sys/arm64/vmm/arm64.h
sys/arm64/vmm/hyp.h
sys/arm64/vmm/io/vgic.c
sys/arm64/vmm/io/vgic.h
sys/arm64/vmm/io/vgic_if.m
sys/arm64/vmm/io/vgic_v3.c
sys/arm64/vmm/io/vgic_v3.h
sys/arm64/vmm/io/vgic_v3_reg.h
sys/arm64/vmm/io/vtimer.c
sys/arm64/vmm/io/vtimer.h
sys/arm64/vmm/mmu.h
sys/arm64/vmm/reset.h
sys/arm64/vmm/vmm.c
sys/arm64/vmm/vmm_arm64.c
sys/arm64/vmm/vmm_call.S
sys/arm64/vmm/vmm_dev.c
sys/arm64/vmm/vmm_hyp.c
sys/arm64/vmm/vmm_hyp_exception.S
sys/arm64/vmm/vmm_instruction_emul.c
sys/arm64/vmm/vmm_mmu.c
sys/arm64/vmm/vmm_reset.c
sys/conf/files.arm64
sys/modules/vmm/Makefile
usr.sbin/bhyve/aarch64/bhyverun_machdep.c
usr.sbin/bhyve/aarch64/fdt.c

Merge dev to main for bhyve fixes

---

bin/cheribsdtest/cheribsdtest_malloc.c
lib/libc/stdlib/malloc/mrs/mrs.3
lib/libc/stdlib/malloc/mrs/mrs.c

mrs: mallocx/rallocx alignment support

---

bin/cheribsdtest/cheribsdtest_malloc.c
lib/libc/stdlib/malloc/mrs/mrs.3
lib/libc/stdlib/malloc/mrs/mrs.c
sys/fs/nfs/nfs_var.h
sys/fs/nfsclient/nfs_clcomsubs.c
sys/fs/nfsclient/nfs_clrpcops.c
sys/fs/nfsclient/nfs_clvnops.c

Merge dev to main

---

COPYRIGHT
bin/cheribsdtest/cheribsdtest_cidcap.c
bin/cheribsdtest/cheribsdtest_internal.c
bin/cheribsdtest/cheribsdtest_malloc.c
lib/libc/stdlib/malloc/mrs/mrs.3
lib/libc/stdlib/malloc/mrs/mrs_utrace.h
lib/libc/sys/cheri_cidcap_alloc.2
libexec/malloc_is_revoking/malloc_is_revoking.c
sys/cheri/cheri_cidcap.c
sys/cheri/cidcap.h
sys/compat/freebsd64/freebsd64_cheri.c
usr.bin/procstat/procstat_cheri.c

@bsdjhb you'll want to do the same in kldxref upstream.

Fix MTSS contract ack

---

cddl/lib/Makefile
cddl/lib/libavl/Makefile
cddl/lib/libuutil/Makefile
share/mk/src.libnames.mk

This reverts commits 0cbe25cb42adedfe1d5549ddf1ae137c1aa07f80 and
eb15e17653da2864461eef66fed2f89501a9e396.

Reduce diffs ZFS build infrastructure and src.libnames.mk

---

libexec/rtld-elf/aarch64/rtld_c18n_asm.S
libexec/rtld-elf/aarch64/rtld_c18n_machdep.c
libexec/rtld-elf/rtld_c18n.c
libexec/rtld-elf/rtld_c18n.h

Also reworks trampoline hooks and improves the general efficiency of trampolines.

c18n: Change trusted frame layout to make room for extra data

---

sys/arm64/arm64/locore.S

- arm64 locore: Reduce diffs with upstream with handling PA vs VA
- arm64 locore: Reduce diffs with upstream

arm64 locore

---

lib/libc/Makefile
lib/libc/Symbol-c18n.map
lib/libc/aarch64/gen/setjmp.S
lib/libc/gen/dlfcn.c
lib/libc/sys/sigaction.c
lib/libthr/Makefile
lib/libthr/pthread-c18n.map
lib/libthr/thread/thr_create.c
lib/libthr/thread/thr_rtld.c
lib/libthr/thread/thr_sig.c
libexec/rtld-elf/aarch64/rtld_c18n_asm.S
libexec/rtld-elf/aarch64/rtld_start.S
libexec/rtld-elf/rtld_c18n.c
libexec/rtld-elf/rtld_lock.h

~This PR is to get CI running.~
This PR fixes a subtle bug with signal handling related to stack switching.
It also fixes a bug where transition overhead simulation crashes under the benchmark ABI.

c18n: Fix signal handling bugs

---

libexec/rtld-elf/aarch64/rtld_c18n_asm.S
libexec/rtld-elf/rtld_c18n.c

This is purely a performance optimisation in the trampoline. It should not affect the behaviour of c18n at all.

c18n: Branchless stack resolution in trampolines

---

share/mk/bsd.README
share/mk/bsd.prog.mk

If ELF_FEATURES is set, apply the list of features using elfctl.  If it contains multiple words, they will be joined with commas.

bsd.prog.mk: allow enabling elf features

---

contrib/subrepo-cheri-libunwind/src/CompartmentInfo.hpp
contrib/subrepo-cheri-libunwind/src/Registers.hpp

CI run for riscv64 for libunwind

---

sys/kern/tty_inq.c

`ti->ti_begin` is actually the offset within the first block that is
unread, so we must use that for our lower bound.
Moving to the previous block has to be done at the end of the loop in
order to correctly handle the case of ti_begin == TTYINQ_DATASIZE.  At
that point, lastblock is still the last one with data written and the
next write into the queue would advance lastblock.  If we move to the
previous block at the beginning, then we're essentially off by one block
for the entire scan and run the risk of running off the end of the block
queue.
The ti_begin == 0 case is still handled correctly, as we skip the loop
entirely and the linestart gets recorded as the first byte available for
writing.  The bit after the loop about moving to the next block is also
still correct, even with both …

kern: tty: fix recanonicalization

---

sys/riscv/conf/CHERI-PURECAP-QEMU-FETT

@bsdjhb suggested I merge this seperately.

riscv: add CHERI-PURECAP-QEMU-FETT kernel

---

sys/arm64/vmm/vmm_arm64.c
usr.sbin/bhyve/gdb.c

A couple of bug fixes from upstream, reported by gcc, and one commit to fix a mismerge that I didn't catch when syncing bhyve with upstream.

Several bhyve gdb stub fixups

---

lib/libc/sys/Makefile.inc

Noticed while rebase libsys branch

Actually install the cheri_revoke manpage

---

sys/arm64/arm64/machdep.c
sys/kern/kern_sig.c
sys/kern/kern_time.c
sys/riscv/riscv/machdep.c
sys/vm/vm_cheri_revoke.c
sys/vm/vm_cheri_revoke.h

- **<vm/vm_cheri_revoke.h>: Add comments to final #endifs**
- **Add a helper routine for invoking an in-kernel capability**

Helper routine for revoking hoarded caps

---

Jenkinsfile

NOTE: this is a draft until all prior steps in the CI are completed.
Corresponding changes:
* https://github.com/CTSRD-CHERI/jenkins-scripts/pull/3
* https://github.com/CTSRD-CHERI/cheribsd-deploy-scripts/pull/1

Archive the kernel-c18n branch in Jenkins

---

contrib/subrepo-cheri-libunwind/.gitrepo
contrib/subrepo-cheri-libunwind/CMakeLists.txt
contrib/subrepo-cheri-libunwind/cmake/config-ix.cmake
contrib/subrepo-cheri-libunwind/include/__libunwind_config.h
contrib/subrepo-cheri-libunwind/src/AddressSpace.hpp
contrib/subrepo-cheri-libunwind/src/CompartmentInfo.hpp
contrib/subrepo-cheri-libunwind/src/DwarfInstructions.hpp
contrib/subrepo-cheri-libunwind/src/Registers.hpp
contrib/subrepo-cheri-libunwind/src/UnwindCursor.hpp
contrib/subrepo-cheri-libunwind/src/UnwindRegistersRestore.S
contrib/subrepo-cheri-libunwind/src/UnwindRegistersSave.S
contrib/subrepo-cheri-libunwind/src/libunwind.cpp
lib/libgcc_eh/Makefile.inc
lib/libgcc_s/Makefile
lib/libgcc_s/Symbol-c18n.map

- git subrepo pull contrib/subrepo-cheri-libunwind
- lib: Adapt c18n build options to updated libunwind

Import updated libunwind to use new c18n APIs

---

usr.bin/procstat/procstat.1
usr.bin/procstat/procstat_compartments.c

Also add previously omitted manpage material on the new column.

Replace "DLOPEN" column in "procstat compartments" with "FLAG".

---

sys/riscv/riscv/pmap.c

…unds
The purecap kernel was failing because pmap_bootstrap was initializing virtual_avail with bounds that exclude any memory reserved for bootstrapping, but kmem_init expects virtual_avail to encompass the full range VM_{MIN,MAX}_KERNEL_ADDRESS. kmem_init would try to create a vm_map from a derived capability where the cursor was VM_MIN_KERNEL_ADDRESS, but because virtual_avail excludes memory reserved for bootstrapping that cursor pointed out of bounds. Now, pmap_bootstrap generates a capability with bounds VM_{MIN,MAX}_KERNEL_ADDRESS but still with a cursor that points after the bootstrapped memory.

Fix cheririscv init panic

---

libexec/rtld-elf/rtld_c18n.c

Nominally, this fixes a bug in string_base_search where a mismatch at
the end of a string_base buffer due to the last string containing a
substring of the string being searched for causes the while loop after
the mismatch to walk off the end of the buffer.
However, rather than adding handling for this edge case to the inlined
string comparison, prefer an easier-to-read implementation using
higher level primitives such as strcmp().
While here, do some other simplifications:
- Return bool from string_base_search instead of an index since all of
the callers only care about a boolean result.  Since -1 is no longer
returned as an index, this permits using size_t for string_handle
instead.
- Make string_base_push only use a loop to compute the new capacity
without doing a realloc() inside of …

rtld c18n: Simplify string_base implementation

---

sys/amd64/amd64/elf_machdep.c
sys/arm/arm/elf_machdep.c
sys/arm64/arm64/elf32_machdep.c
sys/arm64/arm64/elf_machdep.c
sys/kern/imgact_elf.c
sys/powerpc/powerpc/elf64_machdep.c
sys/sys/imgact_elf.h

- **elf: Pass ELF header and program header pointers down to various APIs**
- **elf: Support program headers outside of the first page**

Support multiple pages of ELF program headers

---

sys/net/if_bridge.c

BRDGGIFS, BRDGRTS and BRDGGIFSSTP use structures containing pointers so we must preserve capabilities for them, otherwise we will be unable to copyout to them later, and when we copyout the struct itself we will clobber the tag for userspace. The latter causes ifconfig to abort in mrs due to trying to free a member with invalid tag now that we abort on rather than ignore invalid frees.

if_bridge: Use copyincap/copyoutcap for ioctls containing capabilities

---

COPYRIGHT
sys/sys/copyright.h

I noticed we forgot to update the collective copyright for the new year or the start of DEC so fix that.

Copyright bump and add DEC ack

---

contrib/libarchive/libarchive/archive_write_set_format_pax.c

Merged upstream in https://github.com/libarchive/libarchive/pull/2588

Fix libarchive one-byte overflow

---

libexec/rtld-elf/rtld_c18n.c

RTLD is built by linking against shared versions of setjmp/longjmp. Now that the system's default setjmp/longjmp implementations support c18n by calling dl_c18n_get_trusted_stack and dl_c18n_unwind_trusted_stack, this poses a problem when RTLD calls setjmp/longjmp, as these calls won't go through a trampoline, violating the invariants assume by the dl_c18n_* functions.
Whilst it would be best to fix RTLD's build process by linking it against static versions of setjmp/longjmp, insert checks into dl_c18n_* for now to ignore the request if these functions do not return back to a trampoline.

c18n: Make stack unwinding a no-op when called without a trampoline
