CTSRD-CHERI/cheribsd

include/resolv.h
This strange padding array's size was underflowing in sandbox mode.
Since it also seems to make very little sense, let's remove it.
=> Remove padding in __res_state._u when in sandbox mode

tools/tools/atsectl/atsectl.c
Previously atsectl -gu would clear the wrong bit and generate a MAC
starting with 00:05:ed (Technikum Joanneum GmbH) instead of the correct
00:07:ed prefix.
=> Fix -g flag of atsectl

bin/cheritest/cheritest_util.c
vsnprintf() expects a va_list to be passed and not varargs
=> Fix cheritest_failure_err() not appending strerror(errno)

sys/mips/conf/CHERI_MALTA64, sys/mips/conf/CHERI_TEMPLATE
This means I can now add /tmp as tmpfs to /etc/fstab and get CHERIBSD
to boot up faster on QEMU. This is better than adding tmpmfs="YES" to
/etc/rc.conf as that only creates a 20 MB ramdisk for /tmp.
=> Enable tmpfs

bin/cheritest/cheritest.c, bin/cheritest/cheritest.h, bin/cheritest/cheritest_list_only.h, bin/cheritest/cheritest_vm.c
If the file is on tmpfs the tag bit will be discarded instead of an
exception being raised.
=> cheritest: XFAIL cheritest_vm_notag_tmpfile_shared if /tmp is tmpfs

lib/libthr/thread/thr_attr.c, lib/libthr/thread/thr_create.c, lib/libthr/thread/thr_exit.c, lib/libthr/thread/thr_init.c, lib/libthr/thread/thr_private.h, lib/libthr/thread/thr_stack.c, sys/mips/cheri/cheriabi_machdep.c, sys/mips/mips/vm_machdep.c
With these patches it is now possible to run a program using that uses pthreads.
There are probably still some parts of pthreads that won't work correctly but creating threads, joining and mutexes appear to work.
There is still one strange case where `pthread_join()` will return `EDEADLK` due to this code in thr_join.c:
```
if (pthread == curthread)
return (EDEADLK);
```
However, the debug output shows that the two are clearly different:
```
---Main thread 0x16043f000 waiting for thread 0x16043fe00 to join
join: EDEADLK pthread = 16043fe00, curthread = 16043fe00
```
This seems to only happen the first time the binary is run, so it could be caused by some TLS bug.
Could be related to #130
=> Fixes for CHERIABI pthreads

lib/libucl/Makefile, share/mk/bsd.cheri.mk
This makes it easy for me get a -O0 build of the CheriABI libraries+binaries by running `make CHERI_OPTFLAGS=-O0 buildworld`.
=> Add an easy way to override optimization level for CHERI compilation

contrib/binutils/bfd/elf64-mips.c, contrib/binutils/bfd/elfxx-mips.c, contrib/binutils/include/elf/mips.h, lib/libc/gen/setjmperr.c, lib/libc/mips/SYS.h, lib/libc/mips/gen/Makefile.inc, lib/libc/mips/gen/_ctx_start.S, lib/libc/mips/gen/_setjmp_c.S, lib/libc/mips/gen/cheriabi_pic_wrappers.c, lib/libc/mips/gen/setjmp_c.S, lib/libc/mips/gen/sigsetjmp.S, lib/libc/mips/sys/cerror.S, lib/libc/stdlib/abort.c, lib/libc/sys/__error.c
I can successfully run /bin/helloworld after these changes but not before (I tested this before John pushed fixes to the existing assembly for rtld-cheri-elf) so I am fairly confident that this change is correct.
=> Use PC-relative assembly for PIC libc

sys/mips/mips/swtch.S
When a process with per-thread qemu instruction tracing exits, the tracing
is not stopped until the next context switch, resulting in traces that contain
also instructions from whatever thread is scheduled after the sys_exit.
This moves the qemu tracing code in swtch.S so that it is not skipped by calls to cpu_throw().
=> Fix bug in per-thread tracing deactivation.

contrib/binutils/bfd/elfxx-mips.c, contrib/binutils/include/elf/mips.h, contrib/elftoolchain/readelf/readelf.c, contrib/file/magic/Magdir/elf, sys/kern/imgact_elf.c, sys/mips/cheri/cheriabi_machdep.c, sys/mips/include/elf.h, sys/mips/mips/elf_machdep.c
We now use the ELF e_flags field to detect CheriABI (using EF_MIPS_ABI_CHERIABI)  instead of comparing e_machine to EM_MIPS_CHERI. 
We can now also detect whether a binary has been compiled for CHERI 128 or 256 by looking at the e_flags EF_MIPS_MACH field: I added EF_MIPS_MACH_CHERI128 (0x00c10000) and EF_MIPS_MACH_CHERI128 (0x00c20000). The kernel will now check this and reject incompatible binaries. Old binaries with EM_MIPS_CHERI will still work but we should remove this support at some point in the future.
I have tested this both with pre-merge CHERI-clang with added e_flags (branch cheri-eflags38 in https://github.com/RichardsonAlex/llvm-cheri and https://github.com/RichardsonAlex/clang-cheri) and binaries generated with a compiler from the current master branch.
=> Use ELF e_flags to detect CHERI binaries

contrib/sendmail/src/conf.c
The pointer comparison for (LastArgv + 1 == argv[i]) means that LLVM decides to use LastArgv+1 in place of argv[i] in the subsequent strlen call, but since LastArgv points to the end of argv[i-1] (which has strict bounds on just that string) this immediately leads to a length violation. This behaviour is somewhat surprising and it is unclear what should happen here, but since CheriBSD is using libc's builtin setproctitle the results of this initialisation are unused, so we can just skip it.
=> sendmail: Make initsetproctitle a no-op if using the builtin setproctitle

lib/libc/mips/gen/_setjmp_c.S
Confusingly, _setjmp is noreorder, but setjmp is reorder. This means that the assembly in _setjmp has delay slots exposed, which must be filled. Otherwise, the first instruction in the next function is run, which in this case sets up a stack frame, causing stack corruption. Thankfully this was caught by a length violation of PCC in my fork.
Standard MIPS also has this difference between setjmp and _setjmp, but correctly fills this delay slot (also with the move pseudo-instruction).
=> _setjmp_c.S: Move instruction into missing delay slot like on MIPS

Makefile.inc1
I'm not sure if there is a better way that avoids all the `if ${MK_FOO}`
=> Fix building CHERI world without KERBEROS and CDDL options

sys/kern/kern_umtx.c
CheriABI binaries still need work, but this at least means MIPS (and hybrid) binaries should stop blocking (see #224).
=> Fix UMTX_OP_NWAKE_PRIVATE for MIPS binaries on CHERI kernels

sys/mips/mips/support.S
The second argument to Capability Store Conditional instructions is the value to store, not an offset, with the first one being where the boolean result is placed. Since we can do store conditionals without clobbering the source, unlike standard MIPS, we also no longer need to make a copy of the new value input and can just use a2 directly.
This was causing contested locks to have their owner cleared if subject to unfortunate timings, as casueword32_c is used to set the UMUTEX_CONTESTED flag on the owner when performing a UMTX_OP_MUTEX_WAIT.
=> Fix casueword{,32}_c zeroing destination

sys/Makefile, sys/cheri/cheri.h, sys/compat/cheriabi/cheriabi_misc.c, sys/mips/cheri/cheri_exception.c, sys/mips/mips/pm_machdep.c
I've built a CheriABI version of tests/sys/kern/ptrace_test.c (which is what I normally use when testing ptrace() things in FreeBSD aside from running the GDB test suite which is still a WIP on FreeBSD) and am working through getting those tests running.  I think Andrew had run into the PT_CONTINUE issue already as well.  I'll get back to this more next week in conjunction with other fixes other folks might have.  The next one the ptrace_test tests are blocking on is PT_LWPINFO.  I see that one is partially done already, but it needs something to convert it from native to CheriABI in the CheriABI wrapper.
=> PTrace fixes

sys/fs/smbfs/smbfs_smb.c, sys/kern/subr_mchain.c, sys/netsmb/smb_dev.h, sys/netsmb/smb_rq.c, sys/netsmb/smb_smb.c, sys/netsmb/smb_subr.c, sys/netsmb/smb_subr.h, sys/netsmb/smb_trantcp.c, sys/netsmb/smb_usr.c, sys/sys/mchain.h
This makes mount_smbfs work as a CheriABI binary at the cost of
breaking mips64 binaries.  I'll work 32- and 64-bit compat later.
Should fix #275 and half fixes #268.
=> Make smb use capabilities for IO.

contrib/jemalloc/include/jemalloc/internal/jemalloc_internal_types.h
LG_QUANTUM is supposed to represent the base alignment for a given
platform.  mips64 uses 16-byte stack-alignment by default in LLVM, and
also in FreeBSD (though the final fix for this isn't yet merged to
CheriBSD), so it should be using 4 instead of 3.  Similarly, cheri128
uses 16-byte alignment rather than 32.
This change changes mips64 from 8 to 16, and cheri 128 from 32 to 16.
=> Update LG_QUANTUM values for mips64 and cheri128.

sys/compat/cheriabi/cheriabi_ioctl.c, sys/compat/cheriabi/cheriabi_misc.c, sys/compat/cheriabi/cheriabi_mmap.c, sys/kern/kern_event.c, sys/kern/kern_proc.c, sys/kern/kern_sig.c, sys/kern/kern_umtx.c, sys/kern/subr_sglist.c, sys/kern/sys_pipe.c, sys/kern/sys_process.c, sys/kern/sysv_shm.c, sys/kern/uipc_syscalls.c, sys/kern/vfs_aio.c, sys/kern/vfs_vnops.c, sys/mips/cheri/cheriabi_machdep.c, sys/mips/mips/mem.c, sys/mips/mips/pm_machdep.c, sys/mips/mips/trap.c, sys/mips/mips/uio_machdep.c, sys/mips/mips/vm_machdep.c
Implicit CToPtr is really confusing because it returns 0 if the value
is not within the bounds of $ddc. I think in all of these cases we
actually want to be storing the vaddr since it would be nice to no
longer include all of userspace in the kernel $ddc.
I found these cases by adding a new warning to clang that triggers
for (most) CToPtr uses.
---
I think quite a few of these changes could be avoided if we change the behaviour of casting from `void*__capability` to integer types in the hybrid ABI.
In the pure ABI these will always return the address, but in the hybrid ABI it will be whatever CToPtr returns.
I think returning 0 instead of the address is rarely useful. I guess one argument is that if you get the address and then DDC changes you could accidentally access something that …
=> Avoid implicit CToPtr instructions in the kernel

bin/sh/histedit.c, lib/libedit/map.c, lib/libedit/readline.c
Now /bin/sh is no longer as annoying to use and it should also make delete
work in gdb.
Previously these key bindings only worked for the readline API but not
when using libedit. I believe it makes sense to always support common
bindings that users expect from other operatings systems default shells.
I don't use the vi mode so I'm not sure if the bindings make sense there or
if they should only be set for emacs mode.
I'll try to upstream this as well but for now I really want it in cheribsd.
=> Sane libedit key bindings

bin/cheritest/cheritest.c, bin/cheritest/cheritest.h, bin/cheritest/cheritest_vm.c, lib/libc/sys/kqueue.2, sys/kern/kern_event.c, sys/sys/event.h
There are some known ways to pass capabilities between separate address spaces that we probably don't want to have work.  Here are some more xfail-ing tests that will tell us when the situation improves. :)
=> cheritest: xfail some more known cap sharing vectors

bin/cheritest/cheritest.c, bin/cheritest/cheritest.h, bin/cheritest/cheritest_string.c, lib/libc/mips/string/jdw57_memcpy.c
This should help debugging tag violations due to underalinged destination
buffers such as setjmp/longjmp in csh (3dee3c077c6cfa41ef2a6d205be93b1a0350fadd).
=> abort() if memcpy would strip tag bits due to unaligned destination

lib/libgcc_eh/Makefile.inc
My little test program for C++ exceptions wasn't working again today on my branch (which enables assertions by removing -DNDEBUG) and I tracked down a few bugs.  Alex, I don't mind if we push the libunwind ones into llvm first or however it's easiest.
=> Another round of C++ exception fixes

sys/amd64/linux/Makefile, sys/amd64/linux32/Makefile, sys/arm64/linux/Makefile, sys/compat/cheriabi/Makefile, sys/compat/cloudabi32/Makefile, sys/compat/cloudabi64/Makefile, sys/compat/freebsd32/Makefile, sys/compat/freebsd64/Makefile, sys/i386/linux/Makefile, sys/kern/makesyscalls.sh
The Open Group says
> If file does not contain a \<slash\>, the shell shall use the search
> path specified by PATH to find the directory containing file.
and that's not what we want.
=> makesyscalls: always use relative path for syscalls.conf

bin/cheritest/cheritest_bounds_stack.c, sys/mips/cheri/cheri.c, sys/mips/cheri/cheriabi_machdep.c, sys/mips/include/vmparam.h
We need to round down the stack to 0x7ffbff0000 in order to represent a length of 0x3ff0000.
@jonwoodruff This works in QEMU, could you confirm that those values also work for the FPGA?
=> Fix booting with 14-bit bottom precision

ctsrd/lib/Makefile, tools/cheribsdbox/Makefile
libvuln_magic: only if MK_FILE
If we aren't making file and libmagic, don't make libvuln_magic either.
cheribsdbox: honor MK_USB
Skip crunching libusb and usbconfig if we aren't building with USB
These are necessary to fix cheribuild's cheribsd-minimal target on my
machine (verified by full clean build).
=> build: honor some MK_* flags

sys/amd64/include/fpu.h, sys/compat/freebsd32/freebsd32_misc.c, sys/compat/linux/linux_errno.inc, sys/contrib/edk2/Include/Base.h, sys/dev/pci/pci_user.c, sys/sys/signalvar.h, sys/x86/include/sigframe.h
I tried running `cheribuild.py cheribsd-native` and with these changes it gets through buildworld (if I disable openmp) but there are still some issues in the kernel.
=> A few kernel fixes to get closer to being able to build amd64 GENERIC

sys/dev/netmap/netmap_freebsd.c, sys/dev/netmap/netmap_kern.h, sys/kern/kern_mbuf.c, sys/kern/kern_sendfile.c, sys/kern/uipc_mbuf.c, sys/netgraph/ng_tty.c, sys/sys/mbuf.h
Use bounds derived from m_dat/m_pktdat (which should ideally be subobject
bounds set automatically by the compiler), pages coming from VM, clusters,
etc.  In one case, relating to netmap, more plumbing is required to find a
suitable bound dynamically.  The kernel boots, and simple loopback pings
and TCP over IPv4 appear to work.
=> First cut at changes to the mbuf allocator to place bounds on m_pages.

lib/libcheri/libcheri_sandbox_loader.c, libexec/rtld-elf/map_object.c, sys/compat/cheriabi/cheriabi_misc.c, sys/compat/cheriabi/cheriabi_mmap.c, sys/kern/sysv_shm.c, sys/mips/cheri/cheriabi_machdep.c, sys/mips/include/cherireg.h, sys/vm/vm_mmap.c
While touching this code I also converted the old CHERI_ALIGN_SHIFT macros to use the CRAM/CRAP compiler builtins.
=> Allow unrepresentable sizes in MAP_FIXED with MAP_CHERI_NOSETBOUNDS

lib/libc/gen/tls_malloc.c, sys/compat/cheriabi/cheriabi_mmap.c
After this commit we were no longer using the prot value as the default for
prot_max if no PROT_MAX() flags were passed. This resulted in all CheriABI
mmap() calls return a capability without load/store permissions and caused
crashes in tls_malloc.c.
=> Fix mmap() after de42c1c4229a0723196bfd0fab3b130ac5b32efe

sys/kern/genassym.sh, sys/kern/genoffset.sh, sys/sys/assym.h
This is a particularly... unusual dance and it breaks on CHERI.
`sys/assym.h` is used to create object files whose symbols have
structured names and associated values which encode constants available
to the C compiler, for example, the evaluation results of offsetof()
expressions.  Symbols and values can be extracted using `nm`.
`genoffset.sh` contains a pile of awk which inverts the encoding and
generates a C file which can be used to verify that the export was
successful.  `genassym.sh` contains a very similar pile of awk to
generate a #define-ful header file for use with C-preprocessing
assemblers.
The encoding that used to be used was to export 16 bits of the magnitude
of the value at a time, creating four (...{`w0`, `w1`, `w2`, `w3`})
symbols per export, as well as a symbol encoding …
=> sys/assym: use 8, not 16, bits when smuggling values

sys/mips/beri/beri_mp.c, sys/mips/include/cheriasm.h, sys/mips/malta/malta_mp.c, sys/mips/mips/locore.S, sys/mips/mips/mpboot.S
* Factor some very early boot code from locore.S to cheriasm.h and use
it in mpboot.S too.
* Move coprocessor initialization from platform_init_ap in beri_mp.c and
malta.c to mpboot.S.
Tests OK on CHERI BERI (DE4-multi-2) and CHERI Malta (options SMP & qemu
-smp 2).
Profuse thanks to Jonathan Woodruff, Ruslan Bukin, and Robert Watson.
I just push buttons; they figured out which ones needed to be pushed.
=> CHERI SMP: Install the correct caps at AP boot, too

sys/compat/cheriabi/cheriabi_misc.c, sys/kern/subr_uio.c
Without this change BODiagSuite panics the kernel because we create a very long
string that is just above the representable length.
This also rounds the AT_FOO capabilities, but maybe we should continue keeping
those as a KASSERT?
=> Round sizes of string and AT_FOO capabilities

sys/kern/kern_jail.c
iovec objects referencing a path, a jailname and a hostname used the same
invalid length, a number of bytes allocated to store copied in strings and
addresses passed to the jail system call.
This bug resulted in invalid memory access in kern_jail_set() that is called
from kern_jail(). When not exploited, the jail system call usually returned
EINVAL or ENAMETOOLONG due to incorrectly terminated strings, according to their
invalid lengths.
Note that FreeBSD does not include this bug. It was introduced with
IOVEC_INIT*() macros in CheriBSD.
=> Correctly initialize iovec lengths in kern_jail().

sys/kern/sys_process.c, sys/kern/sysv_shm.c, sys/mips/cheri/cheriabi_machdep.c, sys/mips/mips/trap.c, sys/sys/proc.h, sys/vm/vm_mmap.c
$c3 on MIPS is not call-safe, so it's ok if it gets overwritten with the
scalar value for syscalls returning integers.  v0 and c3 now always both
hold the first return value on return from all system calls.  This removes
the need for a hack in PT_SC_GET_RET.  tdu_retoff requires somewhat special
handling as the simple union case does not work for MIPS.
=> Change td_retval[] to an array of syscallarg_t and retire td_retcap.

Makefile, Makefile.inc1, share/mk/bsd.cheri.mk, share/mk/bsd.compiler.mk, share/mk/sys.mk
Going forward a CHERI capable toolchain will also be able to build
and link the matching non-CHERI bits.
=> Retire CHERI_CC and related variables.

sys/mips/mips/db_trace.c
Currently we use the return address, which will normally just give an
output that's off by 8 from the actual call site. However, for tail
calls, this is particularly bad, as we end up printing the symbol name
for the function that comes after the one that made the call. Instead we
should go back two instructions from the return address for the unwound
program counter.
=> sys/mips: Use call site for symbol name/offset when unwinding

sys/mips/cheri/cheriabi_machdep.c
- Use td_sa to reliably read the current system call code.
td_sa didn't exist when this code was first written, but it does
now and simpifies this code greatly.
- Remove an always-true condition from an assertion.
=> Trim some code from cheriabi_set_syscall_retval.

sys/compat/linux/linux_ipc.c, sys/kern/sysv_sem.c, sys/sys/sem.h, sys/sys/syscallsubr.h
The kernel union semun and struct semid_ds now contain capabilities for
all userspace pointers.
=> Remove union semun_native, ksemun_t, and usemun_t types.

sys/dev/altera/softdma/softdma.c
Testing locally failed to elicit the hoped-for dramatic improvement, but maybe I've missed something.  It doesn't break anything, seemingly, at least...
=> dev/altera/softdma: cache fifo depths

usr.sbin/makefs/ffs/mkfs.c
Found while building on a Linux PowerPC host.  Fix by inserting a cast.
Should this go upstream?
=> makefs: daddr_t may be 32 bit, even if off_t is 64

sys/cheri/cheric.h
f9e44f334302574cdccb99e837d1a527dc188fa7 causes cheric.h to be included
transitively in more places, including inside jemalloc.  The inclusion
of assert.h breaks the delicate dance done over there.  Thankfully,
simply not including it doesn't seem to otherwise break the build and
fixes the problem.
=> Don't include assert.h from cheric.h

sys/compat/freebsd32/freebsd32_proto.h, sys/compat/freebsd32/freebsd32_syscall.h, sys/compat/freebsd32/freebsd32_syscalls.c, sys/compat/freebsd32/freebsd32_sysent.c, sys/compat/freebsd32/freebsd32_systrace_args.c, sys/compat/freebsd32/syscalls.master, sys/compat/freebsd64/freebsd64_misc.c, sys/compat/freebsd64/freebsd64_uipc.c, sys/dev/mfi/mfi.c, sys/dev/mfi/mfi_ioctl.h, sys/dev/mrsas/mrsas_ioctl.c, sys/dev/mrsas/mrsas_ioctl.h, sys/dev/spibus/spigen.c, sys/kern/kern_sendfile.c, sys/kern/subr_uio.c, sys/kern/sys_generic.c, sys/kern/syscalls.master, sys/kern/systrace_args.c, sys/kern/uipc_syscalls.c, sys/kern/vfs_mount.c, sys/netinet/sctp_syscalls.c, sys/sys/_iovec.h, sys/sys/socket.h, sys/sys/spigenio.h, sys/sys/sysproto.h, sys/sys/uio.h
Assorted changes to remove the use of `struct iovec_native`.  The driver changes aren't complete, but fixing up ioctls in storage drivers don't see like a good use of time right now.  I did mfi part way because I'd gotten started...
=> Remove struct iovec_native

Makefile.inc1, lib/Makefile, share/mk/bsd.cheri.mk, sys/dev/xilinx/if_xae.c
These are some CheriBSD-specific build fixes.  I haven't yet completed a full build of recent CheriBSD (and will wait to start a new test when Brooks does the next merge of this week's upstream FreeBSD changes), but I feel pretty confident that these changes will be required at least.  My other riscv branch has some other changes, but I think they may not be required either to being specific to previous use of ld.bfd instead of lld, or conflicting with some other inflight purecap native cleanups, etc.
=> A few RISC-V build fixes

sys/kern/kern_proc.c, sys/netinet/sctp_syscalls.c, sys/sys/_stdint.h, sys/sys/_types.h
These are some simple fixes to build a "plain" RISC-V kernel.  The first is to deal with a regression I just introduced in my kevent_native change.
=> Simple compile fixes for RISC-V

sys/compat/cheriabi/cheriabi_misc.c, sys/compat/cheriabi/cheriabi_signal.h, sys/compat/cheriabi/cheriabi_util.h, sys/kern/kern_context.c, sys/mips/cheri/cheriabi_machdep.c, sys/mips/include/sigframe.h, sys/mips/include/ucontext.h, sys/mips/mips/freebsd64_machdep.c, sys/mips/mips/pm_machdep.c, sys/sys/_ucontext.h
- mcontext_t uses the CheriABI layout on MIPS in CHERI kernels.
- ucontext_t uses __kerncap for uc_link.
- Remove mcontext_c_t and ucontext_c_t.
- get/set_mcontext() now operate on the CheriABI context in CHERI
kernels.
- freebsd64_get/set_mcontext() convert to/from mcontext64 and mcontext_t.
In the case of a freebsd64_set_mcontext without a CP2 block,
mc_cheriframe is initialized from the trapframe before calling
set_context().
- sys_sigreturn(), sys_*context() now use copyin/outcap().
=> Make ucontext_t use capabilities for CHERI kernels.

sys/arm64/arm64/machdep.c, sys/conf/files.riscv, sys/conf/options.riscv, sys/riscv/include/frame.h, sys/riscv/include/md_var.h, sys/riscv/include/ucontext.h, sys/riscv/riscv/elf_machdep.c, sys/riscv/riscv/freebsd64_machdep.c, sys/riscv/riscv/genassym.c, sys/riscv/riscv/locore.S, sys/riscv/riscv/machdep.c
This depends on #367.  By itself it also doesn't build.  I have have some hacks that aren't really worth committing to permit building freebsd64 without capabilities.  Once we switch to a CHERI compiler I will be replacing those hacks with real CHERI bits instead.
The first two commits have already been upstreamed to FreeBSD today.
=> Basic freebsd64 for risc-v

sys/compat/freebsd64/freebsd64.h, sys/compat/freebsd64/freebsd64_misc.c, sys/compat/freebsd64/freebsd64_signal.c, sys/compat/freebsd64/freebsd64_signal.h, sys/mips/mips/freebsd64_machdep.c, sys/sys/event.h, sys/sys/systm.h
This PR replaces all pointer types in compat structures with uint64_t.
A few more fixes are required to properly create pointers/capabilities from user-provided integer addresses. A few copyin/out are changed to use capabilities explicitly as this will ultimately reduce the diff between the hybrid and pure kernels.
=> Freebsd64 uint64 struct pointer members.

sys/conf/files.mips, sys/mips/cheri/copystr_c.S, sys/mips/mips/bcopy.S
The assembly versions do not preserve tags which is starting to break the
kernel. We were crashing before because td->td_cheri_mmap_cap was becoming
detagged when fork()ing a new process (which memcpy()s the structure).
This also allows us to delete cheri_memcpy/cheri_bcopy which only handle
well-aligned sizes/pointers.
=> Stop using the assembly versions of memcpy on MIPS to preserve tags

sys/compat/freebsd64/freebsd64.h, sys/compat/freebsd64/freebsd64_misc.c, sys/compat/freebsd64/freebsd64_signal.c, sys/compat/freebsd64/freebsd64_time.c, sys/compat/freebsd64/freebsd64_uipc.c, sys/kern/imgact_elf.c, sys/kern/kern_exec.c, sys/sys/imgact_elf.h, sys/sys/socket.h, sys/sys/sysent.h
This PR makes all of freebsd64 EXPLICIT_USER_ACCESS.
Major changes are in uipc and freebsd64_copyout_strings.
- freebsd64_copyout_strings now builds a single user capability that covers the user stack, which is then split in multiple capabilities for the various things to copyout. This is consistent with the the native copyout_strings in kern_exec.c. Note that now user capabilities stored in image_params are valid. 
- uipc is changed to properly realign the control data to the kernel pointer size. This becomes necessary to support the purecap kernel. In the hybrid kernel the alignment could stay the same, however I currently align to capability size in both the hybrid and purecap variants to avoid introducing conditionals for combinations of kernel and userspace ABIs.
=> Freebsd64 explicit user access

bin/cheri_bench/Makefile, include/Makefile, lib/Makefile, lib/libc/Makefile, lib/libc/db/hash/Makefile.inc, lib/libc/gen/Makefile.inc, lib/libc/mips/gen/Makefile.inc, lib/libc/mips/string/Makefile.inc, lib/libc/sys/Makefile.inc, lib/libc/tests/sys/Makefile, lib/libcheri/Makefile, lib/libgcc_eh/Makefile.inc, lib/libsysdecode/Makefile, lib/libthr/Makefile, libexec/Makefile, libexec/rtld-cheri-elf-debug/Makefile, libexec/rtld-cheri-elf/Makefile, libexec/rtld-cheri-elf/tests/abi-mismatch/Makefile, share/mk/sys.mk
This allows us to use ${MACHINE_ABI:Mpurecap} instead of
(${MACHINE_ARCH:Mmips*c*} || ${MACHINE_ARCH:Mriscv*c*}).
I also added a hard-float vs soft-float value to this variable but that
is not currently used.
=> Introduce a MACHINE_ABI make variable

sys/riscv/conf/CHERI_SPIKE, sys/riscv/conf/SPIKE, sys/riscv/conf/std.MFS_ROOT
- Move NO_MODULES to std.MFS_ROOT since it is generally true for
kernels with an mfs root.
- Add TMPFS to std.MFS_ROOT to use the more efficient tmpfs for
/tmp and /var to avoid double caching.
- Include std.MFS_ROOT in SPIKE and let CHERI_SPIKE inherit it from
SPIKE.
- Use stock LMA for CHERI_SPIKE.  spike can use the "normal" OpenSBI
LMA with BBL.
=> Tidy the SPIKE kernel configs a bit.

share/mk/bsd.cheri.mk
This will allow us to remove some workarounds for offsets and should
already be the default for RISCV.
=> [MIPS purecap] Default to compiling with address interpretation of uintcap_t

sys/kern/kern_malloc.c, sys/kern/kern_proc.c, sys/kern/kern_sig.c, sys/kern/kern_umtx.c, sys/kern/subr_uio.c, sys/kern/vfs_aio.c, sys/libkern/bcopy.c, sys/mips/cheri/cheri_sealcap.c, sys/mips/cheri/cheri_signal.c, sys/mips/mips/pmap.c, sys/mips/mips/uio_machdep.c, sys/mips/mips/vm_machdep.c, sys/riscv/riscv/pmap.c, sys/sys/systm.h, sys/vm/pmap.h, sys/vm/vm_fault.c
These are replaced with the tag-preserving default bcopy and memcpy.
Instances of bcopy where tags are not meant to be preserved use
the machine-independent bcopynocap.
=> Remove redundant cheri_bcopy and cheri_memcpy.

lib/libc/riscv/sys/cerror.S
This change adds lots of macros to include/asm.h to avoid ifdefs inside
of cerror.S. I'm not sure if this is the best approach.
=> [RISCV-PURECAP] Implement cerror

sys/mips/include/cpufunc.h
The use of "int" here caused the compiler to believe that it needs to
insert a "sll $n, $n, 0" to sign extend as part of the implicit cast to
uint64_t.
=> [UPSTREAM] mips cpufunc: coproc regs are uint64_t

Makefile.inc1, contrib/atf/atf-c/check.c, contrib/atf/atf-c/detail/process.c, contrib/atf/atf-c/tc.c, contrib/tcpdump/netdissect.h, contrib/tcpdump/print.h, contrib/tcpdump/tcpdump.c, gnu/lib/Makefile, lib/Makefile, lib/libc/riscv/gen/_ctx_start.S, lib/libnetbsd/sys/cdefs.h, share/mk/bsd.opts.mk, share/mk/src.opts.mk
I have a few other hacks, but aside from tcpdump these are mostly not hacks.
Tested with `make TARGET_ARCH=riscv64 TARGET_CPUTYPE=cheri CROSS_TOOLCHAIN=cheri-clang WITHOUT_CLANG=yes WITHOUT_LLD=yes WITHOUT_LLDB=yes buildworld` where the cheri-clang toolchain sets XCC, XCXX, etc. to point to a CHERI llvm toolchain.
=> Various fixes towards getting a RISC-V hybrid world building

sys/riscv/riscv/trap.c
After this change we also print the values of (c)ra/(c)sp/(c)gp and (c)tp
(which was the missing register that I wanted to see).
=> Reduce ifdefs when printing CHERI/non-CHERI RISCV register dumps

sys/cddl/dev/dtrace/mips/dtrace_subr.c, sys/mips/mips/trap.c
As per https://reviews.freebsd.org/D24018, but for mips.
With this, KDB works when dtrace is compiled into kernel.
#397
=> Fix debug.kdb.enter with dtrace-enabled kernel for mips

lib/libcheri/libcheri_type.c
Otype field size was hard coded as 24 bits based on 256 bit capabilities.  The field size for (default) CHERI Concentrate 128 bit capabilities is 18 bits.  The existing implementation will fail if 2^18 types are requested.  See issue #408. 
This PR simply changes the hardcoded value to 18.
=> update field size for 128 bit capabilities

lib/libpam/modules/modules.inc, share/mk/bsd.crunchgen.mk, tools/cheribsdbox/Makefile
Use this to build libpam and libssh without kerberos support. This reduces
the size of cheribsdbox and means we don't need to add as many .so files to
the minimal disk image.
=> [UPSTREAM?] Allow building custom libs in bsd.crunchgen.mk

sys/compat/freebsd64/freebsd64_misc.c
It was not setting the SCTL_MASK64 before and this caused mount_smbfs to
fail when checking the vfs.conflist sysctl.
=> Fix FreeBSD64 sysctlbyname syscall

lib/libc/riscv/gen/_setjmp.S, lib/libc/riscv/gen/setjmp.S, lib/libc/riscv/gen/sigsetjmp.S, sys/riscv/include/setjmp.h
This keeps the same size jump buffer as the hybrid ABI.  The magic
value and capability registers take up two slots instead of 1.
Floating point registers are still packed as 8-byte values.  The
signal mask is still stored after the floating point, but that is in a
different slot for purecap than hybrid.
=> setjmp/longjmp for RISC-V purecap.

sys/cddl/compat/opensolaris/sys/vnode.h, sys/compat/freebsd64/freebsd64_misc.c
Compiling DTrace, I had the error that `kern_renameat` (sys/kern/vfs_syscalls.c:3565) was called with normal pointers, while it wanted capabilities as parameters.
I changed to call sites of `vn_rename` and `vn_remove` to call them with capabilities.
=> Fix vn_rename and vn_remove to accept capabilities

bin/cheritest/cheritest.c, bin/cheritest/cheritest_bounds_globals.c, bin/cheritest/cheritest_registers.c, bin/cheritest/cheritest_string.c
Unexpected failures:
test_initregs_stack: stack offset 3fdcf50 (expected range 7fc000 to 7fc000)
test_bounds_global_static_uint8_array65537: global: incorrect length (expected 65537, got 65664)
test_bounds_global_uint8_array65537: global: incorrect length (expected 65537, got 65664)
test_bounds_extern_global_array65537: global: incorrect length (expected 65537, got 65664)
test_unaligned_capability_copy_memcpy: Expected child termination with signal 6
test_unaligned_capability_copy_memmove: Expected child termination with signal 6
These are just symptoms of tests not being up to date with the world.
FIXES https://github.com/CTSRD-CHERI/cheribsd/issues/406
=> Fix some cheriabi cruft

share/mk/bsd.compat.mk
We were trying to build kyua against a non-existent obj-lib64 build tree for RISCV64/amd64.
=> Fix build of kyua

share/mk/src.opts.mk
MK_COMPAT_CHERIABI only makes sense on CPUs that support CHERI
(TARGET_CPUTYPE=cheri or MACHINE_CPUTYPE=cheri) and doesn't make sense
on pure=capability targets.
Fixes #423
=> Correct the logic for diabling COMPAT_CHERIABI.

lib/libc/Makefile, share/mk/src.opts.mk
Don't incorrectly build libcheri compatibility on riscv64c.
=> No libcheri on purecap

sys/mips/include/cpu.h
Just return to userspace and let it crash.
I looked at adding a printf, but the TRAPF_PC_SET_ADDR macro is used in
sufficently diverse places that I wasn't sure we could attribute the
error usefully.
This should address #427.
=> Don't panic when we produce an untagged PCC.

contrib/jemalloc/doc/jemalloc.3, contrib/jemalloc/include/jemalloc/internal/jemalloc_internal_inlines_c.h, contrib/jemalloc/include/jemalloc/internal/jemalloc_preamble.h, contrib/jemalloc/src/ctl.c, contrib/jemalloc/src/jemalloc.c
Require that the pointer be tagged (see #393) and that it's offset be zero
(see #342).  For an adversary who can't (or doesn't) adjust pointer bounds,
it sufficent to prevent forged or mis-bounded pointers from being returned
by later mallocs.
=> Add freed pointer sanity checks.

bin/cheritest/cheritest_cheriabi.c, lib/libsysdecode/mktables, sys/kern/imgact_aout.c, sys/kern/kern_exec.c, sys/kern/kern_proc.c, sys/sys/mman.h, sys/sys/syscallsubr.h, sys/sys/user.h, sys/vm/uma_core.c, sys/vm/vm_fault.c, sys/vm/vm_kern.c, sys/vm/vm_map.c, sys/vm/vm_map.h, sys/vm/vm_mmap.c, sys/vm/vm_unix.c, usr.bin/procstat/procstat.1, usr.bin/procstat/procstat.c, usr.bin/procstat/procstat_vm.c
Add an address-space reservation to each VM map entry.  Don't consolidate entries from different reservations.  When munmapping, replace unmapped space with new UNMAPPED mappings (almost, but not quite the same as guard pages).  Actually unmap the reservations only when the reservation has entirely transitioned to UNMAPPED.
Use the above functionality to allow mmapping of objects with unrepresentable sizes by padding the allocations.
=> Add support for the concept of an address-space reservation

sys/conf/Makefile.amd64, sys/conf/files.amd64
This was currently an ignored error but will change to a hard error
eventually.
Differential Revision:	https://reviews.freebsd.org/D24536
=> Don't try ctfconvert on file without debug info.

contrib/openpam/include/security/openpam.h
The PAM_MODULE_ENTRY() was incorrectly adding an additional underscore to
the section that contains all modules. This resulted in them being placed
in set__openpam_static_modules
relevant output of objdump -h -t before:
17 set__openpam_static_modules 00000160 00000000004ee5b0 DATA
0000000000000000  w      *UND*	0000000000000000 __start_set_openpam_static_modules
0000000000000000  w      *UND*	0000000000000000 __stop_set_openpam_static_modules
after:
17 set_openpam_static_modules 00000160 00000000004ee5b0 DATA
00000000004ee5b0 g       set_openpam_static_modules	0000000000000000 .protected __start_set_openpam_static_modules
00000000004ee710 g       set_openpam_static_modules	0000000000000000 .protected __stop_set_openpam_static_modules
=> [UPSTREAM] Fix openpam_static_modules

sys/mips/conf/BERI_DE4_BASE, sys/mips/conf/BERI_SIM_BASE, sys/mips/conf/CHERI128_MALTA64, sys/vm/vm_glue.c
After running into the buzzsaw of trying to rebase my earlier merge fix for the kstack issue, I decided to instead break out most of the cleanups into an earlier set of commits.  Once this is done, the merge is much simpler to resolve.  This doesn't include the actual merge as I plan to do that and push it to dev after this has landed on dev.
This should also fix #417
=> kstack allocation cleanups

cddl/contrib/opensolaris/common/ctf/ctf_lookup.c
The problem arose when `p = "s"`, and `lp->ctl_prefix = "struct"`.
`strncmp("s","struct",1)` returns 0, because it checks only the first char.
The following line was advancing `p(="s")` by 6, going over the terminator.
(the value of p can be user controlled)
=> Fix CTF pointer overrun (in userland)

usr.sbin/kldxref/ef_mips.c
`dest` is a capability with len L. The code was advancing this pointer by (way) more than L, invalidating the TAG, and then make it step back. However, at the end the TAG was still invalid. 
After the changes, the offset is pre-computed.
=> Fix kldxref cheri-related issue

Makefile.inc1, lib/libc/tests/gen/posix_spawn/Makefile, lib/libc/tests/sys/Makefile, lib/libpmc/Makefile, stand/defs.mk, stand/efi/Makefile.inc, stand/efi/boot1/Makefile, stand/efi/loader/Makefile, stand/i386/boot2/Makefile, stand/i386/pxeldr/Makefile, stand/i386/zfsboot/Makefile
With these changes I am able to build an x86_64 disk image an run it on qemu-system-x86_64 on a Linux host.
I'd like to get these into CheriBSD first so that we can boot x86 in Jenkins. Once it's merged here, I'll open upstream reviews.
=> Fix native crossbuild

CHERI-UPDATING.md, README.md
This document describes our branches, updating practices, and will be used
to document flagdays.  I've added a couple recent flagdays as examples.
=> First cut at a CHERI-UPDATING document.

sys/mips/mips/trap.c
I think we can't use __USER_CODE_CAP() here since the PCC value
(curthread->td_pcb->pcb_regs.pcc) that it derives from may use a different
base. The addr variable is not longer a virtual address and has been
changed to char* __capability. It holds the current trap $pcc, so use that
in fuword32_c instead.
=> Fix an incorrect __cheri_fromcap/__USER_CODE_CAP in trap.c

lib/libproc/tests/proc_test.c
For a purecap world we use ld-elf.so.1, but for libcheri it should be
ld-cheri-elf.so.1. Reuse paths.h from RTLD to get the correct name.
=> [UPSTREAM] Fix path to RTLD in libproc/proc_test.c

sys/mips/mips/pm_machdep.c
It seems that the `md_tls` field was never cleared in `exec_setregs`. This results in weirdness if the old TLS pointer (capability) is retained.
=> Make sure we clear MIPS user TLS pointer on exec.

sys/kern/kern_exec.c
Creating this PR as a bit of a testing trial balloon.
=> Switch the default sysvec for purecap binaries to the native ABI.

cddl/contrib/opensolaris/lib/libzfs/common/libzfs_pool.c, cddl/contrib/opensolaris/lib/libzfs/common/libzfs_sendrecv.c, cddl/contrib/opensolaris/lib/libzfs/common/libzfs_util.c, cddl/contrib/opensolaris/lib/libzfs_core/common/libzfs_core.c, sys/cddl/contrib/opensolaris/common/zfs/zfs_ioctl_compat.c, sys/cddl/contrib/opensolaris/common/zfs/zfs_ioctl_compat.h, sys/cddl/contrib/opensolaris/uts/common/fs/zfs/spa_errlog.c, sys/cddl/contrib/opensolaris/uts/common/fs/zfs/sys/spa.h, sys/cddl/contrib/opensolaris/uts/common/fs/zfs/sys/zfs_ioctl.h, sys/cddl/contrib/opensolaris/uts/common/fs/zfs/zfs_ioctl.c, sys/dev/cxgb/cxgb_ioctl.h, sys/dev/cxgb/cxgb_main.c, sys/dev/mpr/mpr_ioctl.h, sys/dev/mpr/mpr_user.c, sys/dev/mps/mps_ioctl.h, sys/dev/mps/mps_user.c, sys/dev/ofw/openfirmio.c, sys/dev/ofw/openfirmio.h
A third round of changes for drivers not included in MIPS builds but included in RISC-V builds.  mpr, mps, and ZFS all have the anti-pattern of assuming that uint64_t can hold any pointer to avoid having to deal with compat32 shims.
=> Explicit copyout 3

sys/conf/files, sys/conf/files.mips, sys/conf/kern.pre.mk, sys/modules/Makefile, sys/modules/dtrace/Makefile, sys/modules/dtrace/dtraceall/dtraceall.c, sys/modules/dtrace/fasttrap/Makefile
The necessary glue has been added to compile `fasttrap` into the kernel, and not as a dynamically loadable module (which is still possible).
Also, systrace_freebsd32 is not compiled if we are in mips. As there were too many errors.
**After this change, nothing new is compiled** (at the moment, dtrace is not compiled)
=> Make possible to compile the fasttrap module into kernel

Jenkinsfile
We can still manually trigger builds or add special labels.
=> Don't build pull requests on every push to dev/master

sys/kern/kern_exec.c, sys/sys/systm.h
Move 64-bit pointer handling under COMPAT_FREEBSD64.  This required
adding a fuecap alias that maps to fueword for non-CHERI platforms.
=> Update get_argenv_ptr() to assume CHERI as the default ABI.

sys/riscv/riscv/exception.S, sys/riscv/riscv/locore.S
This instruction is nop.  Instead, mimic the existing non-CHERI code
and store a zeroed ct0 to sscratchc.
=> Don't try to store cnull (c0) to sscratchc.

sys/riscv/conf/CHERI_QEMU_MFS_ROOT, sys/riscv/conf/QEMU, sys/riscv/conf/QEMU_MFS_ROOT
This is currently needed for running tests on RISC-V
=> Include SMBFS kernel modules in QEMU kernels

contrib/jemalloc/src/jemalloc.c
This both hardens malloc against off-by-one array bugs and allows the
array to be freed when it is resized.  Perviously, resizing resulted in
an assertion in unbound_ptr() due to a base != 0.
=> Fix assertion in calloc

bin/Makefile, bin/cheritest/Makefile, bin/cheritest/cheritest.c, bin/cheritest/cheritest_bounds_stack.c, bin/cheritest/cheritest_cheriabi.c, bin/cheritest/cheritest_cheriabi_open.c, bin/cheritest/cheritest_fault.c, bin/cheritest/cheritest_registers.c, bin/cheritest/cheritest_sealcap.c, bin/cheritest/cheritest_string.c, bin/cheritest/cheritest_syscall.c, bin/cheritest/cheritest_vm.c, share/mk/bsd.opts.mk
Use a large hammer and disable anything vaguely mips-specific on non-mips.  This is similar to an approach taken by @zxombie elsewhere.
=> Port cheri(abi)test to riscv

lib/libc/sys/ioctl.c
There were cases in which the size of the ioctl parameter was defined as zero, but parameters were passed anyways (e.g. in fasttrap).
=> Fix ioctl arguments behaviour when size is zero

sys/mips/conf/CHERI_MALTA64
Accidentally built this instead of CHERI128_MALTA64 (getting used to the RISC-V names without the "128") and tripped over this.
=> Fix CHERI_MALTA64

cddl/contrib/opensolaris/lib/libdtrace/common/dt_module.c, sys/conf/kern.opts.mk, sys/conf/kern.post.mk
For mips, the CTF section is now generated from the symbols in `.dynsym`. `.dymsym` only contains a subset of the `.symtab` symbols, needed for dynamic linking. This flag is needed because  the kernel`.symtab` section is not loaded at boot time, and its address is not available anywhere. 
DTrace, the only consumer of those data, uses the `.dynsym` table.
=> Fix kernel CTF problems with mips

cddl/contrib/opensolaris/lib/libdtrace/common/dt_module.c
This follows #466 
The string table for `.dynsym` is not `.strtab`, but `.dynsym`.
Now the output of DTrace `stack()` is nicer
=> Fix string table name for DTrace when using .dynsym

bin/cheritest/cheritest.c, bin/cheritest/cheritest.h, bin/cheritest/cheritest_bounds_globals.c, bin/cheritest/cheritest_bounds_stack.c, bin/cheritest/cheritest_registers.c, bin/cheritest/cheritest_vm.c, libexec/rtld-cheri-elf/Makefile, sys/cheri/cheri_exec.c, sys/kern/imgact_elf.c
With these changes all cheritests should succeed/xfail.
The result of cheritest_vm_cap_share_sigaction seems to not be consistent so XFAIL sometimes results in an XPASS.
=> Make jenkins green again

sys/mips/mips/elf_machdep.c
This fixes dynamic binaries in a hybrid world.
=> Use ld-cheri-elf.so.1 if it exists for purecap.

share/mk/bsd.cpu.mk
This is a hack due to code thinking that !defined(__LP64__) is the same
as defined(__ILP32__).  We need to audit the tree and fix these.
=> Define __LP64__ on CHERI-RISC-V

lib/libsimple_printf/Makefile, share/mk/bsd.compiler.mk, share/mk/bsd.lib.mk, share/mk/bsd.opts.mk, share/mk/bsd.prog.mk, tools/build/options/WITH_INIT_ALL_PATTERN, tools/build/options/WITH_INIT_ALL_ZERO
There are two options:
- WITH_INITALL_ZERO: Zero all variables on the stack.
- WITH_INITALL_PATTERN: Initialize variables with well-defined patterns.
The exact pattern are a compiler implementation detail and vary by type.
I've used WITH_INITALL_* to matches Microsoft's InitAll feature rather
than naming them after the LLVM specific compiler flags.
=> Add support for initializing stack variables on entry.

sys/mips/malta/malta_mp.c
The APs should jump over any "get the machine going" bootloader code
that QEMU shoves into our physical address space.  Otherwise, we end up
back in the QEMU MIPS MALTA bootloader trying to reconfigure the PCI
BARs, and that's not going to go well for anyone.  (In practice, the
first store to the BAR register triggers a data bus fault and the AP
ends up falling through to the initialization code again and faulting
again and again...)
(The curious are pointed at QEMU's hw/mips/malta.c:/write_bootloader and
the bit of code labeled "Load BAR registers as done by YAMON".)
This fixes issues observed while testing https://github.com/CTSRD-CHERI/qemu/pull/76
=> QEMU MIPS MALTA SMP: set tcrestart to _locore

contrib/jemalloc/include/jemalloc/internal/jemalloc_internal_externs.h, contrib/jemalloc/include/jemalloc/internal/private_namespace.h, contrib/jemalloc/include/jemalloc/internal/tcache_inlines.h, contrib/jemalloc/src/arena.c, contrib/jemalloc/src/ctl.c, contrib/jemalloc/src/jemalloc.c, contrib/jemalloc/src/large.c
When this is set, allocations are zeroed during free().
=> Add a new 'zero_free' option.

Makefile.inc1, share/mk/sys.mk
Without this change, cheribuild's test scripts have to know whether we are
running a hybrid rootfs/sysroot or a purecap one to determine whether to
use /usr/lib or /usr/libcheri for libraries (and the same for lib64).
Having libcheri always point to CHERI libraries (either by being a symlink
to lib or a real directory makes writing tests much simpler since we can
always use /usr/libcheri for pure-capability libraries and /usr/lib64 for
hybrid/non-CHERI ones.
A hybrid sysroot now looks as follows:
```
$ ll sdk/sysroot128
drwxrwxr-x 4 alr48 alr48   4096 Jun 17 10:44 lib
lrwxrwxrwx 1 alr48 alr48      3 Jun 17 10:44 lib64 -> lib
-rw-rw-r-- 1 alr48 alr48 443439 Jun 17 10:44 METALOG
drwxrwxr-x 7 alr48 alr48   4096 Jun 17 10:44 usr
$ ll sdk/sysroot128/usr
drwxrwxr-x 51 alr48 alr48 12288 Jun 17 …
```
=> Add libcheri/lib64 symlinks for the native ABI

bin/cheritest/cheritest.c, bin/cheritest/cheritest.h, bin/cheritest/cheritest_fault.c, sys/mips/mips/trap.c, sys/riscv/riscv/trap.c
This enables CHERI exception tests on RISC-V.  Most of these pass, but one is an XFAIL since QEMU doesn't implement the PTE bits for CHERI.
=> RISC-V exception cheritests

sys/kern/kern_proc.c
The assert valid, but the bug is fairly harmless and panic on debugger exit is unhelpful.
This reverts commit a8ea5ca76fea33a70e4998f2999c6e9e48a5d637.
=> Revert "Assert on pg_jobc state."

libexec/rtld-cheri-elf/mips/rtld_machdep.h, libexec/rtld-cheri-elf/riscv/rtld_machdep.h
While changing this line also update the comment above to ensure that we
don't remove the required addend support.
=> rtld-cheri-elf: Create sentries on RISC-V

bin/cheritest/cheritest_cheriabi_open.c, bin/cheritest/cheritest_registers.c
"Fix" PCC length and stack offset tests.  In the former case, just increase the constant.  In the latter, test something closer to what we meant to test.
=> cheriabitest RISC-V fixes

bin/cheritest/cheritest.c, bin/cheritest/cheritest.h, bin/cheritest/cheritest_vm.c, sys/fs/tmpfs/tmpfs_subr.c, sys/mips/cheri/cheri_debug.c, sys/mips/cheri/cheri_exception.c, sys/mips/include/cherireg.h, sys/mips/mips/trap.c, sys/riscv/cheri/cheri_exception.c, sys/riscv/include/pte.h, sys/riscv/include/riscvreg.h, sys/riscv/riscv/locore.S, sys/riscv/riscv/pmap.c, sys/riscv/riscv/trap.c, sys/sys/signal.h, sys/vm/vm_fault.c, sys/vm/vm_object.c, sys/vm/vm_object.h
Note that the PTE bits haven't been working on MIPS since January due to a merge-o as far as I can tell.  However, this was masked by the existing test in cheritest being skipped due to tmpfs, so the last commits here turn off storing tags in tmpfs so that the test will be tested in Jenkins going forward.  If we want to revisit the tmpfs case we should fix the test to DTRT.
We still need a test case that tag-stripping DTRT on the load side.  I'm not quite sure how to contrive a case where you can have a tag in memory and then remap the page with LC cleared using our current APIs.  We would almost need a `MAP_NOTAGS` hack or something to be able to test that.
=> Support for CHERI-RISC-V PTE bits

bin/cheritest/cheritest.c, bin/cheritest/cheritest.h, bin/cheritest/cheritest_registers.c
Succeeds for MIPS and RISC-V once the various pull requests are merged.
Partially addresses #555. We probably also want tests for function pointers.
=> cheriabitest: Check that the return cap is a sentry

bin/cheritest/cheritest.c, bin/cheritest/cheritest.h, bin/cheritest/cheritest_signal.c, sys/cheri/cheri.h, sys/cheri/cheri_exec.c, sys/cheri/cheri_usercap.c, sys/cheri/cheric.h, sys/mips/cheri/hybridabi_machdep.c, sys/mips/mips/pm_machdep.c, sys/riscv/cheri/cheri_machdep.c, sys/riscv/riscv/locore.S, sys/riscv/riscv/machdep.c
This ensures signal handlers see a sentry for their return capability. Test was confirmed to be broken (saw otype -1) without the kernel change.
=> Create sentries for userspace code capabilities

bin/cheritest/cheritest.c, sys/amd64/amd64/pmap.c, sys/arm/arm/pmap-v4.c, sys/arm/arm/pmap-v6.c, sys/arm64/arm64/pmap.c, sys/i386/i386/pmap.c, sys/i386/i386/pmap_base.c, sys/i386/include/pmap_base.h, sys/mips/mips/pmap.c, sys/powerpc/aim/mmu_oea.c, sys/powerpc/aim/mmu_oea64.c, sys/powerpc/aim/mmu_radix.c, sys/powerpc/booke/pmap.c, sys/riscv/riscv/pmap.c, sys/vm/pmap.h, sys/vm/vm_fault.c, sys/vm/vm_map.c
The pmap_enter_object case fixes the divergence between RISC-V and MIPS
regarding cross-AS SHM_ANON cheritest. On MIPS we failed open, but on
RISC-V we failed closed, as both lacked flags. Since we're doing all
this for pmap_enter_object, which shares code with pmap_enter_quick, we
might as well hook flags up for the latter and remove the restriction on
its use.
This partially reverts 2bd5e17042e3ba083e85468b144c2435a960a9e4.
=> Propagate pmap flags to pmap_enter_quick and pmap_enter_object

sys/mips/cheri/cheri_exception.c, sys/mips/include/cherireg.h, sys/sys/signal.h
These were used for the in-kernel trusted stack, but I don't think we will use them again on MIPS and won't use them on RISC-V.
=> Remove software CHERI traps

secure/lib/libcrypto/Makefile
Fixes https://github.com/CTSRD-CHERI/cheribsd/issues/526 (strict aliasing
violation in bn_nist.c results in ssh keys not being accepted).
This error only affects bn_nist.c, but considering the overall "quality" of
this code we should probably apply it to all source files since OpenSSL
developers appear to like unions and pointers casts a bit too much.
=> Compile bn_nist.c with -fno-strict-aliasing

share/mk/src.opts.mk, sys/kern/kern_mib.c, sys/mips/include/param.h, sys/riscv/include/param.h, sys/riscv/riscv/elf_machdep.c, sys/riscv/riscv/freebsd64_machdep.c, tools/cheribsdbox/Makefile
Mostly apply to RISC-V, but as I was fixing MACHINE_ARCH for RISC-V I noticed we never did the same on MIPS.
(Ignore kernel hashes for MIPS, I tweaked some RISC-V things, rebased and didn't bother rebuilding)
mips-hybrid:
```
root@qemu-cheri128-jrtc4:~ # uname -p
mips64
root@qemu-cheri128-jrtc4:~ # /smbfs/output_root/rootfs128/sbin/sysctl kern.version kern.supported_archs hw.machine_arch
kern.version: FreeBSD 13.0-CURRENT #5 240e14417342-c327690(riscv-freebsd64): Tue Jun 23 23:47:00 BST 2020
jrtc4@zeno.sec.cl.cam.ac.uk:/home/jrtc4/cheri/build/cheribsd-mips-hybrid128-build/home/jrtc4/cheri/cheribsd/mips.mips64/sys/CHERI_MALTA64
kern.supported_archs: mips64c128 mips64
hw.machine_arch: mips64
root@qemu-cheri128-jrtc4:~ # /smbfs/output_root/rootfs-purecap128/sbin/sysctl kern.version …
```
=> Enable freebsd64 on RISC-V and MACHINE_ARCH fixes

Makefile.inc1
We should be using the mips64 triple and not cheri.
=> Avoid deprecation warning when compiling purecap MIPS code

sys/conf/newvers.sh
We're looking for file content differences, so ask the question of git
more directly.  This helps a lot, saving tens of thousands of fork()s,
when the builder and editor see different stat() results (e.g., UIDs),
as they might with containers.
=> [UPSTREAM] Speed up newvers.sh git_tree_modified

sys/conf/files, sys/conf/files.riscv, sys/dev/extres/syscon/syscon_power.c, sys/riscv/conf/GENERIC, sys/riscv/riscv/riscv_syscon.c
This device driver supports both syscon-power and syscon-reset devices,
as specified in [1] and [2]. These provide a very simple interface for
power and reset control, and among other things are used by QEMU's virt
machine on RISC-V. Thus, include them as part of the RISC-V GENERIC
kernel config.
We also need to ensure that we have attached the syscon_generic device
before attaching any syscon_power devices, and so we introduce a new
riscv_syscon device akin to aw_syscon added in r327936.
[1] https://www.kernel.org/doc/Documentation/devicetree/bindings/power/reset/syscon-poweroff.txt
[2] https://www.kernel.org/doc/Documentation/devicetree/bindings/power/reset/syscon-reboot.txt
=> Add syscon power and reset control device driver for RISC-V

Jenkinsfile
A follow-up commit will archive the resulting files for non-pull-request branches
so that they can be used for testing in downstream jobs.
=> Jenkins: Also build MFS_ROOT kernels

sys/libkern/bcopy_c.c
We are trying to print a uintptr_t as a void * so cast through it.
=> Fix the KASSERTs in bcopy_c to cast to a void *

Jenkinsfile
This ensures that we don't break the build.
=> Add AArch64 to Jenkins builds

sys/cam/scsi/scsi_cd.c
I had this lying around in a stale branch.  I think it helps for purecap?
=> Use a uint64_t for the user pointer in struct ioc_read_toc_entry64.

sys/cheri/cheric.h, sys/compat/linux/linux_mmap.c
We may need this extra userland change, I'm not sure whether it is the best way to do this but we essentially need `bool` because we end up including `cheri/cheric.h` as libprocstat pretends to be the kernel when including mount.h.
=> Purecap kernel cleanup fix

sys/mips/conf/std.MALTA, sys/riscv/conf/FETT, sys/riscv/conf/QEMU
Fall back to the previous default if not present.  This allows us boot
independent of the existance of a partition table provided that
the root filesystem is named "root".  A followup change to cheribuild
will make this so.
=> Default to mounting root from /dev/ufs/root.

bin/cheritest/Makefile, bin/cheritest/cheritest.c, bin/cheritest/cheritest.h
(It produces arbitrary capabilities using DDC).
=> By design the swap test can't work on purecap.

sys/riscv/riscv/exception.S
This instance predated the cllc psuedo instruction.
=> Use cllc in exception entry.

contrib/openpam/lib/libpam/openpam_ttyconv.c
On a sufficently slow system controlled by an expect script, it's
possible to lose this race and lose some password input.
=> Avoid a race between printing the prompt and accepting input.

sys/conf/files, sys/dev/goldfish/goldfish_rtc.c, sys/riscv/conf/GENERIC
This device was originally used as part of the goldfish virtual hardware platform used for emulating Android on QEMU, but is now also used as the RTC for the RISC-V virt machine in QEMU. It provides a simple 64-bit nanosecond timer exposed via a pair of memory-mapped 32-bit registers, although only with 1s granularity.
=> Add Goldfish RTC device driver for RISC-V

lib/libc/db/hash/Makefile.inc, libexec/rtld-cheri-elf-debug/Makefile, libexec/rtld-cheri-elf/tests/abi-mismatch/Makefile, share/mk/bsd.cpu.mk, share/mk/sys.mk, sys/conf/kern.mk
The second change is required so that `MACHINE_ABI` is set correctly in kern*.mk which purecap kernels need.
=> Riscv fixes

sys/riscv/conf/CHERI-FETT, sys/riscv/conf/CHERI-FETT-NODEBUG, sys/riscv/conf/CHERI-GFE, sys/riscv/conf/CHERI-GFE-NODEBUG, sys/riscv/conf/CHERI-QEMU, sys/riscv/conf/CHERI-QEMU-MFS-ROOT, sys/riscv/conf/CHERI-QEMU-MFS-ROOT-NODEBUG, sys/riscv/conf/CHERI-QEMU-NODEBUG, sys/riscv/conf/CHERI-SPIKE, sys/riscv/conf/CHERI-SPIKE-NODEBUG, sys/riscv/conf/CHERI_FETT, sys/riscv/conf/CHERI_GFE, sys/riscv/conf/CHERI_QEMU, sys/riscv/conf/CHERI_QEMU_MFS_ROOT, sys/riscv/conf/CHERI_SPIKE, sys/riscv/conf/FETT-NODEBUG, sys/riscv/conf/GENERIC-NODEBUG, sys/riscv/conf/GFE, sys/riscv/conf/GFE-NODEBUG, sys/riscv/conf/QEMU-MFS-ROOT, sys/riscv/conf/QEMU-MFS-ROOT-NODEBUG, sys/riscv/conf/QEMU-NODEBUG, sys/riscv/conf/QEMU_MFS_ROOT, sys/riscv/conf/SPIKE, sys/riscv/conf/SPIKE-NODEBUG, sys/riscv/conf/std.MFS-ROOT, sys/riscv/conf/std.NODEBUG
Also switches the canonical RISC-V kernel names to kebab-case rather than snake_case. The old names are left as aliases for compatibility.
=> RISC-V -NODEBUG kernels

Jenkinsfile
This is only done for the master and dev branches to avoid
wasting space. The dev branch also only retains the last two
builds for the same reason.
This should allow migrating downstream jobs to using the sysroot
and kernel provided by this job.
=> Archive sysroot, images and kernels in Jenkins

sys/fs/nfs/nfsport.h, sys/fs/nfsserver/nfs_nfsdport.c
struct nfsex_args contains pointers and requires both annotation
and the use of copyincap().
=> Fix NFSv4 exports.

sys/mips/mips/trap.c
This is what I merged upstream to FreeBSD.
=> Set ksi_addr to badvaddr for all TLB faults regardless of signal.

sys/conf/options, sys/fs/nfsserver/nfs_nfsdsocket.c, sys/kern/init_main.c, sys/kern/kern_time.c, sys/netinet/in_mcast.c, sys/netinet6/in6_mcast.c
Add options to enable historic vulnerabilities as a target for attackers in red-team or capture-the-flag exercises.
=> Optionally restore historic vulnerabilities

lib/libc/gen/dlfcn.c, sys/kern/imgact_elf.c, sys/sys/imgact_elf.h
In practise this was already the case since capability rpecision means that
capabilities with base 0x12... and address zero cannot be tagged. However,
becoming unrepresentable means that the bounds values are meaningless.
To avoid software from interpreting these bounds, use a NULL-derived
capability instead.
While changing dlfcn.c also change a p_filesz that should probably be p_memsz.
=> Make AT_BASE untagged for static binaries

lib/libc/string/Makefile.inc, lib/libc/string/Symbol.map, lib/libc/string/bcopy.c, lib/libc/string/memcpy_c.c, lib/libc/string/memmove_c.c
- Fix the location of __capability in pointers
- Use __cheri_addr when getting an address value
=> Fix building bcopy.c for CHERI

sys/cheri/cheri.h, sys/riscv/cheri/cheri_machdep.c, sys/riscv/include/cheri.h, sys/riscv/riscv/locore.S, sys/vm/swap_pager.c
The first bits of this for `userspace_cap` are pulled from the purecap changes.  The other bits are just things I failed to initialize on RISC-V previously.  `user_sealcap` is still missing on RISC-V as well since we haven't added the custom `sysarch()` methods to work with it.
=> Riscv init cap

sys/riscv/riscv/exception.S, sys/riscv/riscv/swtch.S
ct0 is the alternate link register, so u-arch's might infer incorrect
branch prediction hints from these jumps.
=> Use ct1 as the target of cjr when entering/exiting capmode.

bin/cheri_bench/cheri_bench.c, include/string.h, lib/libc/mips/string/Makefile.inc, lib/libc/string/Makefile.inc
In purecap code, both are equivalent (and should be identical
implementations), so this is just a waste of space. Instead we can just
define the explicit capability versions to the normal pointer versions.
For convenience, like how we define __capability to nothing when CHERI
is not available, also define them as aliases for their pointer versions
when CHERI isn't available, meaning hybrid code can make use of CHERI
features without needing so many #ifdef's. The kernel currently does
this with memcpy_c for non-CHERI builds, too.
=> Don't have memcpy_c and friends duplicate their non-_c versions for purecap

libexec/rtld-cheri-elf/mips/rtld_machdep.h, libexec/rtld-cheri-elf/tests/abi-mismatch/utils.h, sys/cheri/cherireg.h
I grepped for _MIPS_SZCAP and axed cases that handled 256.  I left `__XSTRING(_MIPS_SZCAP)` instances around, and I've left uses of the value for sizing jmpbuf, etc. around also.
There were some other instances I saw in libunwind and cheri-c-tests that should be fixed in their respective upstream repositories at some point.
=> Remove some more CHERI-256 bits based on _MIPS_SZCAP

sys/kern/kern_sysctl.c, sys/libkern/bcopy.c, sys/libkern/bcopy_c.c, sys/sys/systm.h
This does pull in some purecap #ifdef's, but it seems cleaner to do that than to try to untangle them and then deal with merge conflicts down in the purecap branch.
There is one purecap-only MIPS change in the riscv branch that this doesn't include that will need to be pulled into the main purecap kernel branch if this is looped back before the riscv branch is merged.
=> Sysctl nocap

sys/dev/virtio/pci/virtio_pci.c, sys/mips/conf/std.MALTA
This simply applies the two recent upstream commits to allow virtio to work again for MIPS.
However, using virtio-blk-pci for the disk does not work since the interrupt allocation fails (GDB points at gt_pci.c), but I haven't investigated.
=> Enable virtio for MIPS

sys/kern/kern_flag.c
It's imporant to know which ABI was used to call the system call
and it might be of interest for the kernel function.
=> flag_captured(2|9): Log the ABI of the calling process.

bin/cheritest/cheritest_fault.c, lib/csu/common-cheri/crt_init_globals.c, lib/libc/gen/dlfcn.c, lib/libc/gen/tls_malloc.c, lib/libmalloc_simple/malloc.c, libexec/rtld-cheri-elf/mips/cheri_plt.cpp, libexec/rtld-elf/rtld.c, sbin/dhclient/Makefile, sys/cheri/cheric.h, sys/compat/freebsd64/freebsd64_misc.c
We need to add a few __DECONST/type casts since the builtins are now type
and const preserving.
I also had to silence a -Waddress-of-packed-member in dhlient since that
appears to be triggered now that the builtins are type preserving.
=> Allow compiling with overloaded CHERI builtins

sys/conf/kern.mk
CHERI_SUBOBJECT_BOUNDS_STATS enables capture of statistics,
CHERI_SUBOBJECT_BOUNDS_STATS_FILE sets the file name for the clang CHERI statistics,
defaults to kernel-subobject-bounds-stats.csv in the kernel build directory.
=> Add kernel make option to capture subobject bounds statistics.

sys/kern/kern_exec.c
This will fail because the process sysent is not yet set.
=> Do not use SV_PROC_FLAG early in exec_new_vmspace.

sys/riscv/include/machdep.h, sys/riscv/riscv/genassym.c, sys/riscv/riscv/locore.S, sys/riscv/riscv/machdep.c, sys/riscv/riscv/pmap.c
Unfortunately this results in a kernel panic if you do actually pass arguments:
`panic: kern_setenv: called before SI_SUB_KMEM`
(assuming you build a kernel with EARLY_PRINTF, if not you don't get any helpful output)
I may be missing some dependencies that also need to be cherry-picked.
=> Parse RISC-V bootargs

bin/cheritest/cheritest.c, bin/cheritest/cheritest.h, bin/cheritest/cheritest_syscall.c, lib/libsysdecode/signal.c, sys/kern/vfs_aio.c
This includes Wes's test addition since I used it to test this.  The SIGPROT thing I noticed since truss was reporting the signal in sigaction as "34" (though I still need to re-test truss)
=> Aio purecap bug

contrib/kyua/utils/datetime.cpp, contrib/kyua/utils/datetime_test.cpp
This probably needs to be done upstream as well?
Hopefully this lets my FreeBSD test suites run over the weekend under qemu.
=> Bring in devel/kyua patches to mitigate gettimeofday() jumps.

lib/libc/mips/gen/_ctx_start.S, lib/libc/mips/gen/makecontext.c, sys/kern/vfs_vnops.c
This fixes issues I ran into while running the FreeBSD test suite with a MIPS purecap world.  I might rework the second one to remove 'mc_pc' entirely from the purecap mcontext_t though, or perhaps add a followup commit that does it.
=> Test fixes

contrib/subrepo-cheri-c-tests/test_runtime.c, lib/libc/mips/gen/makecontext.c, sys/mips/include/cheri_machdep.h, sys/mips/include/ucontext.h, sys/mips/mips/freebsd64_machdep.c, sys/mips/mips/pm_machdep.c
Instead, purecap is expected to always manipulate mc_cheriframe.cf_pcc
directly.  freebsd64_setmcontext() now takes care of applying the
64-bit mc_pc as an offset to pcc and freebsd64_getmcontext() stores
the offset of pcc in mc_pc.
get/set_mcontext() in a CHERI kernel (hybrid and purecap) only operate
on pcc.
This did entail fixing some some code in the CHERI C tests.  Some of
it is still dubious (specifically how CJR/CJALR are handled for the
hybrid case), but I suspect hybrid just never uses those instructions.
=> Remove mc_pc entirely from the purecap mcontext_t.

tools/cheribsdbox/Makefile
These have come in handy for debugging minimal images in the past, but I'm not sure if it's worth doing in general.
=> Include procstat and cpuset in cheribsdbox

libexec/rtld-elf/riscv/rtld_start.S, sys/riscv/conf/FETT, sys/riscv/riscv/genassym.c
Also a tweak the FETT kernels to skip modules.
=> Riscv stack alignment fixes

sbin/init/init.c, sys/kern/kern_sig.c
While rare, encountering an unimplemented system call early in init is
catastrophic and difficult to debug.  As such, always log such events
for pid 1.
=> Log ENOSYS in init

sys/mips/conf/CHERI_MALTA64, sys/mips/conf/std.CHERI
Include MALTA64, override and add to it rather than just duplicating most of it. Also move options to std.CHERI that are common for any CHERI-MIPS kernel, even if some end up being no-ops for BERI kernels.
=> mips: Clean up CHERI_MALTA64 config

sys/riscv/riscv/locore.S
The call to init_capabilties trashes a0.
=> Preserve modulep in s2.

sys/riscv/cheri/cheri_machdep.c, sys/riscv/riscv/freebsd64_machdep.c, sys/riscv/riscv/machdep.c, sys/riscv/riscv/trap.c
Most of these exploit the polymorphic builtins, but call_trapsignal instead pushes the (void * __capability) into itself so the callers can just give it a uintcap_t. This would arguably make sense to be upstreamed with the uint64_t/register_t given every upstream caller has to cast its argument to void *, but upstream has fewer cases to deal with, and also doesn't have the round-tripping through uintcap_t.
=> riscv: Remove (and consolidate) several casts

sys/kern/sysv_shm.c
This assert was based on a mis-read of the code.
Fixes #716
This reverts commit 80f0c34c812ccbb5a5ea4f194e53d66aa05db294.
=> Revert "[UPSTREAM] shmat: rely on shmget to have rounded size."

sys/amd64/amd64/mp_machdep.c, sys/amd64/amd64/pmap.c, sys/amd64/include/param.h, sys/arm/include/param.h, sys/arm64/include/param.h, sys/i386/include/param.h, sys/mips/include/param.h, sys/powerpc/include/param.h, sys/riscv/include/param.h, sys/sys/param.h
These macros have substantially identical implementations on each
platfrom and we need to change round_page and trunc_page to use
__builtin_round_(up|down) for purecap to work.
This version standardizes on not adding an explicit cast as that
appears to be required on at least one powerpc and the builtins
are type-preserving.
=> Centralize implemention of some VM macros

sys/conf/kern.opts.mk, sys/conf/kern.pre.mk, sys/dev/mpr/mpr_user.c, sys/dev/mps/mps_user.c, sys/dev/xilinx/axidma.c, sys/riscv/include/param.h, sys/riscv/include/pte.h, sys/riscv/riscv/db_disasm.c, sys/riscv/riscv/intr_machdep.c, sys/riscv/riscv/pmap.c, sys/riscv/riscv/sbi.c, sys/riscv/riscv/trap.c
Recover some performance by cherry-picking the -O2 change (and its dependent commit, to minimise future pain/confusion) and fix PCI interrupts on RISC-V so we can use VirtIO over PCI rather than special-casing RISC-V to use always use MMIO on QEMU.
=> Upstream cherry-picks

bin/cheritest/cheritest.c, bin/cheritest/cheritest.h, bin/cheritest/cheritest_cheriabi.c
The kernel should reject untagged and out-of-bounds capabilities, but it turns
out we were only doing the latter. This is a regression test for
CTSRD-CHERI/cheribsd#709 (which is fixed by CTSRD-CHERI/cheribsd#710).
=> Add tests for passing invalid capabilities to munmap/mprotect/minherit

share/mk/bsd.compat.mk, share/mk/bsd.cpu.mk, share/mk/src.opts.mk
`cheribuild cheribsd-morello-hybrid` worked out of the box but `cheribuild cheribsd-morello-purecap` gave various errors which these commits fix*. This may well duplicate some of Brett's work, but figured I should post these in case things have been missed or done differently.
* My build hasn't actually finished yet but it's still going
=> Purecap world build fixes

share/mk/src.opts.mk
It's in __DEFAULT_NO_OPTIONS so Morello hasn't noticed yet but we should do things properly.
=> src.opts.mk: Mark LIBCHERI as broken on non-MIPS, not just RISC-V

sys/amd64/vmm/vmm.c, sys/cam/cam_periph.c, sys/compat/linuxkpi/common/src/linux_page.c, sys/dev/cxgbe/tom/t4_cpl_io.c, sys/dev/cxgbe/tom/t4_ddp.c, sys/dev/cxgbe/tom/t4_tom.h, sys/dev/nvme/nvme_ctrlr.c, sys/kern/kern_physio.c, sys/kern/sys_pipe.c, sys/kern/vfs_aio.c, sys/kern/vfs_bio.c, sys/kern/vfs_vnops.c, sys/modules/Makefile, sys/net/bpf.h, sys/net/bpf_zerocopy.c, sys/sys/buf.h, sys/sys/param.h, sys/ufs/ffs/ffs_rawread.c, sys/vm/vm_extern.h, sys/vm/vm_fault.c
Rather than passing a virtual address (usually cast from a pointer),
pass a pointer to vm_fault_quick_hold_pages as the starting address.
With CHERI this allows the bounds to be checked before mapping the
memory in question for use by the caller.
Doing this completely correctly requires making data types in struct buf
and struct bio be capabilities and I've skipped that large change for
now.
Note: this compiles, but does not boot.
=> Make vm_fault_quick_hold_pages take a pointer

usr.sbin/kldxref/Makefile, usr.sbin/kldxref/ef.c, usr.sbin/kldxref/ef.h, usr.sbin/kldxref/ef_obj.c, usr.sbin/kldxref/kldxref.c
Introduce compat-like functionality to kldxref so a purecap kldxref works on a hybrid kernel and in theory vice-versa (subject to relocation processing).
This fixes errors when using a purecap kldxref on a hybrid kernel of the form:
kldxref: unhandled relocation type 2
kldxref: error while reading /boot/kernel/ads111x.ko: Bad address
=> kldxref: Support differing userspace and kernel ABIs

bin/cheritest/cheritest.c, bin/cheritest/cheritest.h, bin/cheritest/cheritest_cheriabi_open.c, bin/cheritest/cheritest_fault.c, bin/cheritest/cheritest_sealcap.c, contrib/subrepo-cheri-c-tests/clang-hybrid/clang_hybrid_opaque.c, lib/libcheri/libcheri_type.c, sys/cheri/cheri.h, sys/cheri/cheri_sealcap.c, sys/cheri/cheric.h, sys/cheri/cherireg.h, sys/conf/files, sys/conf/files.mips, sys/mips/cheri/cheri.c, sys/mips/cheri/cheriabi_machdep.c, sys/mips/cheri/hybridabi_machdep.c, sys/mips/include/cheri.h, sys/mips/include/proc.h, sys/mips/include/sysarch.h, sys/mips/mips/freebsd64_machdep.c, sys/mips/mips/locore.S, sys/mips/mips/sys_machdep.c, sys/mips/mips/vm_machdep.c, sys/riscv/cheri/cheri_machdep.c
The concept of sealing is shared by all CHERI implementations, including Morello, yet the current sysarch(2)-based implementation for userspace to obtain a sealing root is MIPS-specific. Instead, replace it with a new sysctl that is shared by all CHERI implementations.
Unlike the old implementation this is now a kernel global rather than a field attached to the proc. However, in practice the previous implementation had the same value for the field for every single process. If future compartmentalisation work needs to further split up the root amongst proceses (such as the coprocess work) then the sysctl can be made a SYSCTL_PROC and various code added to implement that as needed, but for now that's not necessary.
=> Make userspace sealing root MI and implement on RISC-V

sys/cheri/cheri.h, sys/mips/cheri/cheri_signal.c, sys/mips/mips/vm_machdep.c
I noticed the MI cheri.h had this MIPS-specific prototype. However, rather than moving it to an MD header, it can just be deleted as both uses of it are immediately preceded by a bcopy of the entire PCB so this function is a complete and utter waste of time.
=> mips: Remove pointless cheri_signal_copy

sys/riscv/riscv/trap.c
Currently Clang will accept any non-capability pointer for %lp in hybrid, but I have a PR open that, among other things, adds proper type checking for %lp, so (uintcap_t *) becomes forbidden just like uintptr_t isn't a valid argument for %p.
=> riscv: Add cast for PRINT_REG_ARG in hybrid kernels not just purecap

share/mk/bsd.lib.mk
This should "fix" the "section header table goes past the end of the file: e_shoff = 0x..." errors that have started to plague our builds.
=> bsd.lib.mk: Work around build system raciness

sys/conf/files, sys/dev/smc/if_smc.c, sys/dev/smc/if_smc_acpi.c, sys/dev/smc/if_smcvar.h
This is needed by some of the Arm simulators as they implement a smc based
network interface, but use ACPI rather than FDT.
Sponsored by:	Innovate UK
=> Add an ACPI attachment for if_smc

sys/arm64/include/_align.h
This is part of the ABI and can't be changed for hybrid.  Only align
to 16 for purecap.
=> Restore the value of _ALIGNBYTES for hybrid.

sys/arm64/arm64/locore.S, sys/arm64/arm64/machdep.c
- Mark the sigcode as C64 and set c0 from csp instead of setting x0
for the purecap signal code.  While here, trim an instruction from
the sigcode for purecap.
- Mark sigcode as #object instead of #function as is done for the
RISC-V purecap kernel.  The purecap kernel will eventually need
this, but this also ensures the address of 'sigcode' is correct when
used as a pointer passed as a source to memcpy().
- Explicitly set the LSB in the sigcode capability for purecap since
it is C64.
=> Fixes for the purecap signal code.

sys/arm64/arm64/genassym.c, sys/arm64/arm64/machdep.c, sys/arm64/arm64/swtch.S, sys/arm64/arm64/vm_machdep.c, sys/arm64/include/pcb.h
Specifically the 'cid' and restricted capability registers.  These are
handled similarly to TLS registers except that there are no kernel
paths which set these values currently.  Userland is responsible for
managing intra-process compartments.  The registers are saved in the
PCB for context switches, copied on fork, and cleared during exec.
=> Handle additional user-accessible capabilities on Morello.

bin/cheribsdtest/cheribsdtest.c, bin/cheribsdtest/cheribsdtest.h, bin/cheribsdtest/cheribsdtest_cheriabi.c, sys/cheri/cheric.h, sys/kern/sysv_shm.c
- Fix issues around validating capabilities passed to shmdt (#728).
- Improve handling of shmaddr != NULL in shmat (needed for tests of the shmdt fixes).
- Disable loading or storing capabilities in shared memory mapping.
=> SysV shared memory cleanup

sys/cddl/contrib/opensolaris/uts/common/dtrace/dtrace.c, sys/compat/freebsd64/freebsd64_misc.c, sys/kern/kern_exec.c
Originally I was going to try to look for places where we could remove casts due to the builtins working with uintcap_t, but exec_copyout_strings() was the only place I found.
=> Reduce some diffs in exec_copyout_strings

sys/cam/cam_ccb.h, sys/cam/nvme/nvme_da.c, sys/dev/nvme/nvme.h, sys/dev/nvme/nvme_ctrlr.c
This pulls in the key fix from #765 with the intent to loop it back into morello-dev.
=> nvme: fix passthrough commands

sys/compat/freebsd32/freebsd32_misc.c, sys/compat/freebsd32/freebsd32_util.h, sys/compat/freebsd64/freebsd64_generic.c, sys/compat/freebsd64/freebsd64_misc.c, sys/compat/freebsd64/freebsd64_uipc.c, sys/compat/freebsd64/freebsd64_util.h, sys/kern/kern_jail.c, sys/kern/kern_sendfile.c, sys/kern/subr_uio.c, sys/kern/sys_generic.c, sys/kern/vfs_mount.c, sys/mips/mips/trap.c, sys/netinet/sctp_syscalls.c, sys/sys/_iovec.h, sys/sys/syscallsubr.h, sys/sys/uio.h, usr.sbin/jls/jls.c
/usr/tests/bin/pkill/pkill-j_test was causing a kernel panic while running the test suite on CHERI-MIPS
After some extensive debugging it turns out there are four bugs that break this test:
- Root cause: calling convention mismatch for function pointers. Clang doesn't warn even though the argument lists are incompatible. We should probably add this diagnostic. Fix is to change `updateiov(const struct uio *uiop, struct iovec *iovp)` -> `updateiov(const struct uio *uiop, struct iovec * __capability iovp)`. This calling convention mismatch results in updateiov() being passed a iov capability in $c3, but it actually reads whatever happens to be in $a1 (in my case 0xc4).
- This then ends up calling suword64() with this garbage value, which triggers a ADES error. MIPS trap() helpfully tries to …
=> Fix panic triggered by pkill j test

sys/riscv/include/pte.h, sys/riscv/riscv/pmap.c
This provides forwards-compatibility with implementations that check CD as defined by ISAv8.
=> riscv: Set PTE_CD whenever PTE_CW is set

Jenkinsfile
This may require additional cheribuild changes to extract
the compiler to the right directory. For now we only build a
subset of the architectures since this branch is only used
for morello changes and the full CI will run once we merge
back into dev.
The required jenkins-scripts change is https://github.com/CTSRD-CHERI/jenkins-scripts/commit/ec2fafe89f5456033920d144de41aac46f5e2bee
=> Add initial morello CI support

bin/cheribsdtest/cheribsdtest_bounds_stack.c, bin/cheribsdtest/cheribsdtest_fault.c, bin/cheribsdtest/cheribsdtest_printf.c, bin/cheribsdtest/cheribsdtest_registers.c, bin/cheribsdtest/cheribsdtest_syscall.c, bin/cheribsdtest/cheribsdtest_vm.c, lib/libc/stdio/printf-pos.c, lib/libc/stdio/printflocal.h, lib/libc/stdio/vfprintf.c, lib/libc/stdio/vfwprintf.c, lib/libmalloc_simple/malloc.c, sys/cheri/cheri_usercap.c, sys/cheri/cheric.h, sys/kern/subr_prf.c, sys/kern/sysv_shm.c, sys/mips/cheri/cheri_debug.c, sys/mips/cheri/cheri_exception.c, sys/mips/include/cheri.h, sys/mips/include/cheri_machdep.h, sys/riscv/cheri/cheri_debug.c, sys/riscv/riscv/trap.c
Clang now supports capabilities for hybrid varargs and knows that %lp takes a capability, so we can avoid this hack.
=> Hybrid capability varargs cleanups

sys/kern/imgact_elf.c, sys/kern/vfs_vnops.c, sys/sys/_iovec.h
Replace __USER_CAP in vn_rdwr with a capability derived from userspace_cap,
this properly generates a capability instead of deriving from a NULL DDC
in the case of a purecap binary on an hybrid kernel.
In the purecap kernel case, the ELF coredump generates the capability.
Add assertion in IOVEC_INIT_C to make sure that the capability given is valid.
=> Fix ELF core dump for hybrid and purecap kernels.

sys/amd64/amd64/pmap.c, sys/amd64/sgx/sgx.c, sys/arm/annapurna/alpine/alpine_pci_msix.c, sys/arm64/arm64/gicv3_its.c, sys/arm64/intel/stratix10-svc.c, sys/cheri/cheric.h, sys/dev/cxgbe/iw_cxgbe/resource.c, sys/dev/cxgbe/t4_main.c, sys/dev/cxgbe/tom/t4_ddp.c, sys/dev/xdma/xdma.c, sys/dev/xdma/xdma_iommu.c, sys/kern/subr_vmem.c, sys/sys/vmem.h, sys/vm/memguard.c, sys/vm/vm_init.c, sys/vm/vm_kern.c, sys/x86/iommu/intel_intrmap.c
When creating a new arena, the flag M_MEMORY_ARENA can be passed.
This will enable capability bounds enforcement, representability
size and alignent adjustments and checks.
=> purecap-kernel: Refactor vmem to enable capability handling per-arena.

sys/arm64/arm64/db_trace.c, sys/arm64/arm64/stack_machdep.c, sys/arm64/arm64/unwind.c, sys/arm64/include/csan.h, sys/arm64/include/stack.h, sys/cddl/dev/dtrace/aarch64/dtrace_isa.c, sys/cddl/dev/dtrace/amd64/dtrace_isa.c, sys/cddl/dev/dtrace/i386/dtrace_isa.c, sys/cddl/dev/dtrace/mips/dtrace_isa.c, sys/cddl/dev/dtrace/riscv/dtrace_isa.c, sys/ddb/db_ps.c, sys/kern/vfs_subr.c, sys/mips/mips/db_trace.c, sys/mips/mips/stack_machdep.c, sys/riscv/include/stack.h, sys/riscv/riscv/db_trace.c, sys/riscv/riscv/stack_machdep.c, sys/riscv/riscv/unwind.c, sys/sys/proc.h, sys/x86/x86/stack_machdep.c
Some of these are from the purecap branch.  kstack_contains() is new however, and I plan to upstream this entire series.  Alex ran into infinite recursion in the DDB stack unwinder for RISC-V that I think the last patch addresses.
I haven't yet tested this fully (still building)
=> Stack unwind fixes

sys/kern/imgact_elf.c, sys/kern/vfs_vnops.c, sys/sys/_iovec.h
This pulls in #766 as it is also needed for a hybrid kernel dumping a purecap binary. I've reordered, untangled and squashed fixup commits to clean up the history (as well as resolved conflicts with recent upstream changes and reduced the diff size slightly). Technically the IOVEC_INIT_C commit is not needed yet, but this ever so slightly chips away at the diff so might as well be pulled in.
=> Fix core dumps (taken from purecap kernel)

sys/vm/vm_extern.h, sys/vm/vm_fault.c, sys/vm/vm_glue.c
Add a vm_cap_allows_prot() to check if a capability has permissions
matching a given vm_prot_t.
Also use vm_cap_allows_prot in useracc and as a result drop the
requirement that the capability be global.  There is reason to belive
that most capabilities will be local in a co-process world.
Fixes #735
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ctsrd-cheri/cheribsd/742)
=> vm_fault_quick_hold_pages: check cap permissions

sys/cheri/cheric.h
This also removes `__always_inline` as it is not necessary.
=> Consistently use the inline keyword in cheric header.

lib/libc/stdio/printfcommon.h, sys/kern/subr_prf.c
This replaces earlier home-grown varieties that checked the value of
various fields instead (and didn't check the tag previously).
=> Use cheri_is_null_derived() in printf().

contrib/jemalloc/include/jemalloc/internal/atomic.h, contrib/jemalloc/include/jemalloc/internal/seq.h
The compiler warns about a potentially tag-stripping copy of
hooks_internal_t. Fix this by using a uintptr_t array instead of an array
of size_t.
A better solution would be language support for atomic memcpy (e.g.
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1478r5.html)
but until then using uintptr_t should be fine.
=> Fix potentially tag stripping copy in jemalloc

Makefile.inc1, bin/sh/Makefile, contrib/atf/atf-sh/libatf-sh.subr, contrib/netbsd-tests/lib/libc/db/t_db.sh, libexec/atf/Makefile, libexec/atf/atf-check/Makefile, libexec/atf/atf-sh/Makefile, libexec/atf/sh_static/Makefile, tests/sys/geom/class/eli/conf.sh, tests/sys/kern/coredump_phnum_test.sh, usr.bin/mkimg/Makefile, usr.bin/mkimg/tests/mkimg_test.sh, usr.sbin/etcupdate/Makefile
Speed up running the testsuite by skipping some slow tests and/or reducing the configuration matrix and using a statically linked non-CHERI shell.
The full testsuite can still be run with `kyua -v test_suites.FreeBSD.include_slow_tests=true test ...` 
This should significantly reduce the testing time.
See also https://github.com/CTSRD-CHERI/cheribuild/commit/ca2d209683c7711dc0f48a0f8dc8e8e7fabb1845
I submitted two atf-sh improvements that significantly improve test startup times as https://github.com/freebsd/atf/pull/6 and https://github.com/freebsd/atf/pull/5.
=> Faster testsuite runs

Jenkinsfile
Jenkins appears to use the last selected manual override for
automatically triggered builds. This appears to use the last manual
selection across *all* branches for multi-branch pipelines.
This is causing some pull requests on the dev branch to be built using
a manual selection of morello-purecap and that does not work yet.
Therefore, ignore the parameter value except for manually-triggered builds.
This appears to be https://issues.jenkins.io/browse/JENKINS-46941
=> Work around Jenkins build parameter behaviour

sys/kern/kern_environment.c, sys/net/vnet.h, sys/sys/pcpu.h
These are some small things I could recall.  Unfortunately, I haven't really tested these.  I don't think we currently can provide kernel environment variables to the kernel usefully, we haven't tested VIMAGE at all with CHERI hybrid much less purecap, and I don't know if anything in the default kernels uses DPCPU.  However, it did boot ok for me (RISC-V) and was able to run cheritests.
=> More bounds

contrib/libarchive/libarchive/archive_read_support_format_warc.c
Creating a pointer by adding an offset to 0x1 is undefined behaviour and
results in an invalid pointer when running on CHERI systems. Use a
standards-compliant cast via uintptr_t instead.
This was found due to a crash while running the libarchive test suite on a
CHERI-RISC-V system.
Submitted upstream as https://github.com/libarchive/libarchive/pull/1465
=> [UPSTREAM] libarchive: Fix UB in deconst() function

bin/cheribsdtest/Makefile.cheribsdtest, bin/cheribsdtest/cheribsdtest.c, bin/cheribsdtest/cheribsdtest.h, bin/cheribsdtest/cheribsdtest_bounds_varargs.c
(1) Check that calling va_arg() one too many times generates a bounds
violation.
(2) Check that printf() with an extra %p generates a bounds violation.
(3) Check that printf() with an extra %n generates a bounds violation.
Use an additional %c before the latter two in order to force allocation
of a varargs array.
=> Add four test cases relating to varargs:

share/mk/bsd.crunchgen.mk, share/mk/bsd.prog.mk
Commit 9e55b67bd8be942c886994749568dcd1f93d984c added it for libraries but
not for programs. This requires a rather ugly workaround in bsd.crunchgen.mk,
but I think that is simpler than trying to modify the makefile that crunchgen
generates.
=> [UPSTREAM] Also build programs with -Wl,--gdb-index

sys/vm/vm_mmap.c
Unlike upstream FreeBSD, we check max_prot in mmap(), so the implied RWX
max_prot for non-CHERI programs was causing mmap to fail with capsicum
errors for file descriptors that are read-only. This caused 13 test failures
happens in the usr.bin/tail tests. A better fix would be to clamp the
default max_prot value to whatever the capsicum rights permit, but that is
something that should be fixed upstream.
=> Set imply_prot_max to on by default

sys/cheri/cheri.h, sys/cheri/cheri_otype.c, sys/cheri/cheri_sealcap.c, sys/cheri/cheri_usercap.c, sys/ddb/db_main.c, sys/kern/imgact_elf.c, sys/kern/init_main.c, sys/kern/link_elf.c, sys/kern/link_elf_obj.c, sys/mips/beri/beri_machdep.c, sys/mips/cheri/cheri.c, sys/mips/cheri/cheri_stack_machdep.c, sys/mips/cheri/exception.S, sys/mips/include/cpuregs.h, sys/mips/malta/cheri_yamon.S, sys/mips/malta/malta_machdep.c, sys/mips/mips/busdma_machdep.c, sys/mips/mips/locore.S, sys/mips/mips/vm_machdep.c, sys/riscv/cheri/cheri_machdep.c, sys/riscv/riscv/machdep.c, sys/riscv/riscv/pmap.c, sys/vm/vm_mmap.c
Moved to {kernel,userspace}_*cap naming for capabilities.
I renamed the mips-specific ones by prefixing them with `mips_` as in `mips_xkseg_cap` instead of using the `kernel_*` prefix as I would not expect those to be used outside MD code.
=> Rename global root capabilities

sys/cheri/cheri.h, sys/sys/types.h
This is a subset of the changes in #832, but it is the bare minimum prereqs for merging other purecap-kernel related changes.
=> Purecap simple

sys/contrib/ipfilter/netinet/mlfk_ipl.c, sys/ddb/db_sym.c, sys/kern/kern_switch.c, sys/kern/kern_sysctl.c, sys/kern/subr_pcpu.c, sys/net/vnet.c, sys/net/vnet.h, sys/sys/pcpu.h
Handle VNET and dynamic per-CPU variables in the purecap kernel.
Note that this is focused on the "consumer" side for the use of the variables.  There are additional changes in the kernel linker to support these special variable types, but I'm waiting to include that as part of a kernel linker patch series.
=> Purecap dpcpu vnet

usr.sbin/pkg/config.c
This hack was used when bootstrapping pkg in order to install kyua.
Now that kyua is installed we don't need this.
=> pkg: Remove PKG_BOOTSTRAP_CONFIG_FILE

Jenkinsfile, Makefile.inc1, Makefile.libcompat, bin/cheribsdtest/Makefile, lib/csu/aarch64/Makefile, lib/csu/aarch64/crt1_c.c, lib/libc/aarch64/string/Makefile.inc, share/mk/bsd.compat.mk, share/mk/bsd.cpu.mk, share/mk/src.opts.mk, share/mk/sys.mk, stand/defs.mk, stand/efi/libefi/Makefile
This is enough to build a Morello hybrid userland. With it I can build userland with `TARGET_CPUTYPE=morello`.
Although there is further refinement of the build infrastructure in the `morello-dev` branch we could start building a Morello hybrid world in Jenkins to check for build failures from future changes.
=> Allow a hybrid Morello userland to be built

sys/arm64/arm64/exception_morello.S, sys/cam/scsi/scsi_cd.c, sys/compat/linux/linux_errno.inc, sys/dev/cxgbe/t4_ioctl.h, sys/dev/cxgbe/t4_main.c, sys/dev/efidev/efidev.c, sys/dev/hwpmc/hwpmc_arm64_md.c, sys/dev/mlx5/mlx5_core/mlx5_fwdump.c, sys/dev/mlx5/mlx5io.h, sys/net/bpf.c, sys/net/bpf.h, sys/ofed/include/rdma/ib_verbs.h, sys/sys/cdio.h, sys/sys/efiio.h, sys/sys/errno.h
This fixes all the modules enabled on arm64 but not mips64 or riscv, excluding the compat-related ones (i.e. cloudabi32/64 and the set of Linuxulator modules), and provides a tiny fix so the Linuxulator works again without panicking on load on INVARIANTS kernels (currently non-CHERI given Linuxulator needs changes to build for CHERI kernels).
It also bundles in a much-needed fix so stack unwinding works (or at least does the same thing as the baseline again; other than the deficiencies outlined in the commit, the implementation seems rather confused about when to use pre-unwind and post-unwind values in the printing). This ultimately should be ripped out and replaced with the RISC-V version with minor adaptation to be arm64-flavoured upstream.
=> Morello Modules

sys/arm64/arm64/machdep.c, sys/arm64/cheri/cheri_machdep.c, sys/arm64/include/cheric.h, sys/cheri/cheri_usercap.c, sys/mips/include/cheric.h, sys/riscv/include/cheric.h
These are mostly changes from Jess, but split into a small series of changes to permit cheri_build_user_code_cap() to return sentries on Morello.
=> Morello code cap

sys/arm64/arm64/vm_machdep.c
This reduces the diff to dev and should also fix ELR (PCC) for 32-bit
processes running under Morello.
=> Simplify cpu_set_upcall().

tools/build/Makefile
This is unncessary when cross-building from Linux/macOS. Additionally,
cp -p appears to be broken on macOS Big Sur
(https://openradar.appspot.com/8957219). I doubt this is causing the
build failures on Big Sur, but it's possible that things break when the
system binaries are executed from a non-rootfs directory.
=> Create symlinks to host tools

bin/cheribsdtest/cheribsdtest.c
Rather than treat XFAIL as a subset of FAIL, regard it as entirely separate, and do the same for XPASS and PASS. This is easier to reason about and more consistent with other tools (like llvm-lit).
Whilst here, add a comment and fix a style issue.
=> cheribsdtest: Improved test summary reporting

bin/cheribsdtest/cheribsdtest_cheriabi.c
41609e51beed2cc666574a22ee70550729493b7d fixed mmap tests by
pre-reserving space.  Do the same here.  Use mmap to reserve a a block of address space,
unmap it, and then make the shm mappings inside it.
Add a comment that the mmap case will need updating when we start
revoking unmapped reservations before reallocation.
=> cheribsdtest: make test_cheriabi_shmdt_invalid_ptr less fragile

lib/Makefile, lib/csu/aarch64c/Makefile, lib/csu/aarch64c/crt.h, lib/csu/aarch64c/crt1_c.c, lib/libc/aarch64/gen/Makefile.inc, lib/libc/aarch64/gen/_ctx_start.S, lib/libc/aarch64/gen/_set_tp.c, lib/libc/aarch64/gen/_setjmp.S, lib/libc/aarch64/gen/makecontext.c, lib/libc/aarch64/gen/setjmp.S, lib/libc/aarch64/gen/sigsetjmp.S, lib/libc/aarch64/static_tls.h, lib/libc/aarch64/string/Makefile.inc, lib/libc/aarch64/sys/cerror.S, lib/libc/aarch64/sys/vfork.S, lib/libc/gen/Symbol.map, lib/libc/gen/emutls.c, lib/libc/gen/tls.c, lib/libc/gen/tls_malloc.c, lib/libc/locale/Symbol.map, lib/libpmc/pmu-events/list.h, lib/libsimple_printf/aarch64/write.S, lib/libthr/arch/aarch64/include/pthread_md.h, secure/lib/libcrypto/Makefile.inc, sys/arm64/include/asm.h, usr.bin/gh-bc/Makefile
This is most of the userland changes from morello-dev (including the non-Morello-specific jevents fix) with the exception of compiler-rt (needs to loop back through LLVM), libunwind (needs to loop back and has some fixes in flight), and rtld.
=> Morello libc and other user land bits

lib/libsysdecode/mktables, sys/compat/freebsd64/freebsd64_mmap.c, sys/compat/linux/linux_mmap.c, sys/kern/imgact_aout.c, sys/kern/imgact_elf.c, sys/kern/kern_exec.c, sys/kern/sysv_shm.c, sys/kern/uipc_shm.c, sys/mips/cheri/cheri.c, sys/sys/imgact.h, sys/sys/mman.h, sys/sys/types.h, sys/vm/uma_core.c, sys/vm/vm_kern.c, sys/vm/vm_map.c, sys/vm/vm_map.h, sys/vm/vm_mmap.c, sys/vm/vm_param.h, sys/vm/vm_unix.c
Introduce purecap-kernel reservation changes.
=> vm_map reservations interface

sys/kern/sysv_sem.c
We were calling bzero() on the wrong semaphore structure: when we call
bzero, semtot had already been incremented so we were zeroing the next
structures. This explains why the first run of semaphore tests was always
failing, but follow-up ones succeed (since they got an already zeroed
structure).
=> Fix uninitialized memory being returned by semget()

sys/cheri/cheri.h, sys/cheri/cheri_cap_relocs.c, sys/compat/freebsd64/freebsd64_misc.c, sys/kern/link_elf.c, sys/kern/link_elf_obj.c, sys/kern/linker_if.m, sys/riscv/conf/std.CHERI-PURECAP, sys/riscv/riscv/elf_machdep.c
The first several changes are all generic purecap fixes that were only encountered when enabling module builds.  For some cases I disabled modules rather than trying to fix them.
The last few changes are the actual fixes for the kernel linker.
I know this will need updating to deal with vm_pointer_t fallout and some other changes, so this probably shouldn't be merged right away.  OTOH, since this is "close enough", we can probably just omit the bits about not building kernel modules from the first PR being merged to dev since I suspect this will all land in dev by the time we can actually turn CI on in dev.
=> Purecap kldload

sys/mips/include/pcpu.h, sys/riscv/include/pcpu.h, sys/riscv/riscv/machdep.c, sys/riscv/riscv/mp_machdep.c
- Bound pcpu pointer in MIPS macros
- Add purecap-only pcpu fields
- Adjust RISC-V padding and store pcpu pointer in kernel ctp
=> Purecap kernel pcpu headers

sys/amd64/amd64/pmap.c, sys/amd64/sgx/sgx.c, sys/arm/annapurna/alpine/alpine_pci_msix.c, sys/arm64/arm64/gicv3_its.c, sys/arm64/intel/stratix10-svc.c, sys/cddl/contrib/opensolaris/uts/common/dtrace/dtrace.c, sys/dev/cxgbe/iw_cxgbe/resource.c, sys/dev/cxgbe/t4_main.c, sys/dev/cxgbe/tom/t4_ddp.c, sys/dev/xdma/xdma.c, sys/dev/xdma/xdma_iommu.c, sys/i386/i386/pmap.c, sys/kern/subr_vmem.c, sys/powerpc/aim/mmu_radix.c, sys/powerpc/mpc85xx/pci_mpc85xx.c, sys/powerpc/powernv/opal_async.c, sys/powerpc/powernv/opal_pci.c, sys/powerpc/pseries/phyp_vscsi.c, sys/powerpc/pseries/plpar_iommu.c, sys/sys/vmem.h, sys/vm/memguard.c, sys/vm/vm_init.c, sys/vm/vm_kern.c, sys/x86/iommu/intel_intrmap.c
- Add arena flags parameter to vmem_create() to control capability-specific operations
- Add assertions to check capabilities handled by vmem
- Enforce representable boundaries for vmem capability arenas
=> Purecap kernel vmem changes

lib/libprocstat/Makefile
This is more correct, even if we currently disable CDDL for CHERI so it doesn't matter.
Whilst here, drop the MIPS check; it's not needed and should be done via src.opts.mk, especially now we use the right variable.
=> libprocstat: Guard ZFS code with MK_ZFS not MK_CDDL

sys/vm/vm_map.c
When reservations are enabled and the previous entry is extended, we
need to delete first the reserved entry that has been clipped to size
for the new mapping, otherwise this will result in overlapping entries.
=> Fix bug in vm_map_insert with reservations

sys/net/if.c, sys/net/if.h
These are a couple of additional cleanups in sys/net/if.c that I noticed while working on upstreaming some of the changes from the earlier series.  The groupreq one is mostly about being consistent with what is now the dominant style for compat shims (especially for freebsd32 compat shims in this file upstream).
=> Small if ioctl cleanups

sys/kern/sysv_shm.c
Some `attach_addr` slipped through the renaming to `attach_va`.
=> Fix sysv_shm purecap mismerge

include/stdlib.h, lib/libc/stdlib/Makefile.inc, lib/libc/stdlib/jemalloc/Makefile.inc, lib/libc/stdlib/jemalloc/Symbol.map, lib/libc/stdlib/malloc_revoke.3, lib/libc/stdlib/malloc_revoke.c
Add a stub version of `malloc_revoke()` for non-revoking mallocs. Also add a skeleton manpage.
The current `void` args and return match dlmalloc's implementation which is convenient for now.  We might want to expand the signature to return success (0/-1) and set errorno as appropriate.
=> Stub malloc_revoke

bin/cheribsdtest/Makefile.cheribsdtest, bin/cheribsdtest/cheribsdtest_lazy_bind.c, lib/Makefile, lib/libcheribsdtest_dynamic/Makefile, lib/libcheribsdtest_dynamic/cheribsdtest_dynamic.h, lib/libcheribsdtest_dynamic/cheribsdtest_dynamic_identity_cap.c, libexec/rtld-elf/riscv/rtld_start.S, share/mk/src.libnames.mk
Whilst here, add suitable macroisation to support pure-capability lazy binding in future too, though this will need tweaking once JAL becomes CJAL.
Note that this is a change of behaviour riscv64sf; previously we would allocate 64 bytes for FRPs unconditionally, but now we don't. A simplified version of that optimisation could be upstreamed if we cared enough.
=> rtld-elf: Fix hybrid RISC-V lazy binding to preserve capability arguments

sys/riscv/riscv/exception.S, sys/riscv/riscv/locore.S, sys/riscv/riscv/swtch.S
In ISAv9, JALR is mode-dependent, so CJALR (and aliases like CJR) are only available in capability mode, with JALR.CAP being the new mnemonic for the old ISAv8 CJALR (but the same encoding). To aid this transition, Clang defines a new (temporary) __riscv_xcheri_mode_dependent_jumps macro so we can build with both old and new toolchains.
=> riscv: Support building with CHERI ISAv9 mnemonics for jumps

usr.bin/tip/tip/tip.h, usr.bin/tip/tip/value.c
Currently IREMOTE assumes that every value is (initially) a pointer to a long. This is true for NUMBERs, but false for STRINGs, which are instead pointers to pointers, though on ILP32 and LP64 systems these happen to have the same representation, but this is still a strict aliasing violation, and of course breaks on systems where the representations are not the same, such as CHERI. We do not currently have any BOOLs (short, curiously) or CHARs used with IREMOTE, though the code should not be relying on that.
=> tip: Fix pointer-vs-integer confusion

Jenkinsfile
The former have never been built in CI, but are useful for architectures using EFI as this way there is a NODEBUG kernel in the image. The latter used to be built by default but are no longer after the cleanup of kernel config code in cheribuild.
Whilst here, switch to the shorter form for cheribsd-mfs-root-kernel cheribuild options that is now supported (cheribsd-mfs-root-kernel falls back on cheribsd's configuration for kernel config options if not specified).
=> Jenkinsfile: Build benchmarking normal and MFS_ROOT kernels

sys/crypto/des/des.h, sys/crypto/des/des_enc.c, sys/crypto/des/des_locl.h, sys/crypto/des/des_setkey.c
The types are as follows:
typedef unsigned char des_cblock[8];
typedef struct des_ks_struct {
union {
des_cblock cblock;
DES_LONG deslong[2];
} ks;
int weak_key;
} des_key_schedule[16];
Currently des_encrypt1, des_encrypt2 and des_set_key_unchecked access
the first des_key_schedule's deslong and use that as an array of 32
elements. This is dubious and bad practice even if it has the same
underlying representation, but each des_key_schedule also has a weak_key
field, so we end up reading and writing some of those rather than the
final deslong's. To make matters worse, i386 has an assembly
implementation of des_enc (but not des_setkey) that also assumes there
is no weak_key field.
Firstly, remove the unused (or at least not intentionally) weak_key
field so the i386 assembly matches the …
=> sys/crypto/des: Fix out-of-bounds accesses to deslong

tools/tools/atsectl/atsectl.c
The compiler error states that the comparison in line 296 is trivially true, which is caused by assigning
a value to a char type variable and then comparing it against "-1".
=> Workaround for compiler error in atsectl.c line 296

sys/cheri/cheric.h
This needs to be here until the ctestsubset instruction argument order is stable.
=> Use a soft implementation of cheri_is_subset.

sys/dev/md/embedfs.S, sys/riscv/riscv/pmap.c
This boots provided you patch cheribuild's minimal rc to bring up lo0 before vtnet0. I assume a normal purecap kernel is similarly broken if you bring vtnet0 up first. The current order in cheribuild for minimal images is a bit silly/unusual, but in this case it's useful as it finds a bug.
=> purecap-kernel: MFS_ROOT fixes

sys/sys/cdefs.h, sys/sys/param.h, usr.bin/truss/main.c, usr.bin/truss/setup.c, usr.bin/truss/syscall.h, usr.bin/truss/syscalls.c, usr.bin/truss/truss.h
Currently running a pure-capability `truss -a -e` does not decode any
argument values for freebsd64_* syscalls (open/readlink/etc.).
This cherry-picks my upstreamed fixes for compat32 decoding and
makes some minor adjustments to allow using a hybrid truss to trace
purecap programs.
=> truss: decode compat32/compat64 arguments

bin/cheribsdtest/cheribsdtest_bounds_stack.c
We already provided tests for stack allocations done statically, and via ```alloca()```, but not via the VLA syntax. The benefits of these tests are only very incremental, but I think a good idea to have them giving on going GNU toolchain work.
=> Add tests for C variable-length arrays on the stack.

sys/sys/syscallsubr.h, sys/vm/vm_mmap.c
Rather than smuggling the kernel-only MAP_RESERVATION_CREATE flag to
kern_mmap() via mr_flags, add a new mr_kern_flags and pass it there.
This allows us to remove MAP_RESERVATION_CREATE from the list of flags
allowed from userspace and reject it centrally.
There's a larger issue of kernel/userspace flags being mixed, but that's
a large, API-breaking change that should start upstream.
=> mmap: reject MAP_RESERVATION_CREATE from userspace

lib/libpam/modules/modules.inc, tools/cheribsdbox/Makefile
I am about to add those to the minimal disk images anyway since various
programs need them (e.g. CTest), so we might as well link them dynamically
to avoid duplicating the code.
This also drops the local diff to the libpam Makefile since we link pam
dynamically.
=> cheribsdbox: Use a few more shared libraries

lib/libc/riscv/sys/Makefile.inc, lib/libc/riscv/sys/__vdso_gettc.c, sys/riscv/include/vdso.h, sys/riscv/riscv/elf_machdep.c, sys/riscv/riscv/timer.c
PR:	256905
Reviewed by:	arichardson, mhorne
MFC after:	1 week
Differential Revision:	https://reviews.freebsd.org/D30963
(cherry picked from commit 348c41d1815dc2e872a1deba1f4bf760caaa1094)
=> riscv: Implement non-stub __vdso_gettc and __vdso_gettimekeep

libexec/rtld-elf/rtld.c
Currently the mprotect() call fails because of missing VMMAP permissions.
While we could add VMMAP to AT_BASE, I don't changing the page permissions
to read-only for one page in RTLD adds any security/debugging benefits
when we have CHERI capabilities.
=> rtld: Don't mprotect() the rtld RELO segment for purecap

bin/cheribsdtest/Makefile.cheribsdtest, bin/cheribsdtest/arm64/cheribsdtest_md.h, bin/cheribsdtest/cheribsdtest.h, bin/cheribsdtest/cheribsdtest_local_global.c
This adds a simple test that demonstrates storing a local capability and
they faulting when attempting to store it through a capability without
CHERI_PERM_STORE_LOCAL_CAP.
=> cheribsdtest: test storing local capabilities

sys/arm64/arm64/identcpu.c, sys/arm64/include/cpu.h
As documented in "Arm Morello System Development Platform (SDP) Preliminary Technical Reference Manual".
=> arm64: Add MIDR_EL1 for Morello SoC

bin/cheribsdtest/cheribsdtest_strfcap.c
The executive permission bit is not accounted for.
=> Fix strfcap test for Morello.

libexec/Makefile, share/mk/bsd.subdir.mk
Fix manpage related issues in sh_static and rtld.  In the former case, just don't install one.  In the latter, don't perform installs in parallel in libexec so rtld.1 is installed before other rtld's start to link to it.
Remove an outdated local diff from libc's CFLAGS
=> assorted build cleanups

bin/cheribsdtest/Makefile.cheribsdtest, bin/cheribsdtest/cheribsdtest_ipc.c, sys/arm64/arm64/uio_machdep.c, sys/kern/subr_uio.c, sys/kern/uipc_shm.c, sys/libkern/bcopy_c.c, sys/mips/mips/uio_machdep.c, sys/riscv/riscv/uio_machdep.c, sys/sys/uio.h
Currently we only have a cap version of uiomove itself, and preserve_tags is unconditional for UIO_SYSSPACE. This fixes that, plus adds a uiomove_fromphys_cap and makes uiomove_fromphys not tag preserving, as is needed in almost all cases (namely, other than SHM copying) and fixes the issue seen in #1045 where we tried to do a tag-preserving copy from a tag-bearing page (and capability, in the case of the purecap kernel) to a non-tag-bearing page (and capability, in the case of the purecap kernel, I assume) and thus faulted if the userspace buffer ever happened to contain capabilities (which, when stack-allocated, tends to be the case for large chunks of uninitialised memory).
=> Improve uiomove tag preservation, including fix for #1045

lib/libc/sys/Symbol.map
Unlike the other syscalls these two symbols were missing from the
version script. I noticed this while looking into purecap compiler-rt
runtime libraries.
=> Export _mmap and __sys_mmap from libc.so

sys/arm64/include/cpu.h, sys/kern/imgact_elf.c, sys/kern/kern_exec.c, sys/kern/kern_linker.c, sys/riscv/include/cpu.h, sys/riscv/riscv/cpufunc_asm.S, sys/riscv/riscv/trap.c, usr.bin/Makefile, usr.bin/ktrdump/Makefile, usr.bin/ktrdump64/Makefile
These are various small fixes I encountered while working on the merge of the coexcve branch.  The sys_kldsym() fix fixes the purecap ktrdump not being able to resolve symbols, though since I was using a hybrid kernel I ended up needing ktrdump64 instead to have the 'struct ktr_entry' type match the ABI.  ktrdump64 seemed simpler and less invasive given the nature of this tool than trying to teach ktrdump about different kernel ABIs.
=> Coproc fixes

Makefile.libcompat
These libraries have been removed upstream.
=> Don't filter amu and gdb from INTERNALLIBS for /usr/lib64c.

contrib/libpng/pngpriv.h, contrib/libpng/pngrutil.c, lib/googletest/Makefile.inc, lib/libc/stdlib/merge.c, lib/libefivar/Makefile, share/mk/bsd.compiler.mk, share/mk/bsd.sys.mk, stand/i386/loader/Makefile, sys/conf/kern.mk, sys/contrib/dev/acpica/include/actypes.h, sys/x86/xen/pv.c, tests/sys/fs/fusefs/Makefile, tools/build/cross-build/include/common/sys/cdefs.h
Mostly cherry-picks from upstream. Only real change is the last commit that allows us to still use the old compiler which is > 13.0.0 but doesn't support -Wno-unused-but-set-variable yet.
=> Changes needed to build with newer LLVM

sys/kern/imgact_elf.c, sys/kern/kern_exec.c, sys/riscv/riscv/cpufunc_asm.S
The last commit is what I think is the fix for the length violation panics I've seen when leaving a system up overnight.  Probably what happens is that at some point the address space that cron lives in "fills up" with abandoned entries and every future execve falls back to non-opportunistic.  I might try a temporary hack to force the opportunistic case to fail always and verify it breaks quickly on the stock coexecve kernel and works with the fix.
The purecap changes are because cheribuild has recently changed to compile purecap kernels by default.  One is a cherry-pick, the second is a local fix.
=> Coexecve args

sys/ddb/db_sym.c, sys/net/vnet.c
Also includes an NFC (I hope) change that I noticed that was an outlier in using the wrong variable (vnet_data_mem is otherwise only used for managing the actual allocation and initialising in vnet_alloc, never for accessing the data therein).
=> Fix loading vnet-using kernel modules

sys/compat/cloudabi/cloudabi_file.c, sys/compat/freebsd64/freebsd64_vfs.c, sys/compat/linux/linux_file.c, sys/kern/vfs_syscalls.c, sys/sys/syscallsubr.h
The first commit avoids having to expose at2cnpflags() from sys/kern/vfs_syscalls.c to freebsd64.  I will try to merge the first commit upstream.
=> Handle AT_RESOLVE_BENEATH in freebsd64

Jenkinsfile
Morello is now supported in the main qemu-cheri branch.
=> Jenkinsfile: Use normal qemu-cheri branch for Morello

libexec/rtld-elf/aarch64/rtld_machdep.h
This had not yet been updated since Morello is still using emulated
TLS.  However, the recent changes to static TLS support in libc from
upstream started using the TCB size from rtld in libc instead of a
local definition.
=> morello: Update TLS TCB size in rtld for purecap.

lib/libc/gen/errlst.c, lib/libc/nls/C.msg, lib/libc/sys/intro.2
The actual errno value was removed from errno.h almost a year ago in
commit da841970cf37590751542906ccfcaf28d2237fde.
=> libc: Remove references to ENOMETHOD.

sys/riscv/riscv/pmap.c
pmap_promote_l2() failed to handle implementations which set the
accessed and dirty flags.  In particular, when comparing the attributes
of a run of 512 PTEs, we must handle the possibility that the hardware
will set PTE_D on a clean, writable mapping.
Following the example of amd64 and arm64, change riscv's
pmap_promote_l2() to downgrade clean, writable mappings to read-only, so
that updates are synchronized by the pmap lock.
Fixes:		f6893f09d
Reported by:	Nathaniel Filardo <nwf20@cl.cam.ac.uk>
Tested by:	Nathaniel Filardo <nwf20@cl.cam.ac.uk>
Reviewed by:	jrtc27, alc, Nathaniel Filardo
MFC after:	1 week
Sponsored by:	The FreeBSD Foundation
Differential Revision:	https://reviews.freebsd.org/D30644
(cherry picked from commit c05748e028b84c216d0161e70418f8cb09e074e4)
=> riscv: Handle hardware-managed dirty bit updates in pmap_promote_l2()

sys/arm64/arm64/locore.S
.bss is not guaranteed to be a multiple of 2 pointers in size.  If the
.bss's size was not divisible by 2 pointers (32 bytes for the purecap
kernel), then the start of the symbol table used by ddb was
overwritten with zeroes causing DDB to think it had no valid symbols
for the kernel.
While we could store a single pointer in the loop perhaps, this isn't
really a critical path and we still store a plain integer at a time on
RISC-V as well in the purecap kernel.
=> morello: Zero the bss during startup 8 bytes at a time.

sys/kern/init_sysent.c, sys/tools/makesyscalls.lua
Pull in a few changes from the recently upstreamed generation of freebsd32 from sys/kern/syscalls.master. These should hopefully reduce the risk of conflicts and mis-merges when we loop those changes back.
=> makesyscall tidying

bin/cheribsdtest/cheribsdtest.c, bin/cheribsdtest/cheribsdtest.h, bin/cheribsdtest/cheribsdtest_util.c, bin/cheribsdtest/cheribsdtest_vm.c, sys/cheri/cheric.h
Here are a couple of tweaks to `cheribsdtest` I have locally that seem generally applicable:
1. Add an optional check for `si_addr` in tests that trigger a signal.
2. Move the check for `TESTRESULT_FAILURE` before other checks. This solves a problem with reporting the result when a test with `CT_FLAG_SIGNAL` calls `cheribsdtest_failure_*` before triggering the signal. In that case the check for signal would overwrite the error message provided by the test with `Unexpected signal 0 recieved` which is much less useful.
=> Cheribsdtest tweaks

sys/compat/freebsd64/freebsd64_uipc.c, sys/kern/subr_epoch.c, sys/net/bpf.c, sys/net/bpfdesc.h, sys/net/if_llatbl.h, sys/net/if_var.h, sys/net/if_vlan.c, sys/net/pfil.c, sys/net/route/fib_algo.c, sys/net/route/nhgrp_var.h, sys/net/route/nhop_var.h, sys/net/route/route_ctl.c, sys/net/route/route_var.h, sys/netinet/in_pcb.h, sys/sys/_mutex.h, sys/sys/_rwlock.h, sys/sys/_sx.h, sys/sys/epoch.h
The last commit is just a warning fix for CheriBSD specific code I snuck in.
The second commit is perhaps debatable though technically more accurate perhaps?
If we had a working "__subobject_type_used_for_c_inheritance" we could tag "lock_object" with that and remove most of the locking annotations.
=> Kernel subobject bounds

tools/build/cross-build/include/linux/sys/wait.h
As of glibc 2.34, our unistd.h wrapper's inclusion of stdlib.h exposes
fragility in glibc's sys/wait.h and corresponding part of stdlib.h,
leading to "error: use of undeclared identifier 'WNOHANG'" and similar
errors when bootstrapping bmake.
Work around this by wrapping sys/wait.h to force stdlib.h's inclusion
first before it's implicitly included during the problematic window in
sys/wait.h.
MFC after:	1 week
(cherry picked from commit 9e5b0d9eac5b240dc0ee280870291fd11d499046)
=> cross-build: Fix bmake bootstrap with glibc 2.34

sys/kern/uipc_syscalls.c
Place sys_recvfrom below kern_recvfrom and use kern_recvfrom in
orecvfrom rather than calling sys_recvfrom with a modifed uap.
=> recvfrom: reduce diffs to upstream

sys/sys/types.h
I was thinking of pulling together a patch to upstream I noticed this line didn't really match the rest of the file.
=> syscallarg_t: remove layer of typedef indirection

lib/libc/locale/collate.c, lib/libc/locale/ldpart.c, lib/libc/locale/rune.c, lib/libc/locale/setlocale.c, lib/libc/locale/xlocale.c, lib/libc/locale/xlocale_private.h
The only diffs now are \_ThreadRuneLocale's emutls variable in Symbol.map and lib/libc/locale/gb18030.c's diff to fix an overread of the source by including an extra MIN(..., strlen) (which should be revisited and either dropped or upstreamed).
=> libc: Diff-reduce locale code

lib/libc/regex/regexec.c
The states macro is the type for engine.c to use, with states1 being a
local macro for regexec to use to determine whether it can use the small
matcher or not (by comparing nstates and 8*sizeof(states1)). However,
macro bodies are expanded in the context of their use, and so when
regexec uses states1 it uses the current value of states, which is left
over as char * from the large version (or, really, the multi-byte one,
but that reuses large's states). For all supported architectures in
FreeBSD, the two have the same size, and so this confusion is harmless.
However, for architectures like CHERI where that is not the case (or
Windows's LLP64 as discovered by LLVM and fixed in 2010 in 2e071faed8e2)
and sizeof(char *) is bigger than sizeof(long) regexec will erroneously
try to use the small …
=> libc: Fix regexec when sizeof(char *) > sizeof(long)

sys/kern/vfs_export.c, sys/net/pfvar.h, sys/netinet/in_fib_algo.c, sys/netinet6/in6_fib_algo.c, sys/netpfil/ipfw/ip_fw_table_algo.c
A downcast idiom is used to retrieve the container from the node
pointer, so we cannot set bounds when passing these to rnh_addaddr /
rn_addroute. This repeats 3f0122c5f4b2 for all the other instances I
could find.
=> Add __subobject_use_container_bounds to all struct radix_node[2] embeds

sys/dev/re/if_re.c
IDR0-IDR5 can be read byte-by-byte but must be written to as 4-byte
words. The current code to do this is rather clunky and ends up reading
past the end of the union's eaddr member due to MAC addresses only being
6 bytes. In practice this ends up being fine because the align_dummy
member will pad the union to a multiple of 4 bytes, but this is dodgy,
and on CHERI with subobject bounds enforcement enabled, as is done in
CheriBSD's pure-capability kernel, will trap.
Instead, make the buffer in use the right size, just use an array of
uint32_t's rather than a char buffer that's then cast to uint32_t * to
simplify it in the process, and zero-initialise it first to avoid
reading uninitialised data in the trailing bytes.
Found by:	CHERI
Reviewed by:	jhb
Differential Revision: …
=> re: Avoid subobject overread when setting IDRn

sys/ufs/ufs/dir.h
Otherwise if this struct is near the end of the buffer then accessing
d_name in a way that isn't proved safe will trap (on CHERI) or clear the
tag (on Morello) since UFS_MAXNAMLEN + 1 will exceed the remaining
length. This mirrors what is done for struct dirent.
=> ufs: Annotate struct direct's d_name array as a VLA for subobject bounds

sys/kern/kern_umtx.c
Using char * as the user address type only works in hybrid kernels; we
must use uint64_t instead. Whilst here, hoist the capability derivation
out of the loop and add appropriate bounds.
Without this, buildworld on a purecap kernel (which currently only has a
toolchain built as hybrid) eventually gets stuck during the everything
phase, with all jobs being lld processes performing relocatable links
which each have all their threads waiting in UMTX_OP_WAIT_UINT_PRIVATE
operations. It's unclear why this only affected relocatable links, or
even if that's always the case.
=> umtx: Fix UMTX_OP_NWAKE_PRIVATE for freebsd64 processes on a purecap kernel

sys/net/bpf.c
Commit ab4fc2f7ba47 missed one instance of fcode that should have been
changd to the new old_fcode. This results in immediate use-after-free,
and eventually panics in bpfd_free with a double free detected when it
tries to free its own program buffer.
=> bpf: Fix wrong free in bpf_setf

sys/kern/sysv_sem.c, sys/libkern/bcopy.c, sys/libkern/bcopy_c.c, sys/sys/sem.h, sys/sys/systm.h
This reimplements CHERI-specific bcopy*() functions as macros around mem* in the kernel to be consistent with upstream FreeBSD which has done the same for bcopy() and bzero().
=> bcopy*() cleanup

sys/compat/freebsd64/freebsd64_process.c
The structure pointed to by addr is the same size on freebsd64 and
purecap.
=> Support PT_COREDUMP in freebsd64_ptrace().

libexec/rtld-elf/aarch64/rtld_machdep.h, libexec/rtld-elf/map_object.c, libexec/rtld-elf/mips/rtld_machdep.h, libexec/rtld-elf/riscv/rtld_machdep.h, sys/arm64/include/elf.h
ELF_IS_CHERI post-dates CheriABI rtld, hence why it wasn't used for mips, but for some reason I never thought to use it in rtld when cleaning the code up and adding CHERI-RISC-V...
=> Clean up rtld ABI checking and enable for Morello

sys/kern/vfs_aio.c
For lio_listio(), the request type to check for LIO_VECTORED must be
read from the aiocb rather than using the passed-in type.
=> aiocb64_copyin: Handle opcodes for lio_listio().

share/mk/bsd.opts.mk
This is a local diff and PIE is later enabled by default upstream on
all non-32-bit arches.
=> Remove PIE from DEFAULT_YES_OPTIONS.

.mergify_pause_paths, sys/compat/freebsd64/freebsd64_misc.c, sys/kern/kern_procctl.c, sys/sys/procctl.h, sys/sys/syscallsubr.h
- Drop freebsd32 bits from sys/kern as freebsd32_procctl() is
self-contained over in freebsd32_misc.c.
- Retire struct procctl_reaper_kill_c and instead add __kerncap to the
real structure.
- Unwind user_procctl and instead make freebsd64_procctl more like
freebsd32_procctl.  In particular, upstream changes are going to
make supporting freebsd64 in this function more complicated and
hacky.
=> procctl: Rework ABI compatiblity.

sys/dev/hwpmc/hwpmc_amd.c, sys/dev/hwpmc/hwpmc_arm64.c, sys/dev/hwpmc/hwpmc_armv7.c, sys/dev/hwpmc/hwpmc_uncore.c
If a counter more than overflows just as we read it on switch out then,
if using sampling mode, we will negate this small value to give a huge
reload count, and if we later switch back in that context we will
validate that value against pm_reloadcount and panic an INVARIANTS
kernel with:
panic: [pmc,1470] pmcval outside of expected range cpu=2 ri=16 pmcval=fffff292 pm_reloadcount=10000
or similar. Presumably in a non-INVARIANTS kernel we will instead just
use the provided value as the reload count, which would lead to the
overflow not happing for a very long time (e.g. 78 minutes for a 48-bit
counter incrementing at an averate rate of 1GHz).
Instead, clamp the reload count to 0 (which corresponds precisely to the
value we would compute if it had just overflowed and no more), which
will …
=> hwpmc: Fix amd/arm64/armv7/uncore sampling overflow race

sys/compat/freebsd64/freebsd64_misc.c, sys/kern/kern_exec.c
- Use imgp->strings instead of re-deriving the user stack capability.
- Don't assume sv_szsigcode is non-NULL if sv_sigcodebase is set.
- Use exec_stackgap() instead of invoking sv_stackgap directly.
- Use strlen() on argv and environment strings.  (I didn't do this
when originally splitting out freebsd64_copyout_strings to more
closely match upstream, but I now think it is more important to
match our exec_copyout_strings().)
- Set imgp->auxv (even though it is currently only used in MD code
for SV_CHERI).
=> freebsd64_copyout_strings: Synch with exec_copyout_strings.

contrib/llvm-project/compiler-rt/lib/asan/asan_mapping.h, contrib/llvm-project/compiler-rt/lib/builtins/atomic.c, contrib/llvm-project/compiler-rt/lib/builtins/enable_execute_stack.c, contrib/llvm-project/compiler-rt/lib/builtins/gcc_personality_v0.c, contrib/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp, contrib/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_linux_libcdep.cpp, contrib/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_syscall_generic.inc, contrib/llvm-project/libcxx/include/string
We do not use this in CheriBSD anyway and instead use the
contrib/subrepo-cheri-xxx which pull from CHERI llvm.
=> Drop local diffs in contrib/llvm-project.

lib/libc/stdlib/qsort.c, sys/libkern/qsort.c
This fixes qsort for CHERI kernels in order to fix fib4_lookup tag faults that have been plaguing my Morello purecap kernels if they receive packets between the time re0 comes up and the time re0's routes are set up. At least I hope so...
Also includes a cleanup to libc's qsort to be less unnecessarily verbose yet opaque (and fix a whitespace issue introduced in the original CHERIfication commit).
=> Fix fib4_lookup tag fault panics

lib/libprocstat/core.c, sys/compat/freebsd32/freebsd32_util.h, sys/compat/freebsd64/freebsd64_util.h, sys/sys/exec.h
Presumably we probably would not want to use ps_strings in the future
if we needed to resurrect this but would instead add new ELF auxiliary
vector entries.
=> Retire no-longer-used extensions to ps_strings for sandboxes.

Makefile.inc1
For some reason building on Morello causes the variables to not be set
and fail the build. I don't know why, but I don't really care, all the
_TOOLCHAIN_VARS_SHOULD_BE_SET code is annoying and fragile.
=> Makefile.inc1: Don't set _TOOLCHAIN_VARS_SHOULD_BE_SET for test-includes

lib/libmd/Makefile
Versions of CHERI/Morello LLVM that include the April upstream merge but
not the September upstream merge have a snapshot in the middle of the 13
cycle that includes the SHA512 intrinsics but does not (bogusly) lump
them under __ARM_FEATURE_SHA3. Add +crypto to -march to support these
older compilers.
=> libmd: Add +crypto to -march for sha512c_arm64.c

sys/conf/Makefile.arm64
Based on 651987560ba1's detection for -Wunused-but-set-variable.
=> Makefile.arm64: Support CHERI LLVM versions merged to upstream mid 13 cycle

sys/dev/usb/usb_generic.c, sys/kern/kern_exec.c, sys/kern/kern_umtx.c, sys/kern/vfs_aio.c, sys/sys/systm.h
In places that work with user pointers and not specifically capabilities,
use fueptr and suptr instead of fuecap and sucap.  fuecap and sucap are
now only declared in CHERI kernels (hybrid or purecap).
=> Add fueptr and suptr.

sys/dev/mii/dp83822phy.c, sys/dev/mii/dp83867phy.c
Doesn't show in CI since vtnet isn't a real MAC with a PHY. This shows up on any hardware with a real MAC+PHY combo regardless of the PHY since every probe gets its turn, including both broken ones (and since more than one is broken, at least one won't match and thus try and walk off the end).
=> Add missing MII_PHY_ENDs to avoid buffer overreads on probe

usr.sbin/kldxref/ef_aarch64.c
The current implementation of R_AARCH64_ABS64 doesn't do anything, which
is dodgy, but seems to not matter, so do the same for the equivalent
R_MORELLO_CAPINIT to silence the unhandled relocation warning.
=> kldxref: Stub out R_MORELLO_CAPINIT on morello like R_AARCH64_ABS64

sys/cddl/dev/dtrace/mips/dtrace_isa.c, sys/cddl/dev/dtrace/mips/dtrace_subr.c, sys/conf/kern.post.mk, sys/ddb/db_print.c, sys/vm/vm_glue.c
Removes remaining MIPS-specific local diffs outside of DTS files and sys/dev/altera.
=> Kernel mips cleanup

usr.bin/login/login.conf
FETT is long over and we don't need to support it.
This reverts commit 5a54021a9ddf6030edd4cd7def602c17b1a33902.
=> Revert "Add /fett/bin to the default path."

sys/dev/usb/net/usb_ethernet.h
struct ether_cf_task extends struct usb_proc_msg and the driver needs
to downcast.
=> ue: Add subobject annotation for struct ether_cfg_task subclass.

sys/arm64/arm64/exec_machdep.c
The removed code duplicates the code starting at line 483.
=> Remove duplicate code that clears `tpidr[ro]`

usr.bin/dtc/fdt.cc
It seems that recent libcstdc++ pulls in fewer headers implicitly, so this
is needed to get std::numeric_limits<>.
=> usr.bin/dtc: Add another missing <limits> include

libexec/getty/gettytab, stand/lua/drawer.lua
Note that this only updates the default ASCII brand.  Graphic consoles
still use the existing FreeBSD branding.
=> loader: Brand as CheriBSD rather than FreeBSD by default.

sys/sys/param.h, usr.sbin/pkg/CheriBSD.conf, usr.sbin/pkg/Makefile, usr.sbin/pkg/config.c
pkg for CheriABI can detect aarch64c and riscv64c ABIs [0] and the ports-mgmt/pkg port includes this change [1] now. Since pkg should be ready to bootstrap itself, it's a good moment to add a repository configuration for CheriBSD packages. They're not available on pkg.CheriBSD.org yet but we should be able to host them in the following days. Fingerprints should be added the the repository by @gvnn3 as they must be generated on the host the packages are built, in a secure way.
[0] https://github.com/CTSRD-CHERI/pkg/commit/386a364fc65aa3d2285318b9dbdaa6da0a6d78fc
[1] https://github.com/CTSRD-CHERI/cheribsd-ports/commit/4c64703ac643132e5ff052a30b2203ed13ac176c
=> Add a pkg repository configuration for CheriBSD.

lib/csu/common/crtbrand.S, lib/csu/common/notes.h, sys/sys/elf_common.h
**This PR depends on `__CheriBSD_version` added by #1298 and should not be merged to `dev` before #1298 is merged.**
We would like to be able to distinguish CheriBSD binaries from FreeBSD binaries. Since the 3rd-party software doesn't recognise CheriBSD as a vendor, we must leave the NT_FREEBSD_ABI_TAG note intact as it would break their build systems.
Instead, let's introduce a new note NT_CHERIBSD_ABI_TAG that indicates a binary's vendor is CheriBSD and includes a CheriBSD ABI version in its description.
I considered two changes when working on this:
* Add a second NT_FREEBSD_ABI_TAG ELF note with CheriBSD as a vendor. I'm not sure if an ELF binary can have multiple notes with the same tag. Even if so, it makes sense not to reuse the same tag since a program might use a wrong one and …
=> Add a separate ELF note to indicate a binary is built for CheriBSD.

sys/arm64/arm64/unwind.c, sys/riscv/riscv/unwind.c
~This patch, suggested by @bsdjhb, fixes a kernel panic caused by a misaligned `fp` being accessed.~
Edit: This patch uses the correct operator to compare capability top bounds.
=> Use correct operator when comparing with `cheri_gettop` result

share/keys/pkg/trusted/Makefile, share/keys/pkg/trusted/pkg.cheribsd.org.2022032901
The signing key corresponding to the fingerprint was generated on a host separate from build hosts and pkg.CheriBSD.org. Packages will be signed with pkg-repo(8) and a signing command executed via SSH on the host where the signing key was generated.
The generating and the signing operations are implemented in [1].
[1] https://github.com/CTSRD-CHERI/poudriere-infrastructure/blob/master/key.sh
Example signing process:
```
Creating repository in CheriBSD:20220314:aarch64c: 100%
Packing files for repository: 100%
```
Example bootstrap and update commands' output:
```
The package management tool is not yet installed on your system.
Do you want to fetch and install it now? [y/N]: y
Bootstrapping pkg from pkg+http://pkg.CheriBSD.org/CheriBSD:20220314:aarch64c.new, please wait...
Verifying …
```
=> Add a fingerprint for the pkg.CheriBSD.org repo.

usr.sbin/pkg/Makefile
The pkg64 Makefile attempts to disable manpages but that is overridden
by the pkg Makefile. This fixes the WITH_MAN build for me.
=> Fix pkg64 manpage build error

.github/workflows/clang-format.yml, sys/libkern/strlen.c
This checks all the commits in the current PR using
my fork of WolleTD/clang-format-checker.
Ideally, it would also add inline comments but that
might be quite a lot of work.
=> Add a clang-format GitHub action

bin/csh/dot.cshrc, bin/sh/dot.profile, share/skel/dot.cshrc, share/skel/dot.profile, usr.bin/login/login.conf, usr.sbin/Makefile, usr.sbin/pkg/Makefile, usr.sbin/pkg64c/Makefile, usr.sbin/pkg64c/pkg.sh
Related issue: https://github.com/CTSRD-CHERI/cheribsd/issues/1346.
In order to make users aware of consequences of using experimental CheriABI packages:
* Rename the pkg program to pkg64c;
* Introduce the pkg utility that explains what package managers are available.
This PR also adds /usr/local64/{bin,sbin} to PATH.
=> pkg utility explaining available package managers pkg64c and pkg64

tools/build/test-includes/Makefile
FreeBSD's shell permits [^bar] to match characters not in [bar] like
common regular expressions. This is non-portable and '!' should be
used in place of '^' for portability.
Reported by:	Nathaniel Wesley Filardo
Issue:		https://github.com/CTSRD-CHERI/cheribsd/issues/1321
Reviewed by:	imp
Differential Revision:	https://reviews.freebsd.org/D34597
=> test-includes: improve portability

usr.bin/man/man.1, usr.bin/man/man.conf.5, usr.bin/man/man.sh, usr.bin/man/manpath.1
At the moment, man(1) can find man pages in `/usr/local64/man` because it traverses paths in `PATH` to look for `man/` directories. However:
* It still cannot find configuration files in `/usr/local64/etc/man.d/` installed with packages;
* `/usr/local64/share/man` and `/usr/local64/man` should be considered by default and not just because `/usr/local64/*` is in `PATH`.
=> Add hybrid ABI paths to man(1).

usr.bin/procstat/procstat_basic.c
‘FreeBSD ELF64C’ is one character longer than the previous longest ABI string supported by procstat(1), leading to a poorly aligned following column. Perhaps more ideally the field would be autosized, but for now just shift everything one character over.
=> Widen procstat 'EMUL' field to make room for 'FreeBSD ELF64C’.

release/Makefile
We don't currently build with separate debug files, and Jenkins does not
even enable debug info currently, but both of these will soon change for
the upcoming release and we want to provide debug distribution sets
without having to set up, and rely on, remote fetching for CheriBSD,
especially given we automatically install all listed distribution sets
with no way to opt out.
Also includes them in dvd for -DNO_ROOT builds, which (unintentionally)
already happens for root builds due to a missing -E in the grep call;
this can be traced back to 8834318685bc which turned grep -v '-dbg' into
grep -vE '(base|lib32)-dbg' for disc1/memstick but inadvertently changed it
to the nonsense grep -v '(base|lib32)-dbg' for dvd, forgetting the -E.
=> release: Include debug distribution sets in disc1/memstick images

Jenkinsfile
I believe I originally added the `--cheribsd/no-debug-info`
flag to reduce disk usage in Jenkins. However, this means that
the release images we are shipping do not include debug symbols,
which means userspace crashes are much more difficult to debug
than they should be.
=> Always include debug info in Jenkins

sys/kern/link_elf.c
MODINFO_ADDR is an address not a pointer. link_elf_obj already handled
this, presumably for CHERI-MIPS, but link_elf did not, so copy the fix.
=> link_elf: Fix link_elf_link_preload for purecap kernels

sys/vm/vm_map.c
Don't check that reservations are non-overlapping for hybrid processes.
As reported in #1371, this invariant isn't maintained in processes
who's maps don't set the MAP_RESERVATIONS flag.
This is a workaround to allow a system with the DIAGNOSIC option enabled
to run hybrid processes.
=> vm_map: relax assertions for hybrid processes

sbin/fsck_ffs/pass5.c, sys/ufs/ffs/ffs_alloc.c, sys/ufs/ffs/fs.h
Allow (in theory) 64-bit background fsck to work by altering struct ffs_cmd to fit a capability on CHERI systems and adding a thunk for freebsd64 calls. Compiles and the system boots, but complete untested.
=> vfs.ffs compat freebsd64

sbin/pfctl/pfctl.c
This results a nightly crash due to a bounds violation in pfctl(8) when the
daily event runs. Requires further validation before considering a merge.
Fixes https://github.com/CTSRD-CHERI/cheribsd/issues/1385
Also fixes https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264128
=> Don't dereference anchoropt, even if non-NULL, if it is an empty string.

contrib/jemalloc/include/jemalloc/jemalloc_FreeBSD.h, lib/libc/stdlib/jemalloc/Makefile.inc
This reverts 854818ce20b7d which forced MALLOC_PRODUCTION and partially
reverts b1f8ea91fd5bb which allowed enabling MALLOC_DEBUG.  Correct the
MALLOC_DEBUG option to define JEMALLOC_DEBUG since the define has
changed upstream.
=> jemalloc: make MALLOC_PRODUCTION obey WITH(OUT)

libexec/rtld-elf/aarch64/reloc.c
This uses the generic error message for relocations not supported for
a given ABI in exchange for simpler code that doesn't use gotos, etc.
=> Simplify #ifdef's in aarch64 rtld.

bin/cheribsdtest/Makefile.cheribsdtest, bin/cheribsdtest/cheribsdtest.h, bin/cheribsdtest/cheribsdtest_bounds_stack.c, bin/cheribsdtest/cheribsdtest_bounds_subobject.c
Sundry subobject bounds tests for various structure configurations, exemptions, the queue(3) macros, etc.
=> Subobject bounds tests for pure-capability CHERI C/C++.

Makefile.inc1
For the time being, the llvm-morello and llvm-cheri toolchains are
installed under /usr/local64 on native CHERI systems.
Testing: Works on a Morello box
=> Look for cross toolchains under /usr/local64

usr.bin/top/display.c
Only the second commit seems to be required (the strncpy change isn't sufficient, but adding space for `\0` terminators is), but using common library functions that do exactly what the code they replace does seems like a generally good idea.
=> Fix overflows in top

sys/arm64/cheri/cheri_machdep.c, sys/riscv/cheri/cheri_machdep.c
A bug resulted in updating and then discarding a temporary rather than
setting bounds on the final.
=> Actually bound kernel_root_sealcap

tools/build/stdint.h
Also use _PTRADDR_T_DECLARED guards around ptraddr_t decleration.
=> crossbuild: Don't declare vaddr_t

sys/vm/swap_pager.c
CSeal on at least RISC-V is not able to seal a sentry and raises an
exception instead.
=> swap_pager: Use CSealEntry to seal restored sentries.

sys/arm64/cheri/cheri_machdep.c, sys/arm64/include/cheri.h, sys/dev/psci/smccc_arm64.S, sys/riscv/cheri/cheri_machdep.c
The non-purecap TF-A firmware on Morello systems uses SP_EL0 which
depends on DDC_EL0 being a reset capability.
=> Morello: Set DDC_EL0 to kernel_root_cap during PSCI calls.

contrib/less/filename.c
Apply upstream GNU less PR#271 commit 5ed5582e:
https://github.com/gwsw/less/pull/271
When supplied with a file of random data >256 bytes, read()
would return a full buffer of data[256] to bin_file().
That function loops through the buffer, but calls is_utf8_well_formed()
with the full length of the buffer.  When looping on the last byte of the
buffer, is_uft8_well_formed() reads past the end.
This commit fixes bin_file() to only inspect the remaining bytes in the
buffer.
=> less(1): Prevent bin_file() -> is_utf8_well_formed() buffer overrun

lib/libefivar/Makefile, share/mk/bsd.compiler.mk, share/mk/bsd.sys.mk, sys/conf/kern.mk
Both CHERI LLVM and Morello LLVM are upgraded to LLVM 13 and no longer
need this workaround.
This reverts commit 651987560ba1c2df5aae91a19fb6287c3cb95b6b.
=> Revert "Allow building with CHERI-LLVM prior to the Sep 2021 merge"

share/mk/bsd.sys.mk, sys/conf/Makefile.arm64
…round.
Just assume it isn't broken for versions != 13 rather than doing the
runtime check.
=> Remove workarounds for older versions of Morello LLVM.

secure/lib/libcrypto/Makefile
This will silently merge with a duplicate line otherwise, keeping the
diff around, which is harmeless but confusing.
=> libcryto: Sync with upstreamed -fno-strict-aliasing workaround

sys/arm64/arm64/pmap.c
Fixes https://github.com/CTSRD-CHERI/cheribsd/issues/1454. In https://github.com/CTSRD-CHERI/cheribsd/commit/84304ad7376e9e5de0535cc1fe5031c976474b89 the flag `PMAP_CAPLOADGEN_WIRE` was removed from mips and riscv but was not removed from arm64. This commit removes `PMAP_CAPLOADGEN_WIRE` following the same pattern from that commit.
=> Remove PMAP_CAPLOADGEN_WIRE from arm64

sys/kern/imgact_elf.c
For CheriABI, if the binary is missing the ELF note providing an OS
release, assume it's the current release rather than defaulting to 0.
There is some argument for a static 1400058 (the version at the time of
the var-args and TLS ABI flagday), but simply assuming syncronization
with the kernel seems mostly like to work going forward and the loss of
ELF notes is still unsolved.
=> cheriabi: set osrel to __FreeBSD_version if missing

usr.bin/find/function.c
The find command would fail with "no space for arguments" when the
size of the environment conspired to leave a multiple of 16 bytes for
strings. A magic 16 was used to represent some sort of average minimum
size of an argument plus pointer pair, but since our pointers are
16-bytes the next line that removed space for the pointers could result
in no space being available.  Change the code to use 8 + sizeof(char *)
with a minimum value of 16 to avoid perturbing 32-bit systems.
Diagnosed by:	@jrtc27
=> find: fix -exec on CheriABI

lib/libnv/msgio.c
This change allows a CheriABI nm to work with long argument lists, but it's a workaround since hybrid or native binaries are also broken and we can't change their control message size limits retroactively.
=> CheriABI: libnv fd_send/fd_recv limit fix

crypto/openssh/sshd_config
CheriABI now supports dynamic binaries and having PAM authentication
working out of the box is friendlier to new installs on Morello
systems.
This reverts commit 98c1f564e3f06c66d264bcaa4808557278bc09f0.
=> Revert "Disable PAM, it doesn't work with static sshd."

sys/sys/_stdint.h
kuint64cap_t is an integer type that can hold a pointer.  On CHERI
systems it's an __uintcap_t in the kernel and an uintptr_t elsewere.
On 32-bit systems it's a uint64_t so 32- and 64-bit systems have
data structures the same size (module i386's weak aligment
requirements).
=> kuint64cap t

sys/vm/vm_fault.c
This complements some MD origins of SEGV_STORETAG.  I'm not sure it's necessary, but I had it floating around in `caprevoke`.
=> Teach vm_fault_trap about VM_PROT_WRITE_CAP

sys/arm64/arm64/elf_machdep.c, sys/arm64/cheri/cheri_machdep.c, sys/arm64/conf/GENERIC-MORELLO-PURECAP-SYZKALLER, sys/arm64/conf/GENERIC-MORELLO-PURECAP-SYZKALLER-NODEBUG, sys/kern/kern_kcov.c, sys/kern/subr_devmap.c, sys/sys/cdefs.h
The KCOV option is broken. This was likely due to a lost changeset for kern_kcov from the MIPS purecap kernel.
=> Fix kernel coverage support.

share/mk/bsd.compat.mk, share/mk/bsd.cpu.mk
Don't declare a ptr## entry if we're in purecap.  It might be we want a
ptr128c instead of purecap, but leave it alone for now.
Add long## and time## for the other common ABI aspects.
Fixes #639
=> MACHINE_ABI: add long and time, fix ptr

sys/compat/freebsd64/freebsd64_uipc.c
When a freebsd64 caller uses all or most allowed space for control
messages (MCLBYTES) then the message may no longer fit when the messages
are padded for capability alignment. Historically (with freebsd32) we've
just shrugged and said there is no ABI guarantee. Unfortunatly, libnv
breaks this assumption so capsicumized programs link nm fail on CHERI
systems.
Fix this by using external storage in mbufs if the expansion requires
it.
=> freebsd64_sendmsg: allow more control messages

bin/cheribsdtest/cheribsdtest.c
The use of 'all' was depreceted almost 8 years ago in a1d9b6c0a01d9.
=> cheribsdtest: remove 'all' as a synonym for -a

sys/compat/freebsd64/freebsd64_uipc.c
This was fixed in freebsd32_copyin_control in 1b1428dcc82b5.  Apply the
same changes to the freebsd64 code.
=> Fix freebsd64_copyin_control TOCTOU bug

sys/sys/param.h
While the currently used ABI is compatible with 20220511, we expect major changes within the kernel and packages in the next release. These changes include DRM, Panfrost GPU and upstream FreeBSD ports merges.
In order to avoid any possible breakages of existing 22.05 and 22.05p1 environments, we decided to bump the ABI counter. We also decided to bump it now rather than wait for the merges so that we can build, test and publish packages in advance to the next release.
Note that
* http://pkg.cheribsd.org/CheriBSD:20220828:aarch64/
* http://pkg.cheribsd.org/CheriBSD:20220828:aarch64c/
are currently symlinks to
* http://pkg.cheribsd.org/CheriBSD:20220511:aarch64/
* …
=> Bump __CheriBSD_version

bin/cheribsdtest/Makefile.cheribsdtest, bin/cheribsdtest/cheribsdtest.c, bin/cheribsdtest/cheribsdtest.h, bin/cheribsdtest/cheribsdtest_colocation.c, sys/kern/imgact_elf.c, sys/kern/kern_exec.c
Add infrastructure to (co)exec cheribsdtest and call a test-specific function in the child. Use this to add a couple tests to verify that colocation happens as expected.
=> Colocation tests

sys/sys/ktrace.h
This applies cfa4ccfbd169 to the new version of the header structure
added in 640b6110a7e8.
=> ktrace: Convert ktr_tid to a long in the new header structure.

sys/arm64/arm64/exec_machdep.c
Add `rcsp` and `ddc` to the `ucontext_t`. Also save (restore) them in get_mcontext (set_mcontext).
=> Save (restore) rcsp in get_mcontext (set_mcontext)

sys/compat/freebsd32/freebsd32_misc.c, sys/compat/freebsd64/freebsd64_uipc.c
The API says that CMSG_SPACE should be used for msg_controllen, but in practice the native ABI allows you to only use CMSG_LEN for the final (typically only) control message, and real-world software does this, including Wayland. For freebsd32, this is in practice mostly harmless, since control messages are generally used to carry file descriptors, which are already 4 bytes in size and thus no padding is needed, but they can carry other quantities that may not result in an aligned length. However, freebsd64 uses 8 byte alignment which does break the file descriptor use case, and thus Wayland.
=> freebsd*: Make sendmsg match native ABI for unpadded final control message

contrib/elftoolchain/readelf/readelf.c
I was trying to figure out why pkg was not happy after rebuilding from dev and noticed that NT_CHERIBSD_ABI_TAG was not being pretty-printed:
```
Notes at offset 0x000002d8 with length 0x00000064:
Owner         Data size       Description
FreeBSD       0x00000004      NT_FREEBSD_ABI_TAG
ABI tag: 1400064
CheriBSD      0x00000004      <unknown: 1>
description data: 9c 8b 34 01
FreeBSD       0x00000004      NT_FREEBSD_FEATURE_CTL
Features:
FreeBSD       0x00000004      NT_FREEBSD_NOINIT_TAG
description data: 00 00 00 00
```
After:
```
Notes at offset 0x000002d8 with length 0x00000064:
Owner         Data size       Description
FreeBSD       0x00000004      NT_FREEBSD_ABI_TAG
ABI tag: 1400064
CheriBSD      0x00000004      NT_CHERIBSD_ABI_TAG
ABI tag: 20220828
FreeBSD       0x00000004 …
```
=> readelf: Dump NT_CHERIBSD_ABI_TAG

libexec/rc/rc.subr
This change will ensure that exactly one service of a given name tries to run eliminating the risk of a random service being run if multiple packages are installed that provide the same service as discussed in #1486.
The current change warns when ever `find_local_scripts_new()` is run so the warnings appear a couple times during boot. A more intrusive patch could accumulate them and defer printing them at the end of `/etc/rc`.
I'm not sure if upstream would take this patch as is so I'm keeping it to CheriBSD for now.
=> rc: disallow services with duplicate names

libexec/rc/rc.conf
Services installed via `pkg64` (stable hybrid ABI packages) are installed into `/usr/local64/etc/rc.d`.
By including it in the `local_startup` list, services in this folder will be automatically detected by FreeBSD's `init` system.
This shouldn't cause issues if we're not running purecap and the `/usr/local64/etc/rc.d` folder doesn't exist. [^1]
Example: After running `pkg64 install mDNSResponder` and adding `/usr/local64/etc/rc.d` to `local_startup`, services appear when running `service -l`, and can be startup/enabled using `service mdnsresponderposix start`.
[^1]: I've tested this by adding a `/this/folder/does/not/exist` to the var; everything still seems to work, and there doesn't seem to be any warnings/errors anywhere
=> etc/defaults/rc.conf: add pkg64 service support

Jenkinsfile, lib/libc/stdlib/jemalloc/Makefile.inc
Instead of setting MALLOC_DEBUG (which will result in a -Werror compile failure), override cheribuild's default of -DWITH_MALLOC_PRODUCTION by passing -DWITHOUT_MALLOC_PRODUCTION. We could also set the build type to Debug, but for the sake of vaguely reasonable testsuite run times on QEMU, we should keep it as release+debug info+malloc assertions.
=> Drop an old local diff and update testsuite Jenkins job

bin/cheribsdtest/cheribsdtest_bounds_stack.c
An upcoming Morello compiler change will remove tighted bounds on capabilities created by casting a pointer to a capability.  This following RISC-V.  Since CheriBSD no longer supports MIPS, just remove the check that would be dead code.
https://github.com/CTSRD-CHERI/llvm-project/issues/647 https://git.morello-project.org/morello/llvm-project/-/merge_requests/208
=> hybrid: don't check upper bounds on stack caps

lib/libc/sys/ptrace.2, sys/kern/sys_process.c, sys/sys/ptrace.h
This reads capabilities as unpacked 17 byte values.  The tag is treated as the 129th bit of a capability and is stored as the LSB of the 17th byte (for little endian, big endian stores the tag in the first byte).
Multiple capabilities can be fetched at a time in which case the buffer length must be a multiple of 17.  The target address for the read must also be capability aligned.
=> ptrace: Add a PIOD_READ_CHERI_CAP operation to PT_IO.

sys/kern/sys_process.c
The first sub-byte mask of tags fetched should stay at LSB and subsequent masks appended at higher bits rather than the other way around.
I had fixed this before, but merged a stale version of the memory tags in coredumps PR that didn't yet have this fix.
=> Accumulate tags correctly.

sys/arm64/arm64/exec_machdep.c
The original patch did not quite resolve the signal-related bugs. We revert the changes and will use an alternative way to solve the problem (See #1498).
=> Revert "Save csp/rcsp in ucontext depending on ELR"

ObsoleteFiles.inc, tools/build/mk/OptionalObsoleteFiles.inc
delete-old still wants to delete dtrace and ZFS libraries installed for lib64 and this does not try to address that.
=> delete-old: Don't delete files installed by installworld on Morello.

lib/libc/gen/tls_malloc.c, lib/libmalloc_simple/heap.c, lib/libmalloc_simple/malloc.c
Assorted improvements to the light weight malloc implementations used in libc (for TLS) and rtld on CheriABI. Most of these were inspired by feedback to #1497.
=> Mini malloc cleanups

share/mk/bsd.compat.mk, share/mk/bsd.cpu.mk, sys/conf/kern.mk
This ensures we don't accidentally get purecap when using a toolchain
that defaults to it (which currently happens for hybrid kernels when
using llvm-base's cc). As part of this, to simplify the various
conditions, we drop support for toolchains that require the use of +c64,
since the patch to infer the encoding mode from the ABI was merged 8
days after the merge of CHERI LLVM 13, our current baseline.
=> Explicitly use -mabi=aapcs for hybrid and vanilla AArch64 code

sys/vm/vm_map.c
I noticed this bug because its knock-on effects cause significant performance issues with some graphics applications. In more detail, some GEM buffers of the panfrost GPU driver and their page frames are not freed even if the client process exits because the associated vm_objects are not freed.
This bug can also cause issues with non-graphics applications. Here is a small demo program that mmaps and munmaps one million pages: https://github.com/CTSRD-CHERI/pffm2/blob/cheribsd/misc/unmap_bug_investigation/torture_test.c
After each execution ~4GB of main memory remain used up without this fix, even after the process exits. With vmstat -z one can see how the "used" objects count of the VM OBJECT zone increases with each execution.
The demo application also runs ~1.11x slower without this …
=> Fix vm_object leak in the implementation of munmap

sys/sys/_stdint.h, sys/sys/_types.h
These are integer(ish) types capable of storing a pointer and at least 64-bits in size.  They are suitable for use in objects that previously used uint64_t to store 32/64-bit agnostic pointers in a fixed size where the object is not used as a kernel interface.  (If the object is used as a kernel interface then kuint64cap_t should be used.)
These are useful for ZFS where some types have uint64_t members that hold pointers and are not used as part of the userspace/kernel interface.
=> Add (u)int64ptr_t types

sys/fs/nullfs/null_vnops.c, sys/tools/vnode_if.awk
Issue: https://github.com/CTSRD-CHERI/cheribsd/issues/1539
=> Don't use subobject bounds for vop_F_args.a_gen

sys/dev/sound/usb/uaudio.c, sys/dev/usb/misc/ugold.c, sys/dev/usb/serial/usb_serial.h, sys/dev/usb/usb_bus.h, sys/dev/usb/usb_device.h, sys/dev/usb/usb_transfer.h
This fixes a nested panic seen when testing GUI support, likely
dependent on having USB HID devices connected, as usbd_clear_stall_proc
was hitting a bounds fault.
=> usb: Annotate struct usb_proc_msg inheritance for purecap kernel

sys/arm64/arm64/unwind.c, sys/riscv/riscv/unwind.c
Without this I can't boot a purecap kernel to the login prompt in qemu.
=> Check alignment of fp in unwind_frame

sys/dev/drm/freebsd/drm_os_freebsd.c, sys/libkern/bcopy_c.c
The first commit fixes KWin's ability to start Xwayland (though required X processes started by startplasma-wayland still crash and block plasma actually starting; one looks to be an unaligned allocation, and the other has the hallmarks of an adjust-pointers-by-realloc-diff bug, crashing on strlen of a capability to a string that points to valid data but has a cleared tag and is way out of bounds).
The second commit is why hybrid kernels are more broken than purecap kernels when it comes to DRM ioctls.
=> Misc DRM fixes

sys/dev/drm/panfrost/panfrost_gem.c
If allocating pages fails, we will have a pages array but entries will be NULL, resulting in a NULL dereference. Ignore such entries just like other partial states.
The panfrost_gem_mapping_put call already does a put on the object (our get at the start of the function was in order to give the mapping a reference) so we shouldn't do a second one manually, as that will result in a use-after-free in panfrost_gem_create_object_with_handle when it does the final panfrost_gem_object_put intending to take the refcount to 0, since drm_gem_handle_create_tail's balanced put will already have done that and freed the object.
=> panfrost_gem: Fix panics on page allocation failure

libexec/rtld-elf/aarch64/rtld_start.S, share/man/man7/compartmentalization.7
* The layout of trusted stack frames is changed to make it easier for setjmp/longjmp to unwind the stack.
* Adds a comment to the man page about C++ compatibility.
Closes #1556.
=> c18n: Additional changes and fixes

sys/conf/files.arm64, sys/conf/files.riscv, sys/libkern/memset_c.c, sys/sys/systm.h
LLVM 14's MemcpyOpt pass now optimizes the following code to call memset_c:
```
dp = (__cheri_fromcap struct dirent *)uiop->uio_iov->iov_base;
NFSBZERO(dp, DIRBLKSIZ);
dp->d_type = DT_UNKNOWN;
```
=> libkern: provide memset_c in hybrid kernels

usr.sbin/bsdinstall/scripts/services
This isn't quite a service but given dumpdev is here this seems like a
sensible place to put the option.
Fixes https://github.com/CTSRD-CHERI/cheribsd/issues/1565
Also includes a bunch of fixes I just committed upstream to this file.
=> bsdinstall: Add off-by-default debugger_on_panic option to services menu

sys/dev/drm/panfrost/panfrost_drv.c
Now that drm_ioctl correctly converts from the negative Linux convention to the positive FreeBSD convention, return values from panfrost's own ioctls also get negated by drm_ioctl and thus need to be negative in the first place. However, most of them were not, and so userspace sees errno as a negative value. In particular, panfrost_bo_wait in Mesa asserts that errno is either ETIMEDOUT or EBUSY, but was seeing -EBUSY and thus aborting.
=> panfrost: Fix ioctl return values to use Linux convention

sys/dev/drm/freebsd/drm_os_freebsd.c
This fixes an assertion failure in Mesa's panfrost_bo_wait in Xwayland when running Firefox, as the ERESTARTSYS was leaking up into errno and not being one of the two expected values.
=> drm_os_freebsd: Map Linux ERESTARTSYS to FreeBSD ERESTART for ioctls

sys/dev/drm/panfrost/panfrost_device.h, sys/dev/drm/panfrost/panfrost_drv.c, sys/dev/drm/panfrost/panfrost_gem.c, sys/dev/drm/panfrost/panfrost_job.c, sys/dev/drm/panfrost/panfrost_job.h, sys/dev/drm/panfrost/panfrost_mmu.c, sys/dev/drm/panfrost/panfrost_mmu.h
This fixes the race when file descriptor is closed abruptly, but jobs are still running.
=> panfrost: Fix MMU/fd race

sys/dev/drm/core/drm_atomic_helper.c, sys/dev/drm/core/drm_fb_helper.c
When a kernel panic occurs while DRM graphics are enabled a second panic occurs before the message can be printed or a backtrace produced.  This prevents the users from seeing the panic message.
This change works around the panic in two parts:
- dont wait for vblank during panic.
- avoid call to drm_modeset_drop_locks as well due to unknown bug
This should really be done in a FreeBSD-specific layer.
Fixes #1564
=> Work around nested panic in DRM

sys/dev/drm/panfrost/panfrost_gem.c
Fix warning that struct_mutex is not locked on drm_gem_object_put
=> panfrost: struct_mutex warning fix

contrib/bmake/unit-tests/Makefile, contrib/bmake/unit-tests/export.mk, contrib/bmake/unit-tests/make-exported.mk
Some Linux variants have deprecated egrep breaking the bmake tests that rely on it.  Manually apply the change from NetBSD as FreeBSD doesn't yet have a bmake import the contains the fix:
https://github.com/NetBSD/src/commit/bc7acecb42334194bab81ed2c204681ee53845ea
Fixes: #1562
=> bmake: avoid deprecated egrep on Linux

usr.bin/qtrace/qtrace.c
The per-thread tracing flag will cause the kernel to enable tracing in the user process after execvp(). Enabling the tracing mode within qtrace is wrong and will produce a polluted trace with a portion of instructions from qtrace.
=> Do not start user-mode tracing in qtrace when using per-thread tracing.

bin/cheribsdtest/cheribsdtest_ptrace.c
ptrace()'s PIOD_READ_CHERI_TAGS requires that we operate on granules that are not merely eight capabilities wide but aligned to eight capabilities as well. calloc() does not, in general, impose sufficient alignment on its results, though SLAB-esque allocators like jemalloc and snmalloc probably will happen to do so.  Instead, switch to allocating the probe region on the stack and using an attribute to align it sufficiently.
Testing locally suggests this solves the problem, but I've also pushed this delta to `caprevoke` to get CI's opinion.  See https://ctsrd-build.cl.cam.ac.uk/job/CheriBSD-pipeline/job/caprevoke/21/ .
=> test_ptrace_readtags: stack alloc & align probe region

bin/cheribsdtest/Makefile.cheribsdtest, bin/cheribsdtest/cheribsdtest.h, bin/cheribsdtest/cheribsdtest_cheriabi.c, bin/cheribsdtest/cheribsdtest_util_vm.c, bin/cheribsdtest/cheribsdtest_vm.c, tools/build/Makefile
Add an use a new function to cheribsdtest to find empty sections of address space and use it remove some magic numbers.
Also included: a bootstrapping fix for makefs on older FreeBSD systems.
=> Add find_address_space_gap() to cheribsdtest

sys/kern/kern_cheri_revoke.c
When the cheri_revoke* syscall stubs are called from init, complain they are missing.  It's otherwise difficult to diagnose the cause of the panic that follows.
=> Warn about unimplemented syscalls in init

usr.sbin/makefs/zfs/fs.c
Cherry-picks of changes sufficient to use `makefs -t zfs` with the METALOG files generated by cheribuild.
=> makefs ZFS improvements

sys/dev/usb/usb_generic.c
Without this it'll lose the tags on ppBuffer and pLength, which has been
seen to make libusb hang. It's unclear why it hangs rather than giving
an error (likely missing error handling) but that's probably an upstream
issue that could be hit by using junk pointer values whereas this is a
CHERI-specific bug.
Fixes https://github.com/CTSRD-CHERI/cheribsd/issues/1616
=> usb_generic: Copy in endpoints with copyincap

sys/arm64/arm64/machdep.c, sys/arm64/include/param.h, sys/contrib/subrepo-openzfs/.gitrepo, sys/contrib/subrepo-openzfs/module/zfs/zfs_chksum.c, sys/riscv/include/param.h, sys/riscv/riscv/machdep.c
Pull in fixes for bugs preventing KSTACK_PAGES from being increased via the kernel config, increase the default for pure capability kernels, and remove a no-longer needed workaround in ZFS for allow the module to load.  This is now sufficient to allow a pure capability kernel to boot on a ZFS root file system.
=> ZFS purecap fixes

contrib/jemalloc/src/pages.c, sys/contrib/subrepo-openzfs/.gitrepo
Revert a very obsolete malloc change causing excessive alignment (and thus fragmentation) of mmap's regions.
Also include a fixup for the zfs subrepo.
=> Malloc overalignment

bin/cheribsdtest/cheribsdtest_util_vm.c
For large enough gaps (and thus alignements) it was possible to align the start address above the end address.  Due to ptraddr_t being signed, this could result in returning an address that was not a gap in the address spacep map.
Somewhat oddly this turned up in cheribsdtest-c18n-mt on the caprevoke branch and not somewhere earlier.
=> cheribsdtest find_address_space_gap bug

sys/arm64/include/cheri.h, sys/riscv/include/cheri.h, sys/sys/systm.h
Use the right DDC in restricted mode when creating userspace caps for hybrid processes.
Match base offsetting mode of userspace thread when creating userspace caps.
=> __USER_CAP fixes

sys/arm64/include/cheri.h, sys/sys/systm.h
Use a set of casts to create NULL-derived capabilities rather than a builtin since it doesn't matter if offset or address mode is used (the compiler might well add the value to the zero capability register).
Co-authored-by:	Jessica Clarke <jrtc27@jrtc27.com>
=> ___USER_CFROMPTR: simplify NULL-derived cap creation

sys/dev/rtwn/pci/rtwn_pci_var.h, sys/dev/rtwn/usb/rtwn_usb_var.h
The bus-specific drivers extend the common struct rtwn_softc with bus-specific fields and expect to cast a pointer to the base class back to the sub class.
Fixes #1636
=> rtwn: Add subobject bounds annotations for softc subclasses.

bin/cheribsdtest/Makefile.purecap, bin/cheribsdtest/cheribsdtest_vm.c, sys/arm64/arm64/cheri_revoke_machdep.c, sys/arm64/arm64/cheri_revoke_machdep_tests.c, sys/kern/kern_cheri_revoke.c, sys/kern/kern_proc.c, sys/riscv/riscv/cheri_revoke_machdep.c, sys/riscv/riscv/cheri_revoke_machdep_tests.c, sys/sys/user.h, sys/vm/vm.h, sys/vm/vm_cheri_revoke.h, sys/vm/vm_map.c, sys/vm/vm_map.h, usr.bin/procstat/procstat.1, usr.bin/procstat/procstat_vm.c
This PR adds quarantine and revocation of unmapped reservations. It can revoke a single range of address space per pass which currently means a single reservation. Posting now for discussion. Further work will add tests, ~add~ enhance merging of entries to improve the impact of a given revocation pass, and consider better options for selecting which entry to revoke.
=> Add quarantine and revocation of unmapped reservations

lib/Makefile
Commit 47da4fc4f55 ("Remove references to MK_LLVM_LIBUNWIND.") and upstream commit c45018041d5 ("retire the LLVM_LIBUNWIND option") conflicted such that these libraries were listed in both SUBDIR and SUBDIR_BOOTSTRAP.  Remove them from the latter to match upstream.
=> lib: Avoid building libgcc_(eh|s) twice

Makefile.inc1
As of macOS Ventura, Apple-signed binaries cannot be run if copied away from their system location. This security feature doesn't really make sense for boring things like sh(1), more so for applications with special entitlements, but it's universally present, and results in the following error:
>>> Install check world
bmake[2]: "/Users/Jess/cheri/freebsd/Makefile.inc1" line 572: warning: "MAKEFLAGS= CPUTYPE=dummy /Users/Jess/cheri/build/freebsd-riscv64-build/bmake-install/bin/bmake -f /dev/null  -m /Users/Jess/cheri/freebsd/share/mk MK_AUTO_OBJ=no -V CPUTYPE" exited on a signal
bmake[2]: "/Users/Jess/cheri/freebsd/Makefile.inc1" line 575: CPUTYPE global should be set with ?=.
As with host-symlinks, we don't actually need to copy the files on macOS, since we're not updating the current …
=> Makefile.inc1: Support building with macOS Ventura's AMFI Launch Constraints

contrib/jemalloc/src/jemalloc.c
It is impossible distinguish between a zero-bounded capablity to the slot before an allocation and a zero-bounded capability to the allocation.  As such, the allocator must reject zero-bounded capability and not produce them.
This reverts a commit that set zero length bounds on the 1-byte allocations used for zero length allocations.
=> jemalloc: don't set zero length bounds

contrib/libpcap/gencode.c
Currently the non-NetBSD code assumes that long is the maximum alignment needed for anything allocated from the chunk allocator. In practice, on typical 32-bit and 64-bit Unix platforms, this is true, since all the structures stored in it have only pointers and 32-bit integers. However, CHERI (on 64-bit architectures) uses 128-bit capabilities to implement C language pointers, which are a combination of a traditional 64-bit address, 64 bits of metadata and an additional 129th validity tag bit. Due to the use of tagged memory to support this tag bit they must be stored at naturally aligned addresses, i.e. 16 byte aligned, but long is still only 64-bit, since that is the natural machine word size for integer arithmetic, and thus if sdup tries to allocate a string of between 0 and 7 bytes …
=> libpcap: gencode: Unify NetBSD and non-NetBSD alignment, and make more general

Makefile.inc1, contrib/jemalloc/src/jemalloc.c, contrib/libpcap/gencode.c, lib/libc/cheri/Makefile.inc, lib/libc/cheri/strfcap.3, sys/arm64/include/cheri.h, sys/riscv/include/cheri.h, sys/sys/systm.h
Backport a number of minor fixes (nothing here warrants a point release):
- Fix __USER_CAP creation from processes in restricted mode (not available by default) and construct capabilities according to the processes DCC offsetting mode.
- Fix a bug in the strfcap manpage and actually install it
- Fix builds on macOS Ventura (https://github.com/CTSRD-CHERI/cheribuild/issues/339)
- Correct an issue with malloc where we returned zero-length capabilities for zero sized requests which could lead to a use-after-free in fairly contrived cases.
- Correct an alignment issue in libpcap causing issues with wpa_supplicant. Fixes #1637
=> 22.12 backports 20230303

sys/kern/sysv_msg.c, sys/kern/sysv_sem.c, sys/kern/sysv_shm.c, sys/sys/msg.h, sys/sys/sem.h, sys/sys/shm.h, usr.bin/ipcs/ipc.c
Correct ABi mismatches between the hybrid kernel and purecap binaries in the SysV semaphore and message queue ABIs by adopting the previously applied fix to sysvshm. While doing so, improve the declarations to the structs in the ABI so all the right things are visible in kernel and userspace.
=> Fix ipcs and ipcrm

sys/kern/kern_shutdown.c, sys/kern/kern_vnodedumper.c, sys/sys/conf.h
The callers of dump_savectx() (i.e., doadump() and livedump_start()) subsequently call dumpsys()/minidumpsys(), which dump the calling thread's stack when writing the dump.  If dump_savectx() gets its own stack frame, that frame might be clobbered when its caller later calls dumpsys()/minidumpsys(), making it difficult for debuggers to unwind the stack.
Fix this by making dump_savectx() a macro, so that savectx() is always called directly by the function which subsequently calls dumpsys()/minidumpsys().
This fixes stack unwinding for the panicking thread from arm64 minidumps.  The same happened to work on amd64, but kgdb reports the dump_savectx() calls as coming from dumpsys(), so in that case it appears to work by accident.
Fixes:	c9114f9f86f9 ("Add new vnode dumper to support live …
=> kerneldump: Inline dump_savectx() into its callers

sys/arm/arm/generic_timer.c
This broke Morello where ASR is required for the physical timer so init was in a crash/restart loop.
Diagnosed by:	jrtc27
=> arm: Always use the virtual timer in userland.

sys/arm64/arm64/unwind.c, sys/cheri/cheric.h, sys/riscv/riscv/unwind.c
The current code was accepting sealed capabilities with as a valid fp
value. This would then trap later when trying to load from the capability.
For RISC-V this actually failed on QEMU while evaluating the expression
`fp - sizeof(fp) * 2` in the kstack_contains() call since QEMU has not yet
been updated to be tag-clearing. I was seeing a boot failure here in the
WITNESS logic which was trying to treat a function pointer to `deadlkres`
as a dereferenceable frame pointer.
=> unwind_frame: reject sealed capabilities

sys/arm64/arm64/busdma_bounce.c
When performing DMA on a non cache coherent device we need to ensure the data cache has been invalidated before the device writes to the DMA memory. The helper function that performed this operation took a vm_offset_t, however the cache instructions need a capability.
Change the virtual address argument to a vm_pointer_t to ensure we have a capability.
This fixes CheriBSD on the Morello FVP.
=> arm64: Pass a capability to dma_preread_safe

sys/arm/arm/generic_timer.c, sys/arm64/include/armreg.h
This works around the need to expose the physical counter to userland and any restriction on the System Register Access permission.
Also added a tunable to switch the `sc->user_physical` which is always false for now. Not sure whether it may be useful for testing, so I left it in but I can yank it out.
=> Allow to enable emulation of cntfrq_el0 access.

lib/libkvm/kvm.3, lib/libkvm/kvm.c, lib/libkvm/kvm.h, lib/libkvm/kvm_read.3, sys/dev/mem/memdev.c, sys/sys/memrange.h
- mem: Add a MEM_READ_CHERI_CAP ioctl similar to PIOD_READ_CHERI_CAP.
- <sys/memrange.h>: Include <sys/ioccom.h>.
- libkvm: Add function to read tagged CHERI capabilities.
Note: This only contains support for live debugging via /dev/kmem.
Crash dumps will need additional changes.
=> Kernel memory tags via libkvm

bin/cheribsdtest/cheribsdtest_strfcap.c, lib/libc/cheri/strfcap.3, lib/libc/cheri/strfcap.c, lib/libc/stdio/printfcommon.h, lib/libc/stdio/vfprintf.c, sys/kern/subr_prf.c
While here, restructure the printing of capability attributes to make
it easier to extend.
=> riscv: Add "capmode" to the list of attributes printed for capabilities.

Makefile.inc1, etc/Makefile
This fixes two issues:
1. We install an additional empty /base directory
2. We don't install POSIX and en_US.US_ASCII NLS symlinks (which, due to the weird way they're done, actually appear in etcupdate's current tree and thus show as a local diff on a freshly-installed system)
=> Minor fixes for release builds

bin/cheribsdtest/arm64/cheribsdtest_md.h, bin/cheribsdtest/cheribsdtest_ptrace.c, bin/cheribsdtest/riscv/cheribsdtest_md.h, lib/libc/sys/ptrace.2, sys/arm64/arm64/exec_machdep.c, sys/cheri/cheri.h, sys/cheri/cheri_usercap.c, sys/kern/sys_process.c, sys/riscv/include/cheric.h, sys/riscv/riscv/exec_machdep.c, sys/riscv/riscv/support.S, sys/sys/ptrace.h, sys/vm/vm_map.c, sys/vm/vm_map.h, sys/vm/vm_mmap.c
- sys: Add helper functions for injecting capabilities via ptrace().
- riscv: Add a pcb_onfault wrapper around CBuildCap.
- riscv: Support PT_SETCAPREGS.
- arm64: Support PT_SETCAPREGS.
- ptrace: Add PIOD_WRITE_CHERI_CAP mode for PT_IO.
- ptrace.2: Document the policy knob for CHERI capability injection.
=> Capability injection via ptrace

sys/riscv/riscv/support.S
Otherwise a failing buildcap was always returning NULL rather than
the original untagged value.
Reported-by: Jessica Clarke <jrtc27@jrtc27.com>
=> Fix RISC-V CBuildCap workaround

sys/arm64/arm64/cheri_revoke_machdep_tests.c
Stop using no longer defined macros now that it's possible to print a capability in both hybrid and purecap kernels.  This fixes the ability to build without CHERI_CAPREVOKE_FAST_COPYIN.
=> caprevoke printf formating fix

lib/libc/csu/libc_start1.c
This was only used in the libcheri C startup code.
=> Remove CRT_ATEXIT_SUPPRESS

bin/cheribsdtest/cheribsdtest_fault.c, sys/riscv/cheri/cheri_debug.c, sys/riscv/include/riscvreg.h, sys/riscv/riscv/machdep.c
Currently a tag clearing implementation will fail two of the cheribsdtests. This commit adds support for the new "tag clearing semantics" feature bit (https://github.com/CTSRD-CHERI/sail-cheri-riscv/pull/74) that will be added to QEMU as well to allow all tests to pass with a tag clearing QEMU.
In the future we can change this warning message into a hard panic().
=> Prepare for tag clearing CHERI-RISC-V implementations

lib/libc/gen/elf_utils.c, lib/libc/include/libc_private.h, lib/libc/sys/interposing_table.c, lib/libthr/thread/thr_attr.c, lib/libthr/thread/thr_create.c, lib/libthr/thread/thr_private.h, lib/libthr/thread/thr_stack.c, lib/libthr/thread/thr_syscalls.c, libexec/rtld-elf/map_object.c, libexec/rtld-elf/rtld.c, libexec/rtld-elf/rtld.h
This does add several new #ifdefs that could increase the chance for conflicts in the future.  It might be nice if we could have an upstream macro in rtld to request building a version that doesn't support binaries that request executable stacks as that would make the upstream diff a bit less painful.
=> Remove thread guard pages and executable stacks entirely on purecap

sys/dev/mthca/mthca_memfree.c, sys/kern/sys_process.c, sys/ofed/drivers/infiniband/core/ib_umem.c, sys/vm/vm_map.c, sys/vm/vm_param.h
- Enable common PMAP macros on all platforms.
- vm: Update a few printf formats to uintmax_t to pacify 32-bit build.
- proc_cheri_cap_page: Use PHYS_TO_DMAP_PAGE.
- OFED: Fix a few places that use get_user_pages.
=> i386 kernel build fixes

sys/arm64/arm64/pmap.c, sys/riscv/riscv/pmap.c
Always use a capability with full page bounds when zeroing a subpage region.
=> Fix DMAP capability bounds in pmap_zero_page_area.

sys/arm64/arm64/freebsd64_machdep.c, sys/sys/systm.h
Upstream doesn't pull it in here; this diff dates back to CHERI-MIPS,
which stored DDC in the PCB and thus __USER_CAP needed its definition.
However, neither Morello nor CHERI-RISC-V get it from the PCB and so do
not need this include (nor is it a generic thing that's needed), so we
should not have this as a downstream diff any more.
This fixes building lib32 libprocstat on amd64. Currently it dies
building zfs_defs.c, since it transitively includes machine/fpu.h via
sys/systm.h and, because it hackily defines _KERNEL, gets kernel
prototypes for things like fpu_save_area_free which reference struct
savefpu, but x86/fpu.h will give the i386 definition, which is a union
not a struct, giving a tag mismatch error. This issue once again
highlights how awful this approach is, and how fragile …
=> sys/sys/systm.h: Drop downstream-only include of machine/pcb.h

Jenkinsfile
These add a bit to the build time, but we want to check that we're not regressing the lib32 build as has happened in the past. We may wish to flip the default in cheribuild (or remove the option entirely) at some point in the future once we don't need to support versions where the build is broken.
=> Jenkinsfile: Enable building lib32 in CI

bin/cheribsdtest/cheribsdtest_vm.c, lib/libsysdecode/flags.c, lib/libsysdecode/mktables, lib/libsysdecode/sysdecode.h, lib/libsysdecode/sysdecode_mask.3, libexec/rc/rc, libexec/rc/rc.subr, sys/arm64/arm64/pmap.c, sys/arm64/include/pmap.h, sys/cheri/revoke.h, sys/kern/kern_cheri_revoke.c, sys/kern/kern_exec.c, sys/riscv/include/pmap.h, sys/riscv/riscv/pmap.c, sys/vm/pmap.h, sys/vm/vm_cheri_revoke.c, sys/vm/vm_cheri_revoke.h, sys/vm/vm_map.c, usr.bin/kdump/kdump.c, usr.bin/truss/syscall.h, usr.bin/truss/syscalls.c
Fix/work around some issues present in the caprevoke tree.
- The first change is a cherry pick of a change that for reasons I don't fully understand triggers other issues: panic on Morello due to calling a NULL revocation test function and hang in rccorder (the change should cause a significant increase in the malloc/free calls as I believe the append pattern in the sh is basically realloc repeatedly.)
- The first vmspace_fork() fix addresses the NULL pointer dereference.
- The second I noticed while fixing the first.
- Finally, I disable the rcorder use that causes hangs as it's quite hard to debug during boot.  More investigation required.
=> caprevoke fork fixes

sys/arm64/arm64/identcpu.c, sys/arm64/include/armreg.h
It's plausible these could mean something else in the Arm architecture outside of the Morello architecture fork, so we shouldn't go defining (and using) them unless we know we're targeting Morello.
=> arm64: Don't define Morello-specific register fields for non-CHERI

bin/cheribsdtest/cheribsdtest.c
Currently we just use "Child exited abnormally" for when the child process doesn't exit cleanly, which is unhelpful when debugging, so print the signal number instead if it was due to a signal.
Note that tests which deliberately provoke signals still exit cleanly, since the child's test harness will catch the signal, save various parts of the given siginfo_t and exit. This code is only for more catastrophic situations (e.g. signal delivery itself is broken or the child received a fatal signal before even setting up the handler).
=> cheribsdtest: Improve reason if child unexpectedly dies with a signal

etc/mtree/BSD.usr.dist, share/examples/Makefile, share/examples/cheribsdtest/Makefile, share/examples/cheribsdtest/run-many
This lets you easily run multiple cheribsdtest variants in sequence, filtering out the verbose logging for each test, printing just the summary lines at the end, as a useful tool for local testing. It is only intended for humans and should not be extended for use in automated environments; those should be using cheribuild or another similar tool to do things properly.
=> examples: Add a new /usr/share/examples/cheribsdtest/run-many

libexec/rtld-elf/rtld_paths.h, usr.bin/ldd/ldd.c, usr.bin/stdbuf/stdbuf.c
This at last finishes the multi-year transition from libcheri to lib64c, now that cheribuild should be able to handle both.
=> Replace LD_CHERI_ prefix with LD_64C_ for rtld-elf64c

sys/kern/kern_cheri_revoke.c, sys/vm/vm_map.c
In working on #1743 I discovered that I was the unmapped entry that was being revoked too early resulting in it never being removed except perhaps in the most accidental fashion. Fixing this turned up a bug when exiting a process that was in the load-side INITED state as we'd hit an assert when trying to unlink the entry being removed.
=> caprevoke: actually revoke unmapped entries

sys/kern/imgact_elf.c
When loading hybrid position-dependent binaries, we do not care about the representability of the ELF sections. The reservation creation will skip the representability alignment enforcement as well, so avoid complaining about alignment when creating the imgact_capability.
This should fix #1700.
=> Do not enforce representability for hybrid binaries in elf imgact.

sys/arm64/cheri/cheri_coaccept.S, sys/arm64/cheri/cheri_cocall.S, sys/cheri/cheri_colocation.c
This PR contains fixes for two issues with the user space switcher and unborrowing logic:
1. Copies of the values in the ctpidr_el0 register in the kernel data structures were overwritten with wrong values in some situations.
2. Cocall and coaccept did not return the number bytes copied.
Here a more detailed explanations of the issue with ctpidr_el0. After executing the unborrowing code the thread returns from current system call and then executes the copark system call. Copark causes eventually cpu_switch(...) to be called, which saves the current register state, including the value of ctpidr_el0, into a kernel data structure. This data structure is later used restore the state of the thread when it is again scheduled on the CPU. However, the ctpidr_el0 register contains a value that …
=> Fixed coprocess switcher and unborrowing logic for Morello.

lib/libthr/thread/thr_init.c
The current stack pointer will have a very big non-zero offset at the
point this is called, so adding on the length will take it way beyond
the real "base" (top) of the stack. This greatly confused WebKit, since
it would very easily observe during its evaluation loop that the
difference between the current stack pointer and this claimed base was
bigger than the (correct) reported stack size, and thus conclude that
the stack had overflowed and throw an exception (helpfully with no
message).
Fixes:	31044f68ee91 ("libthr: Always define usrtack from the main thread's stack pointer.")
=> thr_init: Fix __thr_get_main_stack_base for purecap

libexec/rtld-elf/map_object.c, sys/kern/imgact_elf.c, sys/sys/elf.h
If an architecture defines ELF_IS_CHERI, always check it in the
non-CHERI case (imgact_elf64.c), not just in CHERI-enabled kernels.
=> imgact_elf: Enable ELF_IS_CHERI check always

bin/cheribsdtest/cheribsdtest.c, bin/cheribsdtest/cheribsdtest.h, bin/cheribsdtest/cheribsdtest_registers.c, bin/cheribsdtest/cheribsdtest_syscall.c, bin/cheribsdtest/cheribsdtest_vm.c, share/examples/cheribsdtest/run-many
- cheribsdtest: Remove the sig_dfl_neq_ign test
- cheribsdtest: Trim some spurious debug printfs.
- cheribsdtest: Export verbose flag so tests can use it
- cheribsdtest: Move debug printfs conditional on verbose
- cheribsdtest: Remove some stale macros for printing capabilities
- run-many: Hide SKIP test results
=> Reduce cheribsdtest verbosity

sys/sys/_stdint.h, sys/sys/_types.h, sys/sys/signal.h
Also update the comment here to clarify what exactly is going on (the
talk about CToPtr in particular is a bit confusing, really it's saying
why we use __intptr_t rather than __intcap_t for hybrid userspace, but
the latter would be a bit stupid to use anyway).
=> sys/signal.h: Simplify __SIGHANDLER_CONSTANT by using __kintcap_t

sys/kern/sysv_msg.c
Free the msghdr in question, not the first msghdr in the global
msghdrs array.  This corrupted the free_msghdrs list resulting in
panics during the kyua tests.
Fixes:		9bada506e46f sysvmsg: switch message queues to TAILQs
=> sysv_msg: Fix a typo when freeing a msghdr.

usr.sbin/pkg/CheriBSD.conf
Change the mirror type to "none" to match the reality as we don't provide mirroring, and don't use the "pkg+http://" URL scheme that libfetch(3) disallows when not using mirroring.
A package repository with a mirror type set to "srv" must point at an URL that includes a domain with SRV records in its DNS entry. pkg 1.18.4 from CheriBSD 22.12 doesn't verify that but pkg 1.20.5 or later scheduled for the next CheriBSD release will do. Note that this change is compatible with both 1.18.4 and 1.20.5 pkg versions so we don't have to synchronize merging this commit with packages for the next release.
=> Disable pkg repository mirroring

lib/libc/gen/lockf.c
INTERPOS_fcntl uses fixed arguments per the underlying syscall, not
variadic like the C wrappers.
Found by running a purecap visudo on Morello, which gives EFAULT for an
F_SETLK of the sudoers file.
=> lockf: Use correct calling convention for fcntl syscall

sys/riscv/conf/CHERI_FETT, sys/riscv/conf/CHERI_GFE, sys/riscv/conf/CHERI_QEMU, sys/riscv/conf/CHERI_QEMU_MFS_ROOT, sys/riscv/conf/CHERI_SPIKE, sys/riscv/conf/QEMU_MFS_ROOT
These were deprecated in July 2020 so their removal is long overdue.
=> riscv: Remove old underscore-based kernel configs

bin/cheribsdtest/cheribsdtest.c, bin/cheribsdtest/cheribsdtest.h, bin/cheribsdtest/cheribsdtest_sentries.c
This has never really been used in a meaningful way, and using it is a
bit dodgy, since it's information the test is telling to the harness
about itself; any information it wants to give itself it can just use
directly rather than looping it through the struct. Other than being
used in sentry_static as a lazy way to get a function pointer, it has
only ever been used for ct_stdin_string/ct_stdout_string, but using
those in particular is even more dodgy, since there's a risk that,
should those values end up corrupted or otherwise wrong, the test uses
that wrong value, rather than the original value it meant, and creates a
circularity in the checking that renders it less meaningful.
=> cheribsdtest: Stop passing struct cheri_test

bin/cheribsdtest/cheribsdtest.c
After #1803 we'll need another way to find the current test's `struct cheri_test` so store it in a static global where #1802 can find it.
=> cheribsdtest track the running test

sys/arm64/arm64/db_trace.c, sys/arm64/arm64/exception.S, sys/arm64/arm64/machdep.c, sys/riscv/riscv/db_trace.c
- arm64 db_trace: Use cheri_can_access for trapframes.
- arm64: Fix the pseudo FP (c29) for kernel exceptions for purecap.
- arm64 makectx: Fix overflow of tf_x array
=> arm64 purecap kernel panic fixes

bin/cheribsdtest/cheribsdtest_vm.c
Recent LLVM emits a warning here by default which causes -Werror failures.
=> cheribsdtest: add missing (void) to function signatures

sys/fs/tarfs/tarfs_vfsops.c
The ustart_header is defined as a struct with several char arrays.
The checksum is computed in two loops, one for fields before the
checksum and the second for fields after the checksum.  The second
loop was constraining the pointer to the bounds of the field after the
checksum (typeflag) rather than the remainder of the header.
=> tarfs: Disable subobject bounds on the header for tarfs_checksum

sys/riscv/cheri/cheri_exception.c, sys/riscv/include/cheri.h, sys/riscv/riscv/trap.c
Output a string description of the exception type and the register
name.
=> riscv: Include more details for kernel CHERI fault panics

bin/cheribsdtest/cheribsdtest_cheriabi.c, sys/vm/vm_mmap.c
Relax the requirement of mincore's addr argument.  Because mincore only reads metadata about page status, require that it be a memory capability that can do something (tagged, unsealed, and have at least one of load, store, or execute permissions) and that if cover some part of each page for which metadata is retrieved.
Fixes #1806
=> mincore: adjust capability requirements

tools/cheribsdbox/Makefile
FreeBSD no longer supports WITHOUT_CASPER and this was spamming the
log with warnings.  MK_CASPER=no is sufficient to disable casper
support.
=> cheribsdbox: Drop -DWITHOUT_CASPER

sbin/ping/Makefile
- Revert "Disable tests for now."
- ping: Fix a mostly harmless buffer overflow in -S parsing in main
=> Re-enable ping tests for purecap

share/mk/bsd.cpu.mk, sys/conf/kern.mk
And enable `-morello-bounded-memargs` for the kernel.
This is the first phase of the ABI switch whose end goal is to enable `-morello-bounded-memargs` for all purecap code. Supercedes #1695.
=> Enable -morello-bounded-memargs=caller-only for Morello purecap userland

bin/cheribsdtest/cheribsdtest_util_vm.c, sys/cheri/cheri_exec.c, sys/cheri/cheric.h, sys/kern/imgact_elf.c, sys/kern/kern_exec.c, sys/kern/subr_devmap.c, sys/kern/sysv_shm.c, sys/riscv/riscv/machdep.c, sys/vm/vm_kern.c, sys/vm/vm_map.c
- cheribsdtest: Remove extraneous + 1 from address space gap alignment
- riscv fake_preload_metadata: Always roundup lastaddr for module metadata
- vmspace_exec: Unexpand CHERI_REPRESENTABLE_BASE
- cheric.h: Add a CHERI_REPRESENTABLE_ALIGNUP macro
- sys: Unexpand CHERI_REPRESENTABLE_ALIGNUP in various places
=> Add CHERI_REPRESENTABLE_ALIGNUP

sys/dev/drm/bridges/tda19988/tda19988.c, sys/dev/drm/komeda/komeda_drv.c
- tda19988: Implement a non-stub mode_valid to filter unsupported resolutions
- tda19988: Properly implement mode_set/bridge_enable/bridge_disable flow
- tda19988: Fix divisor calculation
- komeda: Drop temporary resolution hack
=> Various TDA19988 fixes

sys/arm64/iommu/iommu_pmap.c
Using Inner Shareable on Linux supposedly resulted in disappearing
glyphs, a problem we are sometimes plagued by. Regardless of whether
this resolves that issue, we should do the right thing here and ensure
coherence between the GPU and CPU.
=> arm64: Map Mali GPU memory as Outer Shareable

lib/libc/stdlib/malloc/snmalloc/Makefile.inc
We only need to search the snmalloc include dir for snmalloc files.
Omitting the frame pointer is specific to malloc overheads.
=> snmalloc: narrow scope of more CXXFLAGS

sys/sys/param.h
=> Bump __CheriBSD_version to 20230804

usr.sbin/pkg/CheriBSD-debug.conf, usr.sbin/pkg/CheriBSD.conf, usr.sbin/pkg/Makefile
* Only for pkg64c, install a separate pkg repository file with the CheriBSD-debug repository definition that is disabled by default, and that can be enabled in /usr/local/etc/pkg/repos as advised in the configuration file itself;
* Increase the priority of the CheriBSD repository so that pkg64c commands consider it before the CheriBSD-debug repository;
* Remove unnecessary logic in Makefile that is specific to upstream and maps branch-specific configuration file names to their configuration names.
The CheriBSD-debug repository is disabled by default not to confuse users. If it was enabled `pkg64c search` would list packages twice, once for CheriBSD and once for CheriBSD-debug. Hence, it is better to disable it and document in the Getting Started with CheriBSD guide how to make use of …
=> Add a pkg repository with CheriABI debug packages

lib/libc/stdlib/malloc/mrs/mrs.c, sys/cheri/cheri_sysctl.c
We're seeing apparent UAF issues in the installer where they are annoying to debug so try disabling quarantine for now.
=> caprevoke: Don't revoke by default

sys/arm64/arm64/exec_machdep.c, sys/kern/sys_process.c, sys/kern/vfs_mount.c, sys/sys/proc.h, sys/vm/vm_map.c
- sys: Various fixes for KTR traces for hybrid kernels
- Fix quarantine_cmp to not return equal
- vm_map_entry_unlink: Cleanup a comment
- vm_map_entry_clone: Assert against cloning quarantine entries
- vm_map: Move quarantine RB_REINSERT into vm_map_merge_entries
- purecap: Grow the size of tst0_sched for purecap kernels
=> Fix panic when starting sddm after caprevoke merge

libexec/rc/rc.conf, sbin/ldconfig/ldconfig.8, sbin/ldconfig/ldconfig.c
- ldconfig: Document -64 in usage and the manual page
- Add /usr/lib64 to default 64-bit ldconfig paths
=> ldconfig -64 fixes

lib/csu/aarch64c/crt1_c.c, lib/csu/riscv/crt1_c.c, lib/csu/riscv64c/crt1_c.c
Without these libunwind attempts to unwind beyond _start which results in nonsense infinite backtraces. Found this by running the libunwind tests for RISCV and noticed that purecap was also missing these directives:
```
starting test1
Frame 1: _Z9backtracei+0x2e
Frame 2: _Z5test1i+0x40
Frame 3: main+0x28
Frame 4: __libc_start1+0x76
Frame 5: __start+0x18
Frame 6: _start+0x22
Frame 7: _Z9backtracei+0x2e
Frame 8: _start+0x22
Frame 9: _Z9backtracei+0x2e
Frame 10: _start+0x22
....
```
For RISC-V I added the directive to the C function rather than the assembly one but I could also add it to _start instead.
=> csu: Add missing .cfi_undefined directives

sys/dev/drm/bridges/tda19988/tda19988.c
The TDA19988 transmitter in Morello SoC r0p0 and r0p1 might not correctly detect hot-plugging due to incorrect voltage levels on the HPD pin.
As a workaround for this issue, a user can set dev.drm.disable_hpd to enforce using a screen if the transmitter only receives an RxSense packet indicating a screen is attached, ignoring if it's actually able to receive HDMI input.
This change was tested with and without the tunable enabled, using boards with and without the failure.
=> Add a workaround for the HPD issue in the TDA19988 transmitter

sys/arm64/arm64/pmap.c
Something is wrong with CLG handling of superpages leading to a tag-load page fault during revocation.  Work around this by disabling superpages by default in caprevoke kernels.
The triggering workload is:
find / -name foo
=> caprevoke: disable superpages on aarch64

sys/kern/kern_proc.c
Fix get_ps_strings for CHERI
The argument and environment vectors are arrays of
`char * __capability` not arrays of `char *`.
This fixes kern.proc.args if the arguments are long enough to overflow
the p_args cache which in turn fixes the bin/pkill/pgrep-f_test:main
test which used an ARG_MAX command line.
(cherry picked from commit cf3cc6322c4f1d694e223a2efa6f0c7d9f768c55)
=> Backport #1814 to 22.12

lib/libc/gen/lockf.c, usr.sbin/bsdinstall/scripts/auto
- lockf: Use correct calling convention for fcntl syscall
- bsdinstall: Drop obsolete warning about root-on-ZFS for purecap kernels
=> Backport #1798 and #1799 to 22.12

bin/cheribsdtest/Makefile.cheribsdtest, bin/cheribsdtest/cheribsdtest_malloc.c, lib/libc/stdlib/malloc/mrs/mrs.c
Add a test for calling malloc_revoke() with an empty quarantine in mrs and fix a crash when that happens.
Fixes: #1875
=> mrs: handle empty quarantine

bin/cheribsdtest/cheribsdtest_vm.c, lib/libprocstat/Symbol.map, lib/libprocstat/libprocstat.c, lib/libprocstat/libprocstat.h, sys/cheri/revoke_kern.h, sys/kern/kern_cheri_revoke.c, sys/sys/sysctl.h, sys/vm/vm_map.c, sys/vm/vm_map.h, usr.bin/procstat/Makefile, usr.bin/procstat/procstat.1, usr.bin/procstat/procstat.c, usr.bin/procstat/procstat.h, usr.bin/procstat/procstat_cheri.c
Delay quarantine of unmapped regions until after a revocation syscall has been made (typically early in libc startup).
Expose quarantine status via sysctl and a new `procstat cheri` subcommand.
=> caprevoke: fix address space leak, provide quarantine status

usr.bin/truss/setup.c
Syscalls are unchanged between CheriABI and the benchmark ABI, but the emul string differs.
Found by grep while working on #1873
=> truss support for benchmark ABI

sys/kern/kern_cheri_revoke.c, sys/vm/vm_map.c
- vm_map_delete: Leave max_prot for unmapped reservations as VM_PROT_NONE
- kern_cheri_revoke: Reload entryst after sleeping
=> Revoke fixes from Robert's demo box

sys/kern/kern_cheri_revoke.c
This work was begun under ECATS and further polished by Wes after he moved to Microsoft.
=> kern_cheri_revoke.c: Add a missing license header

lib/libc/stdlib/malloc/mrs/mrs.c, sys/vm/vm_mmap.c, usr.bin/kdump/kdump.c
- mmap: Add a SYSERRCAUSE for MAP_FIXED without CHERI_PERM_SW_VMEM
- kdump: Handle KTR_SYSERRCAUSE in the record type column
- mrs: For a realloc with a new size of 0 call the underlying malloc
- fixup: mrs: Don't return NULL for a realloc with a new size of zero
=> realloc fixes

sys/arm64/arm64/cheri_revoke_machdep.c, sys/arm64/arm64/cheri_revoke_machdep_tests.c, sys/riscv/riscv/cheri_revoke_machdep.c, sys/riscv/riscv/cheri_revoke_machdep_tests.c, sys/vm/vm_cheri_revoke.c
Assorted style fixes plus some typo fixes and comment cleanups:
- indentation of continued statements
- contine lines after operators not before
- return values in ()
- use __unused rather than (void) casts
- prefer `(flags & FLAG) != 0` to `!!(flags & FLAG)`
- use C-style comments
- declare more varables at the tops of blocks
- space after switch keyword
=> caprevoke: style(9) improvements

lib/libc/stdlib/malloc/mrs/mrs.c
Allocate unconditionally and copy+free if and only if the source pointer is valid and the allocation succeeds.
Suggested by @jrtc27 in the review of #1891
=> mrs: simplify realloc

sys/arm64/arm64/cheri_revoke_machdep.c, sys/riscv/riscv/cheri_revoke_machdep.c
This is required to avoid -Werror build failures with LLVM 15
=> Add missing void to function signatures

sys/arm64/arm64/locore.S, sys/arm64/arm64/machdep.c, sys/arm64/arm64/machdep_boot.c, sys/vm/vm_kern.c
- Morello: Restrict perms on thread0's stack to CHERI_PERMS_KERNEL_DATA
- Morello: Reduce perms on the modulep pointer passed from locore
- purecap kernel: Restrict permissions on kmem capabilities
=> Restrict some cap permissions in purecap kernels

sys/arm64/cheri/cheri_coaccept.S, sys/arm64/cheri/cheri_cocall.S
This PR addresses comments by @brooksdavis in https://github.com/CTSRD-CHERI/cheribsd/pull/1757.
After talking to @trasz, I renamed only two labels to reduce the number of merge conflicts that he'll have when he merges his current work on the user space switcher.
=> Clean up assembly that computes the return values of coaccept and cocall

lib/libprocstat/libprocstat.c, lib/libprocstat/libprocstat.h, usr.bin/procstat/procstat.1, usr.bin/procstat/procstat.c, usr.bin/procstat/procstat_auxv.c
Add support for printing auxv arguments as capabilities. Along the way make some fixes to the 32-bit compat code, fix support for hybrid ABIs, and improve the readability of output with wide commands.
=> procstat auxv improvements

lib/libc/stdlib/malloc/mrs/mrs.c, lib/libc/stdlib/malloc/mrs/mrs_utrace.h, lib/libsysdecode/Makefile, lib/libsysdecode/utrace.c
- mrs: Add utrace(2) events
- mrs: Use %#p instead of mrs_printcap
- mrs: Various style fixes, no functional change
- mrs: Apply recent realloc fixes to mrs_rallocx
- mrs: Make thread safe
=> mrs: Make thread safe and related cleanups

bin/cheribsdtest/Makefile.cheribsdtest, bin/cheribsdtest/cheribsdtest.c, bin/cheribsdtest/cheribsdtest.h, bin/cheribsdtest/cheribsdtest_internal.c, bin/cheribsdtest/cheribsdtest_vm.c
Add infrastructure to spawn children which exec and run a per-test function.
Supersedes #1802
=> cheribsdtest: infrastructure to spawn children

sys/cheri/cheri_sysctl.c
- Update the comment describing security.cheri.runtime_revocation_default
- Enable revocation by default
=> Enable revocation by default

lib/libc/aarch64/gen/_setjmp.S, lib/libc/aarch64/gen/setjmp.S, lib/libc/aarch64/sys/Makefile.inc, lib/libc/aarch64/sys/thr_exit.c, lib/libc/gen/dlfcn.c, lib/libsysdecode/utrace.c, lib/libthr/Makefile, libexec/rtld-elf/Makefile, libexec/rtld-elf/Symbol-c18n.map, libexec/rtld-elf/aarch64/reloc.c, libexec/rtld-elf/aarch64/rtld_c18n_asm.S, libexec/rtld-elf/aarch64/rtld_c18n_machdep.c, libexec/rtld-elf/aarch64/rtld_machdep.h, libexec/rtld-elf/aarch64/rtld_start.S, libexec/rtld-elf/cheri/cheri_reloc.h, libexec/rtld-elf/map_object.c, libexec/rtld-elf/rtld-libc/Makefile.inc, libexec/rtld-elf/rtld-libc/rtld_libc.h, libexec/rtld-elf/rtld.c, libexec/rtld-elf/rtld.h, libexec/rtld-elf/rtld_c18n.c, libexec/rtld-elf/rtld_c18n.h, libexec/rtld-elf/rtld_lock.c, libexec/rtld-elf/rtld_lock.h, libexec/rtld-elf/rtld_utrace.h, share/man/man7/compartmentalization.7, sys/arm64/arm64/elf_machdep.c
This PR contains changes pertaining to compartmentalisation that should be included in the autumn 2023 release.
Key changes:
* Support the transition ABI for passing memory arguments.
* Trampolines now clear unused argument registers based on function signature information embedded in the ELF.
* Compartment transition tracing and overhead simulation.
* Allow defining compartments that consist of multiple libraries.
* Support for the benchmark ABI.
=> c18n: Autumn 2023 release

usr.sbin/tzsetup/tzsetup.c
cherry pick from upstream so one more step of the install process can be pressing return
=> tzsetup: make UTC the first (default) region

bin/cheribsdtest/cheribsdtest.c, contrib/jemalloc/include/jemalloc/internal/sc.h, include/malloc_np.h, lib/libc/stdlib/malloc/mrs/Makefile.inc, lib/libc/stdlib/malloc/mrs/mrs.3, lib/libc/stdlib/malloc/mrs/mrs.c, libexec/malloc_is_revoking/malloc_is_revoking.c
- Move the responsibility for alignment of small allocations into MRS
- remove OPTIONAL_QUARANTINING ifdef
- tidy JUST_INTERPOSE definition now that OPTIONAL_QUARANTINING isn't optional
- GC some unused bits
=> mrs: alignment changes and cleanups

sys/kern/kern_proc.c, sys/sys/user.h, sys/vm/vm_cheri_revoke.c, sys/vm/vm_fault.c, sys/vm/vm_object.c, sys/vm/vm_object.h, usr.bin/procstat/procstat.1, usr.bin/procstat/procstat_vm.c
This set of changes exposes the OBJ_HASCAP flag of vm mapping to the user via procstat and then alters the creation of the underlying object to suppressing setting of OBJ_HASCAP when mappings are touched via faults.
I'm not really convinced by either the `OBJT_CHERI_SHADOW` psuedo type in creation or the revocation-specific `OBJ_CHERI_SHADOW` flag as APIs, but they seem to work. Suggestions from those more familiar with this code would be most welcome.
=> Don't create the shadows bitmap with OBJ_HASCAP

lib/libc/stdio/fflush.c, lib/libc/stdio/fvwrite.c, lib/libc/stdio/wbuf.c, lib/libcasper/services/cap_net/cap_net.c, lib/libcasper/services/cap_net/tests/net_test.c, sys/netpfil/pf/if_pfsync.c
- [FreeBSD-SA-23:15.stdio](https://www.freebsd.org/security/advisories/FreeBSD-SA-23:15.stdio.asc)
- [FreeBSD-SA-23:16.cap_net](https://www.freebsd.org/security/advisories/FreeBSD-SA-23:16.cap_net.asc)
- pfsync: Avoid transmitting uninitialized bytes in pfsync_sendout() (uninitialized data leak, no SA)
=> Merge FreeBSD 2023-11-08 security advisories

bin/cheribsdtest/Makefile, bin/cheribsdtest/Makefile.cheribsdtest, bin/cheribsdtest/benchmark-mt-c18n/Makefile, bin/cheribsdtest/cheribsdtest_context.c, bin/cheribsdtest/cheribsdtest_registers.c, lib/Makefile, lib/libc/aarch64/gen/setjmp.S, lib/libc_c18n/Makefile, lib/libthr_c18n/Makefile, libexec/Makefile, libexec/rc/rc.d/ldconfig, libexec/rtld-elf/aarch64/rtld_c18n_asm.S, libexec/rtld-elf/aarch64/rtld_c18n_machdep.c, libexec/rtld-elf/aarch64/rtld_start.S, libexec/rtld-elf/rtld_c18n.c, libexec/rtld-elf/rtld_c18n.h, libexec/rtld-elf64cb-c18n/Makefile, share/examples/cheribsdtest/run-many, share/man/man7/compartmentalization.7, sys/arm64/include/tls.h, usr.bin/ldd/ldd.c, usr.bin/stdbuf/stdbuf.c
This PR adds the benchmark ABI-variant of the compartmentalising dynamic linker.
=> c18n: Create ld-elf64cb-c18n.so.1 for the benchmark ABI

sys/vm/vm_cheri_revoke.c, sys/vm/vm_cheri_revoke.h, sys/vm/vm_object.c, sys/vm/vm_object.h
Fix a couple of problems with `VM_CHERI_REVOKE_QUICK_SUCCESSOR` and perform assorted cleanup.
=> caprevoke fixes and cleanup

sys/vm/vm_cheri_revoke.c
This work was begun under ECATS and further polished by Wes after he moved to Microsoft.
=> vm_cheri_revoke.c: Add a missing license header

sys/arm64/arm64/cheri_revoke_machdep.c, sys/arm64/arm64/pmap.c, sys/cheri/revoke_kern.h, sys/riscv/riscv/cheri_revoke_machdep.c, sys/riscv/riscv/pmap.c, sys/vm/pmap.h, sys/vm/vm_cheri_revoke.c, sys/vm/vm_object.h
All but the final commit are small, hopefully unobjectionable cleanups. The last fixes a race condition which I believe can trigger the assertion was removed in the commit.
=> Some cleanups and a bug fix for caprevoke

sys/arm64/arm64/exec_machdep.c
If we haven't switched away from the current thread then userspace may
have modified some of the capability registers we save in the PCB rather
than the trapframe since the last time we did so, and so we need to save
their updated values just as we do for VFP state in fill_fpregs when the
FPU is in use.
=> arm64: Don't use stale PCB in fill_capregs for curthread

lib/libprocstat/libprocstat.c, usr.bin/procstat/procstat_cheri.c
Tweak output to include `-` in columns were the data is meaningless and don't warn on EPERM in libprocstat
=> procstat cheri improvements

sys/arm64/arm64/exec_machdep.c
This follows the transitional memory-argument ABI used release 23.11 and will be removed once the ABI transition completes.
=> arm64: Clear c9 before invoking sigcode on Morello

sys/vm/vm_mmap.c
The copy-on-write flag for the MAP_GUARD vm_map operation is spelled MAP_CREATE_GUARD.
With the incorrect MAP_GUARD usage, an mmap(2) call with MAP_GUARD in a hybrid ABI process failed as a result of vm_map_insert1() returning KERN_INVALID_ARGUMENT when the maximum permissions are not VM_PROT_NONE.
=> Fix mmap(2) with MAP_GUARD for hybrid ABI

lib/libc/stdlib/malloc/mrs/mrs.c, libexec/rc/rc.d/motd, sys/cheri/cheri_sysctl.c, sys/cheri/revoke_kern.h, sys/kern/imgact_elf.c, sys/sys/elf_common.h
This debugging feature will tank performance but is useful in debugging, as UAF bugs are caught on first use rather than at some unknown point in the future as UAR (if at all). The global system default is only meant to be enabled by people wishing to flush out UAFs from CheriBSD; users should instead use the environment variable.
No proccontrol support is provided so as to discourage its use and make it harder for people to accidentally enable not knowing what they're doing.
=> caprevoke: Add ability to enable revocation on every free at run time

libexec/rc/rc.conf
The order of search paths matches the order of directories in the default value of the PATH environment variable.
=> rc.conf: add /usr/local64cb to rc.d search paths

contrib/subrepo-cheri-libunwind/.gitrepo, contrib/subrepo-cheri-libunwind/src/AddressSpace.hpp, contrib/subrepo-cheri-libunwind/src/DwarfInstructions.hpp, contrib/subrepo-cheri-libunwind/src/config.h
```
subrepo:
subdir:   "contrib/subrepo-cheri-libunwind"
merged:   "a11aebfb1a54"
upstream:
origin:   "https://github.com/CTSRD-CHERI/libunwind.git"
branch:   "monorepo-mirror"
commit:   "00c1abba9013"
git-subrepo:
version:  "0.4.1"
origin:   "https://github.com/ingydotnet/git-subrepo.git"
commit:   "1f13869"
```
NB: Incorporates the following commits:
```
commit 049700932e2f0fd301feee43db660c38a0be389d
Author: Jessica Clarke <jrtc27@jrtc27.com>
Date:   Thu Nov 30 23:37:02 2023 +0000
[libunwind] Don't skip unwinding last frame in call stack
Having the CFA be exactly at the capability top is expected at the top
of the call stack on secondary threads, so fix this off-by-one error
such that those frames are not skipped, only ones where the CFA is
strictly out-of-bounds.
This is a targeted …
```
=> git subrepo pull contrib/subrepo-cheri-libunwind

tools/build/depend-cleanup.sh
The multiple libcompat support was added upstream after the OpenSSL 3.0
import, so the initial addition of this code hard-coded lib32 only, and
thus missed lib64 (and lib64c). This effectively reapplies 81805ec30074
("depend-cleanup.sh: Generalise lib32 code and avoid duplication") to
get that missing support.
Fixes:	e99e69227dd5 ("depend-cleanup: apply big hammer for OpenSSL 3.0 update")
=> depend-cleanup.sh: Fix mismerge in OpenSSL 3.0 code

sys/sys/_stdint.h
In the interest of diff reduction, centrally define it to SIZE_MAX since they are the same on all practical architectures rather than editing each machine/_stdint.h as per standard practice.
Fixes:	#1793
=> stdint.h: define PTRADDR_MAX

share/mk/bsd.lib.mk
Due to not containing a literal lib32 or lib64 this slipped through the
cracks when generalising the build system to not hard-code the set of
libcompats everywhere. For now just fix it up manually rather than try
and generalise this one, which should be done later upstream.
Fixes:	3215005566be ("arm64: Add new lib64cb libcompat for purecap benchmark ABI")
=> bsd.lib.mk: Use correct debug directory for lib64cb

contrib/bsddialog/bsddialog.c, contrib/bsddialog/lib/barbox.c, contrib/bsddialog/lib/bsddialog.h, contrib/bsddialog/lib/lib_util.c, contrib/bsddialog/lib/lib_util.h, usr.sbin/bsdinstall/distextract/distextract.c, usr.sbin/bsdinstall/scripts/checksum
- bsdinstall: Encode dists to valid variable names in checksum script
- bsddialog: Optionally truncate long mixedgauge labels and screens
- bsdinstall: Enable bsddialog auto-truncate for distextract and checksum
=> Add auto-truncate to bsddialog and use for bsdinstall

sys/arm64/vmm/io/vgic.c, sys/arm64/vmm/io/vgic.h, sys/arm64/vmm/io/vgic_if.m, sys/arm64/vmm/io/vgic_v3.c, sys/arm64/vmm/vmm.c, sys/arm64/vmm/vmm_instruction_emul.c, usr.sbin/bhyve/aarch64/bhyverun_machdep.c, usr.sbin/bhyve/aarch64/fdt.c
First commit imports https://reviews.freebsd.org/D37428#979293. Later commits fix further issues with it and tweak userspace accordingly.
NB: sysutils/u-boot-bhyve-arm64 needs the following diff:
```diff
diff --git a/sysutils/u-boot-bhyve-arm64/Makefile b/sysutils/u-boot-bhyve-arm64/Makefile
index 5f024f30df6a..2e83ba4946fd 100644
--- a/sysutils/u-boot-bhyve-arm64/Makefile
+++ b/sysutils/u-boot-bhyve-arm64/Makefile
@@ -1,5 +1,7 @@
MASTERDIR=     ${.CURDIR}/../u-boot-master
+U_BOOT_SLAVE_PORTREVISION_2023.07.02=  1
+
MODEL=         bhyve-arm64
BOARD_CONFIG=  bhyve_arm64_defconfig
FAMILY=                bhyve
diff --git a/sysutils/u-boot-bhyve-arm64/files/patch-board_emulation_bhyve-arm_bhyve-arm.c b/sysutils/u-boot-bhyve-arm64/files/patch-board_emulation_bhyve-arm_bhyve-arm.c
index …
```
=> Various bhyve fixes to allow booting Linux

sys/arm64/vmm/arm64.h, sys/arm64/vmm/hyp.h, sys/arm64/vmm/io/vgic.c, sys/arm64/vmm/io/vgic.h, sys/arm64/vmm/io/vgic_if.m, sys/arm64/vmm/io/vgic_v3.c, sys/arm64/vmm/io/vgic_v3.h, sys/arm64/vmm/io/vgic_v3_reg.h, sys/arm64/vmm/io/vtimer.c, sys/arm64/vmm/io/vtimer.h, sys/arm64/vmm/mmu.h, sys/arm64/vmm/reset.h, sys/arm64/vmm/vmm.c, sys/arm64/vmm/vmm_arm64.c, sys/arm64/vmm/vmm_call.S, sys/arm64/vmm/vmm_dev.c, sys/arm64/vmm/vmm_hyp.c, sys/arm64/vmm/vmm_hyp_exception.S, sys/arm64/vmm/vmm_instruction_emul.c, sys/arm64/vmm/vmm_mmu.c, sys/arm64/vmm/vmm_reset.c, sys/conf/files.arm64, sys/modules/vmm/Makefile
- arm64: Sync vmm copyright headers with upstream review
- arm64: Sync vtimer with upstream review
- arm64: Sync vmmops_gla2gpa with upstream review
- arm64: Pull in vmm VPIPT code removal from upstream review
- arm64: Pull in vmm build system fixes from upstream review
"arm64: Sync vmmops_gla2gpa with upstream review" is a possible concern (@markjdb this seems to differ from how you handled the failure in CheriBSD, so would appreciate your review there if you've not already seen the change in the upstream review). The rest should all be very low risk (comments, deleting dead code and build system fixes).
=> arm64: Sync rest of VMM code with upstream review

sys/arm64/vmm/vmm_dev.c
Apply 7a0c23da4eaa ("vmm: Destroy character devices synchronously.") to
arm64's copy of vmm_dev.c so that a VM name can be reused as soon as
sysctl hw.vmm.destroy=name returns. The amd64 patch applies without any
conflicts.
=> arm64: Destroy vmm character devices synchronously

sys/arm64/vmm/vmm_dev.c
Applies a85404906bc8 ("vmm: Add credential to cdev object") to arm64's
outdated fork of amd64's vmm_dev.c, preventing processes in one jail
accessing VMs in another. Patch applies cleanly without any conflicts.
=> arm64: Add credential to vmm cdev object and use for lookup

sys/vm/vm_map.c, tests/sys/posixshm/posixshm_test.c
Fix two panics in the large page support triggered by repeated unmaps of the same reservation and trying to map over a quarantined reservation.
Tweak the tests so they all pass. The changes aren't perfect in terms of test coverage, but they are valid for now.
=> POSIX shared memory largepage fixes

COPYRIGHT, sys/sys/copyright.h
I cherry-picked the upstream bump commit for consistency and then bumped our copyrights. Also added ETC and MTSS acks.
A couple things that might want to be addressed separately.
- CapLtd might want to claim a collective copyright, unsure what dates apply.
- A more condensed (bulleted?) ack format might be nice since I think we're missing some non-DARPA acks and CPM is coming.
=> 2024 copyright bump and add missing acks

lib/libc/gen/tls_malloc.c, lib/libmalloc_simple/malloc.c, libexec/rtld-elf/rtld_malloc.c
QEMU CheriABI user mode implements tagged memory now.
This reverts commit 11e986fc851036a52bd3dd8413172a5646e69ee0 and fixes https://github.com/CTSRD-CHERI/cheribsd/issues/1755.
=> Revert "Explicitly clear a pointer to the next free block."

etc/Makefile, share/man/Makefile
Otherwise these are omitted for -DNO_ROOT builds, whether for disk images or dist tarballs.
=> share/man: Add mandoc.db files to METALOG

libexec/rtld-elf/rtld.c
Only copy over tls_static_space bytes from the old TLS block to the
new one.
=> rtld: Reduce diff with upstream in allocate_tls

Makefile.inc1
Otherwise makewhatis can be run too early for -DNO_ROOT builds. This
makes use of the CheriBSD-specific SUBDIR_INSTALL_USE_DEPENDS option
until the dodginess has been resolved upstream, as is already done for
libexec's installing of libcompat rtld-elf variants.
=> Makefile.inc1: Ensure etc installs last for -DNO_ROOT

Makefile.inc1, libexec/Makefile, share/mk/bsd.subdir.mk
- bsd.subdir.mk: Drop broken optimisation for realinstall parallelisation
- Revert "Makefile.inc1: Ensure etc installs last for -DNO_ROOT"
- Revert "Fix parallel install of some rtld manpages."
=> Sync with upstreamed -DNO_ROOT realinstall parallel fix

libexec/rtld-elf/Makefile, libexec/rtld-elf/rtld-libc/Makefile.inc, libexec/rtld-elf/rtld.h
- rtld-elf: Drop redundant downstream MK_PIE override
- rtld-elf: Drop obsolete assignment to CXXFLAGS
- rtld-elf: Drop obsolete libc arch include path addition
- rtld-libc: Stop checking for and trying to use --building-freebsd-rtld
- rtld-elf: GC old unused CHERI-MIPS PLT remnants
- rtld-elf: Sync process___cap_relocs declaration guard with definition
=> Various rtld-elf cleanups

sys/sys/param.h
It turns out we must build OpenJDK packages sooner than I thought.
As @jrtc27 mentioned in https://github.com/CTSRD-CHERI/cheribsd/pull/1986, I'd like to merge this change to releng/23.11 and build the packages now instead of waiting for the ABI bump.
=> Cherry-pick to releng/23.11: Define is_aligned() only for the kernel

libexec/rtld-elf/aarch64/reloc.c, libexec/rtld-elf/aarch64/rtld_c18n_asm.S, libexec/rtld-elf/aarch64/rtld_c18n_machdep.c, libexec/rtld-elf/aarch64/rtld_start.S, libexec/rtld-elf/cheri/cheri_reloc.h, libexec/rtld-elf/rtld.c, libexec/rtld-elf/rtld_c18n.c, libexec/rtld-elf/rtld_c18n.h, share/man/man7/compartmentalization.7
These are the last c18n commits before switching to the new ABI (#1981).
=>  c18n: Align benchmark ABI protection model to CHERI-RISC-V 

sys/arm64/arm64/gicv3_its.c
In the pure-capability kernel cpu_dcache_wb_range requires a capability as the first argument.
This fixes a boot-time panic with the latest dev branch on the Morello board.
=> Do not cast GICv3 pointers to integers for cache invalidation.

sys/cddl/compat/opensolaris/kern/opensolaris_uio.c, sys/compat/freebsd32/freebsd32_misc.c, sys/compat/freebsd64/freebsd64_misc.c, sys/compat/linux/linux_file.c, sys/kern/kern_jail.c, sys/kern/kern_ktrace.c, sys/kern/kern_sendfile.c, sys/kern/subr_prf.c, sys/kern/subr_uio.c, sys/kern/sys_generic.c, sys/kern/vfs_aio.c, sys/kern/vfs_mount.c, sys/kern/vfs_vnops.c, sys/sys/uio.h
There is a trade-off between having an possibly imprecise sub-allocation for the iovec array and using two different malloc()/free() calls for the uio and iovec arrays.
Note that, without explicitly modifying the uio free() code paths, the struct uio can not have tight bounds, because the call to free() requires a capability with the same bounds returned by malloc().
This patch abstracts away the uio allocation using the `allocuio()` and `freeuio()` functions.
Introduce a new UMA zone to allocate `struct uio`. The `struct uio` is modified to include an embedded small iovec array that is meant to satisfy the majority of iovec array allocations without the need for a dedicated external allocation. When the iovec array is larger than the embedded array, allocate a larger chunk of memory …
=> Make sure that the iovec array in struct uio is representable.

libexec/rtld-elf/aarch64/rtld_c18n_asm.S, libexec/rtld-elf/aarch64/rtld_start.S, libexec/rtld-elf/rtld.c, libexec/rtld-elf/rtld_c18n.c, libexec/rtld-elf/rtld_c18n.h, share/man/man7/compartmentalization.7
The PR overhauls the protection model used in the benchmark ABI from a rather ad-hoc model to one that logically matches what would be done on CHERI-RISC-V.
It also fixes `dlsym`, which relied on `__builtin_return_address`. The fix for the benchmark ABI is straightforward. But on the purecap ABI with register banking, `__builtin_frame_address(1)` needs to be used which triggers a warning that needs to be explicitly disabled.
=> c18n: Improvements and bugfixes

usr.sbin/efibootmgr/efibootmgr.c
If cnt == 0 we access element 0 unconditionally, which is out of bounds,
and then if that doesn't crash and happens to be 0 we will access
element - 1, also out of bounds, and then if that doesn't crash will add
1 to whatever junk is there and use that for the variable. On CHERI,
though, this does crash. This code is also overly complicated, with
unnecessary special cases and tracking more state than needed.
Rewrite it in a more general manner that doesn't need those special
cases and naturally works for cnt == 0.
Found by:	CHERI
Reviewed by:	imp
Fixes:		1285bcc833a3 ("Import Netflix's efibootmgr to help manage UEFI boot variables")
MFC after:	1 week
Differential Revision:	https://reviews.freebsd.org/D44029
(cherry picked from commit 09cb8031b43c8e98abb5ff9b43ff649031d1e808)
This fixes …
=> efibootmgr: Simplify make_next_boot_var_name and fix cnt == 0 case

libexec/tftp-proxy/Makefile, rescue/rescue/Makefile, sbin/ifconfig/Makefile, sbin/pfctl/Makefile, sbin/route/Makefile, sys/netlink/netlink_snl.h, tools/cheribsdbox/Makefile, usr.bin/genl/Makefile, usr.bin/netstat/Makefile, usr.sbin/arp/Makefile, usr.sbin/authpf/Makefile, usr.sbin/ftp-proxy/Makefile, usr.sbin/ndp/Makefile
- netlink: Don't use a zero-length array
- Re-enable fatal linker warnings for programs using netlink
=> Stop disabling linker warnings for netlink

contrib/libexecinfo/backtrace.c
This commit should ensure we don't lose tags in `backtrace_symbols_fmt()`. This alone does not make libexecinfo's backtrace work properly. The other issues, however, are in libunwind and will be addressed in the llvm repository.
=> libexecinfo: Preserve tags in backtrace_symbols_fmt().

sys/arm64/arm64/cpufunc_asm.S
This somewhat reduces the diff with upstream which uses x3 for both
the result and temporary pointer.
=> arm64: Reuse PTR(3) as the temporary to read the cache line size

usr.sbin/kldxref/ef_riscv.c
As with R_MORELLO_CAPINIT only the address is output.
=> kldxref: Handle R_RISCV_CHERI_CAPABILITY

lib/libc/aarch64/gen/_setjmp.S, lib/libc/aarch64/gen/setjmp.S, libexec/rtld-elf/aarch64/rtld_c18n_asm.S, share/mk/bsd.cpu.mk, sys/arm64/arm64/exec_machdep.c, sys/conf/kern.mk, sys/dev/psci/smccc_arm64.S
This completes the ABI transition started by
cb987198fe2cf46c10317423b8a917dbf2ec3a6a. We set
-morello-bounded-memargs when building both the kernel and purecap userland.
This also reverts commit a81684622828b38239c1102fe9dc34e55653d39b, which is only applicable to the transition ABI.
=> arm64: Switch to final ABI for passing memory arguments

libexec/rtld-elf/aarch64/rtld_c18n_asm.S, libexec/rtld-elf/aarch64/rtld_c18n_machdep.c, libexec/rtld-elf/aarch64/rtld_c18n_machdep.h, libexec/rtld-elf/rtld.c, libexec/rtld-elf/rtld_c18n.c, libexec/rtld-elf/rtld_c18n.h
Put the frame pointer (c29 as provided by the caller of the trampoline) and the return address (c30) together. This layout complies with the AArch64 ABI and enables privileged unwinders (e.g. the kernel) to walk through the trusted frame transparently.
=> c18n: Change trusted frame layout for better unwinding

contrib/mandoc/config.h, lib/libpmc/pmu-events/jevents.c, usr.sbin/kldxref/kldxref.c
macOS, like Linux, does not include an outer const qualifier for its
fts_open callback arguments, so -Wincompatible-function-pointer-types
also picks this up and breaks the build now Clang 16 makes it an error
by default. Extend the existing Linux support to fix this.
=> Fix bootstrapping on macOS with Clang 16 / Apple Clang 15

libexec/rtld-elf/tests/Makefile, libexec/rtld-elf/tests/cheri/Makefile, libexec/rtld-elf/tests/cheri/abi-mismatch/dlopen-hybrid/dlopen-hybrid.c, libexec/rtld-elf/tests/cheri/abi-mismatch/dlopen-purecap/dlopen-purecap.c
- rtld-elf: Set proper TESTSDIR for tests/cheri and use TESTS_SUBDIRS
- rtld-elf: Drop dlopen_nocheri tests
=> rtld-elf: Fix cheri tests

sys/sys/malloc.h
Fixes:	2a2d2282513c ("Split userspace and kernel iovec types.")
=> sys/malloc.h: Pass correct type in free_c

usr.sbin/kldxref/ef.c, usr.sbin/kldxref/ef.h, usr.sbin/kldxref/ef_obj.c, usr.sbin/kldxref/elf.c
If a string is at or near the end of an input file and the amount of
remaining data in the file is smaller than the maximum string size,
the pread(2) system call would return a short read which is treated as
an error.  Instead, add a new helper function for reading a string
which permits short reads so long as the data read from the file
contains a terminated string.
Reported by:	jrtc27
Reviewed by:	jrtc27
Sponsored by:	University of Cambridge, Google, Inc.
Differential Revision:	https://reviews.freebsd.org/D44419
(cherry picked from commit 785600d0fb13d6f0b4595bf4dbbc048113dda71d)
=> kldxref: Properly handle reading strings near the end of an ELF file

sys/sys/param.h
=> Bump __CheriBSD_version to 20240315

libexec/rtld-elf/aarch64/rtld_c18n_asm.S, libexec/rtld-elf/aarch64/rtld_c18n_machdep.h, libexec/rtld-elf/rtld_c18n.c
Previously, the caller's stack pointer is only saved at the bottom of the caller's stack during domain transition. This means that the act of unwinding a trusted frame relies on external state, namely the value at the bottom of the caller's stack.
We now also save the caller's stack pointer in the trusted frame so that unwinding can be stateless, i.e., inspecting the content of the trusted frame alone is sufficient for restoring the stack pointer of the caller.
=> c18n: Save caller's stack pointer in trusted frame

libexec/rtld-elf/aarch64/rtld_c18n_asm.S, libexec/rtld-elf/rtld_c18n.c
Previously, the dummy stack used to fill the Restricted stack pointer when running Executive mode code is just a capability pointing to itself. This commit augments the dummy stack to contain full metadata like all other Restricted stacks.
=> c18n: Augment dummy stack to contain full metadata

lib/libc/include/libc_private.h, lib/libc/sys/interposing_table.c, lib/libc/sys/sigaction.c
Previously c18n signal handling was supported by overriding __libc_sigaction to call RTLD hooks. However, libthr swaps the default sigaction implementation for its own, yet many libc function continue to call __libc_sigaction instead of the libthr version of sigaction.
This commit creates a new function to be inserted into the interpose table while reverting __libc_sigaction to redirect through the interpose table.
=> libc: Do not override __libc_sigaction to support c18n signal handling

bin/cheribsdtest/Makefile.cheribsdtest, bin/cheribsdtest/cheribsdtest.h, bin/cheribsdtest/cheribsdtest_fptr_canon.c, lib/libcheribsdtest_dynamic/Makefile, lib/libcheribsdtest_dynamic/cheribsdtest_dynamic_fptr.c
These reveal the currently-broken c18n implementation.
=> cheribsdtest: Add function pointer canonicity tests

sys/kern/sys_process.c
I got a `panic: cheri revoke does not support foreign maps (yet)` running GDB on `chericat`. This fix merges the tweak from ebc253e0464f87220085b303a5427fad91cd1d90 into `proc_read_cheri_tags_page()`, which seems to resolve the issue here. But definitely wants review by @markjdb. When ready, this change will want to go into the demo branch also.
=> Update capability tag reading via ptrace() for async revocation

.github/workflows/style.yml, tools/build/checkstyle9.pl
This is very expensive to run against merges from dev to main.  Even
for PRs against dev we would only want it to be advisory (and wouldn't
want it for upstream FreeBSD merge PRs).
=> .github: Update the style checker action for CheriBSD

libexec/rc/rc.d/ldconfig
The original change to factor out the ldconfig_paths helper function
accidentally dropped it due to a variable name mismatch (_ldconf vs
_soconf).  As a result, the 4th argument looked unused so I removed
it.  Rather than re-adding the 4th argument to the helper, just
include /etc/ld-elf.so.conf in the list of paths used in the second
for loop.
=> ldconfig: Restore handling for /etc/ld-elf.so.conf

lib/libc/aarch64/gen/_setjmp.S, lib/libc/aarch64/gen/setjmp.S, lib/libgcc_s/Makefile, lib/libgcc_s/Symbol-c18n.map, lib/libgcc_s/Versions.def, libexec/rtld-elf/Symbol-c18n.map, libexec/rtld-elf/aarch64/rtld_c18n_asm.S, libexec/rtld-elf/rtld_c18n.c, libexec/rtld-elf/rtld_c18n_policy.txt
These 2 commits are bundled together with https://github.com/CTSRD-CHERI/llvm-project/pull/731 into https://github.com/CTSRD-CHERI/cheribsd/pull/2003 for easy testing. There is currently a lot of code duplication across `longjmp`, resume and unsealed resume, and I'm not too sure how to eliminate it since we're in a context where we can't perform a function call, so any function would have to be always inlined (while the compiler supports this, I'm not sure if it's good practice here?). I also wanted to avoid making *too* much of it a macro so that debugging of these functions doesn't become painful.
=> c18n, libgcc_s: Support a c18n-aware libunwind.

libexec/rtld-elf/Symbol-c18n.map, libexec/rtld-elf/rtld_c18n.c, sys/sys/link_elf.h
Extend struct r_debug to contain a pointer to RTLD's array of compartments and count of elements.  Export the size of struct compart so a debugger can walk the array.
=> c18n: Allow GDB to access compartment data

sys/arm64/arm64/cheri_revoke_machdep.c
No test case at the moment, as I've had trouble reproducing this. It's very timing-sensitive. Verified by looking at the disassembly of `vm_cheri_revoke_page_rw()` in kgdb:
```
0xffff000000a23c70 <+340>:   clrtag  c0, c24
0xffff000000a23c74 <+344>:   mov     w8, #0x2 <-- this instruction is missing without the patch
0xffff000000a23c78 <+348>:   ldxr    c1, [c28]
0xffff000000a23c7c <+352>:   cmp     c1, c24
0xffff000000a23c80 <+356>:   b.ne    0xffff000000a23c88 <vm_cheri_revoke_page_rw+364>  // b.any
0xffff000000a23c84 <+360>:   stxr    w8, c0, [c28]
0xffff000000a23c88 <+364>:   cbz     w8, 0xffff000000a23c18 <vm_cheri_revoke_page_rw+252>
0xffff000000a23c8c <+368>:   gctag   x9, c1
0xffff000000a23c90 <+372>:   cbz     x9, 0xffff000000a23c20 <vm_cheri_revoke_page_rw+260>
0xffff000000a23c94 …
```
=> arm64: Make stxr_status an input operand in vm_do_cheri_revoke()

lib/libthr/thread/thr_create.c, libexec/rtld-elf/aarch64/rtld_c18n_asm.S, libexec/rtld-elf/rtld_c18n.c
The PR bundles together three minor improvements to c18n.
1. When c18n is disabled, the _rtld_setjmp helper (and its counterparts for libunwind) must not access the trusted stack but should tail-call an epilogue assembly function.
2. Trampoline tables are now allocated with malloc instead of mmap.
3. Block all signals when a new thread is created and only restore the signal mask when the actual thread function is about to be called. This is need for full interrupted safety which will be implemented in the future.
=> Miscellaneous c18n improvements

libexec/rtld-elf/aarch64/reloc.c
This will resolve a long-standing quirk, making R_MORELLO_JUMP_SLOT look like a normal R_MORELLO_RELATIVE relocation rather than being unchanged from R_AARCH64_JUMP_SLOT in the ELF object.
See https://git.morello-project.org/morello/llvm-project/-/merge_requests/296
=> rtld-elf: Support upcoming new ABI for R_MORELLO_JUMP_SLOT

sys/conf/kern.mk, sys/conf/kern.pre.mk, sys/conf/kmod.mk
The kernel build on Morello still uses some options that pre-date support for EFLAGS in Morello lld.
=> morello: Remove deprecated flags from build config.

sys/arm64/arm64/bus_space_asm.S, sys/arm64/arm64/copyinout.S, sys/arm64/arm64/cpufunc_asm.S, sys/arm64/arm64/efirt_support.S, sys/arm64/arm64/exception.S, sys/arm64/arm64/memcmp.S, sys/arm64/arm64/memcpy.S, sys/arm64/arm64/memset.S, sys/arm64/arm64/strcmp.S, sys/arm64/arm64/strncmp.S, sys/arm64/arm64/support.S, sys/arm64/arm64/swtch.S, sys/arm64/arm64/trap.c, sys/arm64/conf/GENERIC-MORELLO-PURECAP-BENCHMARK, sys/arm64/conf/GENERIC-MORELLO-PURECAP-BENCHMARK-NODEBUG, sys/arm64/include/cheric.h, sys/cheri/cheri_sysctl.c, sys/conf/kern.mk, sys/dev/psci/smccc_arm64.S, sys/kern/init_main.c
Tested on QEMU, boot and cheribsdtests are passing.
Tested on Morello board, cheribsdtests are passing.
Once merged, should close #1983 .
=> Benchmark ABI kernel

sys/vm/vm_cheri_revoke.c, sys/vm/vm_meter.c, sys/vm/vm_object.h
Otherwise t_vmshr gives a silly number, and is what pre-3.3.0 htop uses
for shared (magenta in the default colour scheme) memory in its memory
meter. 3.3.0 switches to the more sensible t_rmshr given the bar is
meant to reflect real, not virtual, memory, but we should still report
more useful totals here.
=> caprevoke: Also exclude shadow bitmap from global VM stats

sys/amd64/amd64/mem.c, sys/amd64/amd64/uio_machdep.c, sys/arm/arm/uio_machdep.c, sys/arm64/arm64/mem.c, sys/arm64/arm64/pmap.c, sys/arm64/arm64/uio_machdep.c, sys/cam/scsi/scsi_target.c, sys/compat/lindebugfs/lindebugfs.c, sys/dev/iicbus/iic.c, sys/dev/md/md.c, sys/fs/procfs/procfs_osrel.c, sys/i386/i386/uio_machdep.c, sys/kern/kern_physio.c, sys/kern/subr_uio.c, sys/kern/vfs_vnops.c, sys/powerpc/powerpc/uio_machdep.c, sys/riscv/riscv/mem.c, sys/riscv/riscv/pmap.c, sys/riscv/riscv/uio_machdep.c, sys/sys/_uio.h, sys/sys/uio.h, sys/ufs/ffs/ffs_suspend.c, sys/vm/pmap.h
This approach is more orthogonal and permits using capability copies
with uiomove_frompyhs or higher level APIs like proc_rwmem without
requiring additional *_cap wrapper routines.
=> uiomove*_cap: Refactor using UIO_READ/WRITE_CAP permissions

lib/libc/gen/tls_malloc.c, lib/libc/sys/mmap.2, lib/libmalloc_simple/heap.c, sys/sys/mman.h, sys/vm/vm_mmap.c
This set of patches makes MAP_CHERI_NOSETBOUNDS a no-op and deprecates it.  Instead, treat MAP_FIXED within an existing reservation as if MAP_CHERI_NOSETBOUNDS was passed and return the `addr` argument unchanged.
I've run into this a couple times while looking at exposing capability load/store page permissions via mmap so I'd like to take the first step before 24.05.
One use remains in the tree in RTLD to allow it to work with older kernels.  For the next release I plan to remove the definition from userspace and then make it an error in the following release.
=> mmap: deprecate MAP_CHERI_NOSETBOUNDS

lib/libsimple_printf/Makefile
It's now a "single" option rather than a pair of incompatible options.
As mentioned in https://github.com/CTSRD-CHERI/cheribsd/pull/2046#issuecomment-1998234008 merge this on it's own.
=> libsimple_printf: Catch up with INIT_ALL option

lib/libgcc_s/Makefile, libexec/rtld-elf/Makefile
With recent changes in https://github.com/CTSRD-CHERI/llvm-project/pull/731, we need to guard these libunwind defines behind aarch64 to avoid breaking other archs (like CHERI-RISC-V).
=> Guard -D_LIBUNWIND_SANDBOX_OTYPES behind an aarch64 check

sys/sys/param.h, usr.sbin/pkg/CheriBSD-debug.conf, usr.sbin/pkg/CheriBSD.conf, usr.sbin/pkg/config.c
**NOTE: this is not ready to be merged until we have packages deployed.**
We need to use a custom compiler to build packages for the demonstration branch with c18n support for function pointers. Not to confuse these packages with production packages for releases and the dev branch, the packages for this branch will be stored in a separate subdirectory.
"[DO NOT MERGE]" headlines should be kept after these commits are merged into `demo-2024-06`. We don't want them to be merged into dev.
=> Package manager configuration for demo-2024-06

lib/libthr/thread/thr_create.c, libexec/rtld-elf/rtld.c
When a pthread is created, RTLD stores in its tcb field a fake tcb-like structure that contains a capability to the actual tcb and a capability to the thread's stack lookup table. This is done so that when the thread is entered, it does not need to create a stack lookup table, which involves a memory allocation that cannot be performed without a stack lookup table in the first place.
This commit fixes a mistake where the tcb field is not restored to the real tcb upon thread entry.
=> c18n: Set curthread->tcb to real tcb upon thread start 

libexec/rtld-elf/aarch64/rtld_c18n_asm.S, libexec/rtld-elf/rtld.c, libexec/rtld-elf/rtld_c18n.c, libexec/rtld-elf/rtld_c18n.h, libexec/rtld-elf/rtld_c18n_policy.txt
So that no lazy binding happens during the call, which might clobber registers when c18n is disabled. (Registers are always clobbered when c18n is enabled due to the use of trampolines.)
Also remove _rtld_unw_*_unsealed as they are no longer used by libunwind.
=> c18n: Make _rtld_unw_setcontext callable via function pointer

sys/sys/param.h
Note that we have already bumped __CheriBSD_version after 23.11 but we want to update it again in case there are dev users who should upgrade packages after the next package repositories' build.
=> Bump __CheriBSD_version to 20240617

sys/sys/param.h
Note that we have already bumped __CheriBSD_version after 23.11 but we want to update it again in case there are dev users who should upgrade packages after the next package repositories' build.
=> Merge dev to main for 24.05 release: __CheriBSD_version

sbin/nos-tun/nos-tun.c, sys/net/if.c, sys/netinet/in.c, sys/netlink/route/iface.c, usr.sbin/ppp/iface.c, usr.sbin/uhsoctl/uhsoctl.c
The SIOCDIFADDR{,_IN6} ioctls take an ifreq structure object, not an ifaliasreq/in_aliasreq/in6_aliasreq structure object, as their argument.
On CHERI, the incorrect calls using the in6_aliasreq object result in CHERI capability violations. A pointer to the ifra_addr field in in6_aliasreq cast to the ifru_addr union member of in6_ifreq results in bounds being set to the union's larger size. Such bounds exceed the bounds of of in6_aliasreq object and the bounds-setting instruction clears a tag of the object's capability.
Fixes: https://github.com/CTSRD-CHERI/cheribsd/issues/2129
=> netinet: correct SIOCDIFADDR{,_IN6} calls to use {,in6_}ifreq

usr.bin/sort/file.c, usr.bin/sort/radixsort.c
These interact quite poorly with MRS with revocation enabled, which implements realloc() by always creating a new allocation.  Even a modification to return the original pointer if its bounds satisfy the request doesn't help much there.
Apply a simple bandaid: grow the allocation exponentially.  This has no major downside except when virtual address space is scarce, and that's something we don't typically worry about.  There doesn't appear to be any explicit justification for growing buffers so conservatively.
This yields a significant reduction in the amount of time needed to build a cscope database (cscope invokes sort(1) under the hood).
=> sort: Avoid linear realloc loops

bin/cheribsdtest/cheribsdtest_ifunc.c, lib/libcheribsdtest_dynamic/Makefile, lib/libcheribsdtest_dynamic/cheribsdtest_dynamic_ifunc.c, libexec/rtld-elf/aarch64/rtld_c18n_asm.S, libexec/rtld-elf/aarch64/rtld_c18n_machdep.h, libexec/rtld-elf/aarch64/rtld_start.S, libexec/rtld-elf/rtld.c, libexec/rtld-elf/rtld_c18n.c, libexec/rtld-elf/rtld_c18n.h
~Just for CI. Do not merge yet.~
This should fix #2130.
=> c18n: Fix rtld_bind reentry bug

sys/kern/uipc_socket.c, sys/netinet/tcp_usrreq.c, sys/sys/sockopt.h
- **ktls: Use SOPT_SETCAP to fix KTLS socket options for CHERI kernels**
- **sys: Replace SOPT_SET/GETCAP with sooptcopyincap**
=> Fix kernel TLS on CHERI kernels

contrib/bsddialog/lib/barbox.c, contrib/bsddialog/lib/lib_util.c
For the height this doesn't matter unless auto_minheight is non-zero,
but for the width it does, as it would subtract off the maximum of
various things including the text width, which is clearly nonsense here.
All we want to do is compute how much space for content there is; what's
on other lines doesn't matter.
Fixes:	64f70731e375 ("bsddialog: Optionally truncate long mixedgauge labels and screens")
=> bsddialog: Fix widget_maxsize to only take into account window decor

sys/riscv/riscv/uio_machdep.c
Commit 98682fe6266037bf3a86164a8f56a4975fa96112 added UIO_READ_CAP and UIO_WRITE_CAP as options uiomove but did not update the associated KASSERT for RISC-V.
=> uiomove_fromphys: Fix incorrect KASSERT

lib/libc/stdlib/malloc/mrs/mrs.c
When the passed pointer is valid and already has enough space, return it unless it's at least twice the requested size.
Some software uses realloc to extend allocations by small, fixed amounts.  In a naive implementation of realloc that blindly performes a new allocation, copies the data, and the frees the old allocation, this is O(n^2).  For small values of `n` this isn't too noticable, but for asymptotically it's quite bad and revocation makes it much worse. With current tuning, we eventually reach a point where approximately every 4th allocating triggers a revocation pass.
We can make this somewhat less visible (or fix it entierly for snmalloc with it's power-of-two sized buckets) by omitting unnecessicary allocations and copies.
Bias towards improveing linear increase performance over …
=> mrs_realloc: avoid copies when space is available

sys/arm64/arm64/machdep_boot.c
A small fix for a crash I hit during boot, triggered by the kernel automatically unloading a preloaded kernel module.
=> Relax permissions on preloaded metadata

lib/libsys/mmap.2, lib/libsysdecode/mktables, libexec/rtld-elf/map_object.c, sys/sys/mman.h, sys/vm/vm_mmap.c
This completes the removal started in f918bdbcd8af.  After this commit:
- Rtld will require a kernel were MAP_CHERI_NOSETBOUNDS is a no-op (24.05 release or any kernel after f918bdbcd8af).
- The kernel completely ignores MAP_CHERI_NOSETBOUNDS so old binaries relying on MAP_CHERI_NOSETBOUNDS should still work (so long as it does not also rely on the bounding behavior).
- Software depending on MAP_CHERI_NOSETBOUNDS will no longer compile.
=> mmap: complete removal of MAP_CHERI_NOSETBOUNDS

sys/dev/drm/core/drm_edid.c
Merge commit 97794170b696 from Linux (by Douglas Anderson):
drm/edid: In connector_bad_edid() cap num_of_ext by num_blocks read
In commit e11f5bd8228f ("drm: Add support for DP 1.4 Compliance edid
corruption test") the function connector_bad_edid() started assuming
that the memory for the EDID passed to it was big enough to hold
`edid[0x7e] + 1` blocks of data (1 extra for the base block). It
completely ignored the fact that the function was passed `num_blocks`
which indicated how much memory had been allocated for the EDID.
Let's fix this by adding a bounds check.
This is important for handling the case where there's an error in the
first block of the EDID. In that case we will call
connector_bad_edid() without having re-allocated memory based on
`edid[0x7e]`.
Fixes: e11f5bd8228f ("drm: …
=> drm: Fix out of bounds access in connector_bad_edid

share/mk/bsd.sys.mk
After upgrading LLVM we get the following error:
`keyword '__make_signed' will be made available as an identifier for the remainder of the translation unit [-Werror,-Wkeyword-compat]` This will be fixed once libc++ is upgraded to version 16, but this commit can be cherry-picked back to older release branches.
=> Disable warnings triggered in libc++15 with Clang 16

libexec/rtld-elf/Makefile
Uncovered while building pkgbase packages for CheriBSD.
=> Fix a small build issue in rtld

sys/arm64/arm64/pmap.c
This is a stopgap to fix some instability after recent dev merges. The main change is to simply disable creation of L3C mappings in userspace for now. I also fixed up some of the L3C routines, as they represent yet another place which synthesizes PTEs and thus needs to be taught about Morello-specific bits.
=> Address a few problems with L3C mappings on Morello

usr.sbin/bhyve/virtio.c
bhyve: Support legacy PCI interrupts on arm64
This allows us to remove various #ifdef hacks and enable building more
PCI devices.
Note that a hole is left in the interrupt mapping for the RTC rather
than having the two core devices straddle the PCIe interrupts. QEMU's
virt machine also takes this approach.
Reviewed by:    jhb
MFC after:      2 weeks
Obtained from:  CheriBSD
=> Fix mismerge of upstream commit which was skipped:

sys/arm64/arm64/pmap.c, sys/arm64/include/pmap.h, sys/compat/linuxkpi/common/include/asm/set_memory.h, sys/compat/linuxkpi/common/include/linux/io.h, sys/dev/agp/agp_i810.c, sys/dev/ena/ena.c, sys/kern/link_elf.c
This passes down a valid pointer all the way to cpu_dcache_*.
Previously the pointer was silently truncated to an address.
=> arm64 pmap_change_{attr,prot}: Switch first arg to vm_pointer_t

lib/libpmcstat/libpmcstat.h, lib/libpmcstat/libpmcstat_image.c, lib/libpmcstat/libpmcstat_logging.c, lib/libpmcstat/libpmcstat_process.c, lib/libpmcstat/libpmcstat_symbol.c, sys/sys/pmckern.h, usr.sbin/pmc/Makefile, usr.sbin/pmcstat/Makefile, usr.sbin/pmcstat/pmcpl_annotate.c, usr.sbin/pmcstat/pmcpl_annotate.h, usr.sbin/pmcstat/pmcpl_annotate_cg.c, usr.sbin/pmcstat/pmcpl_annotate_cg.h, usr.sbin/pmcstat/pmcpl_callgraph.c, usr.sbin/pmcstat/pmcpl_callgraph.h, usr.sbin/pmcstat/pmcpl_calltree.c, usr.sbin/pmcstat/pmcpl_calltree.h, usr.sbin/pmcstat/pmcpl_gprof.c, usr.sbin/pmcstat/pmcpl_gprof.h, usr.sbin/pmcstat/pmcstat_log.c, usr.sbin/pmcstat/pmcstat_log.h
- **hwpmc: Use ptraddr_t instead of uintfptr_t**
- **pmc,pmcstat: Re-enable -Werror**
=> Fix warnings in purecap pmcstat

sys/modules/zfs/Makefile
The current list is missing aarch64cb, so zfs for purecap benchmark
kernels is built with subobject bounds and thus panics with a bounds
fault early in boot if used. Instead of updating the list to include
aarch64cb, just check MACHINE_ABI, which is available here.
=> zfs: Detect purecap kernels via MACHINE_ABI not a list of MACHINE_ARCH

sys/fs/tmpfs/tmpfs.h, sys/fs/tmpfs/tmpfs_subr.c
Without this, installing in a 4G VM fails (at least with ZFS root selected); the installation appears to succeed, but there are errors in /tmp/bsdinstall_log due to running out of space in /tmp, meaning rc.conf, sysctl.conf and loader.conf are missing in the installed system, causing zfs.ko to not be loaded and thus the kernel not be able to mount root.
It was also reported upstream that poudriere falls over for larger packages even with 64G, and I encountered issues upstream with buildworld -j4 on a 16G system when /tmp is configured to be a tmpfs (non-default, but what cheribuild likes to do).
=> Backport tmpfs threshold fix

lib/libc/aarch64/gen/_setjmp.S, lib/libc/aarch64/gen/setjmp.S, lib/libc/gen/posix_spawn.c, lib/libc/include/libc_private.h, lib/libc/sys/sigaction.c, lib/libsys/interposing_table.c, lib/libthr/thread/thr_create.c, lib/libthr/thread/thr_rtld.c, lib/libthr/thread/thr_sig.c, libexec/rtld-elf/aarch64/reloc.c, libexec/rtld-elf/aarch64/rtld_start.S, libexec/rtld-elf/cheri/cheri_reloc.h, libexec/rtld-elf/map_object.c, libexec/rtld-elf/rtld-libc/rtld_libc.h, libexec/rtld-elf/rtld.c, libexec/rtld-elf/rtld.h, libexec/rtld-elf/rtld_lock.c, libexec/rtld-elf/rtld_lock.h, sys/sys/link_elf.h
CHERI_LIB_C18N is only ever defined under the purecap ABI, so there is no need to separately check for the purecap ABI.
=> c18n: Remove unnecessary check for purecap ABI

sys/compat/freebsd32/freebsd32_proto.h, sys/compat/freebsd32/freebsd32_systrace_args.c, sys/compat/freebsd32/syscalls.conf, sys/compat/freebsd64/freebsd64_misc.c, sys/compat/freebsd64/freebsd64_proto.h, sys/compat/freebsd64/freebsd64_systrace_args.c, sys/compat/freebsd64/syscalls.conf, sys/sys/types.h
- **freebsd64_fcntl: Remove unnecessary cast**
- **freebsd32/64: Map [u]intptr_t syscall arguments to [u]intXX_t**
- **sysent: Regen**
=> Fix freebsdNN compat for [u]intptr_t syscall arguments

lib/libc/tests/ssp/Makefile
- **libc/tests: Fix installation without MK_TOOLCHAIN**
- **libc/tests: Further refine the condition for installing h_raw**
=> Fix install of CheriBSD/amd64 on FreeBSD/amd64 hosts

libexec/rtld-elf/aarch64/rtld_cheri_machdep.h, libexec/rtld-elf/aarch64/rtld_machdep.h, libexec/rtld-elf/riscv/rtld_cheri_machdep.h, libexec/rtld-elf/riscv/rtld_machdep.h, libexec/rtld-elf/rtld.h
This header defines new CHERI-specific APIs including inline functions
which depend on the definition of Obj_Entry.  This restores the
include of rtld_machdep.h to its earlier location upstream in rtld.h
which will be required by a future upstream change to add
MD_OBJ_ENTRY.
=> rtld-elf: Split out rtld_cheri_machdep.h from rtld_machdep.h

contrib/elftoolchain/libdwarf/libdwarf.h, contrib/elftoolchain/libdwarf/libdwarf_loc.c
For a few DWARF types, a pointer is smuggled through the DwarfLoc lr_number2 member.  Add a new Dwarf_Uintptr type and use it to allow this to work on CHERI.  It differs from the standard uintptr_t in that it is always capable of holding a 64-bit integer.
This allows `readelf -wi /usr/lib/debug/lib/libc.so.7.debug` to succeed.
=> libdwarf: allow pointers in DwarfLoc lr_number2

bin/cheribsdtest/cheribsdtest_vm.c
Add a couple tests for hoarding of capabilities in shared memory segments
- cheri_revoke_shm_anon_hoard_unmapped demonstrates hoarding by an unmapped shared memory object
- cheri_revoke_shm_anon_hoard_closed takes this a step further and removes the object from the file descriptor table by sending it to a child process while revocation runs
=> cheribsdtest: shm hoarding tests

bin/cheribsdtest/cheribsdtest_vm.c, lib/libsys/mmap.2, sys/sys/mman.h, sys/vm/vm_mmap.c
This PR proposes to remove MAP_ALIGNED_CHERI and MAP_ALIGNED_CHERI_SEAL. I'm not 100% certain this is what I want to do, but I did it in an old branch where I was aiming to add capability PROT_ values and I'd like to do it or discard it.
The argument for removal is that a hybrid program needs to be aware of size rounding or it will either create aliasing violations or leak address space on `munmap`, thus adding MAP_ALIGN() macros isn't a big deal. Reservations could solve this, but I you probably need to opt all the way in to forcing representability on all allocations at which point it's a new ABI whose rules you need to follow. One could decide that MAP_ALIGNED_CHERI* triggers reservation roundup in which case at least the main one is useful. (I think sentries likely eliminate the …
=> Remove MAP_ALIGNED_CHERI

sys/dev/drm/core/drm_vm.c, sys/dev/drm/drmkpi/include/linux/mm.h, sys/dev/drm/freebsd/drm_gem_cma_helper.c, sys/dev/drm/freebsd/drm_os_freebsd.c, sys/dev/drm/panfrost/panfrost_gem.c, sys/dev/drm/panfrost/panfrost_mmu.c, sys/vm/phys_pager.c
The last commit is the main change. I had tried a couple of times to split it up but it was hard to do correctly, so I gave up in the interest of making the patches available a bit more quickly.
I took some small liberties in modifying drmkpi and DRM to better match the design of FreeBSD's fault handler. Since this code (drm device file mmap, fault handling) is highly non-portable anyway, I think this should be acceptable.
This should fix the panics reported in #2097 . I might be too optimistic, but so far it also seems to address some issues I was seeing with tearing and clipped text.
=> drm: Some refactoring and bug fixes to address VM panics

libexec/rtld-elf/rtld_c18n.c
Previously, a bounds-check was missing for the tail-call scenario, which might result in reading from the stack table using an invalid index.
Also, the tail-call scenario cannot be ruled-out even when the presumptive callee's stack is not allocated---we might be interrupted when a tail-call is taking place _and_ the callee's stack is unallocated.
=> c18n: Improve detection of interrupted compartment

usr.sbin/bhyve/aarch64/vmexit.c, usr.sbin/bhyve/amd64/bhyverun_machdep.c, usr.sbin/bhyve/amd64/ioapic.c, usr.sbin/bhyve/amd64/pci_irq.c, usr.sbin/bhyve/amd64/pci_lpc.c, usr.sbin/bhyve/amd64/pci_lpc.h, usr.sbin/bhyve/bhyve_config.5, usr.sbin/bhyve/bhyverun.c, usr.sbin/bhyve/bootrom.c, usr.sbin/bhyve/bootrom.h, usr.sbin/bhyve/gdb.c, usr.sbin/bhyve/pci_emul.c
Some of these are pending review upstream so perhaps we should wait until those land so that we have clean cherry-picks from FreeBSD.
- Fix a problem where `-G w<portnum>` causes the guest to abort after being resumed if more than one vCPU is configured.
- Fix a problem where some gdb command replies were not being escaped properly, causing gdb to fail to read capabilities from memory if one is unlucky.
- Fix a problem where u-boot triggers an assertion failure in bhyve by reprogramming BARs.
=> Assorted bhyve bug fixes

sys/arm64/arm64/cheri_revoke_machdep.c, sys/riscv/riscv/cheri_revoke_machdep.c
=> caprevoke: Fix missing early-clobber in vm_do_cheri_revoke

sys/arm64/include/atomic.h
Use a ptraddr_t as the input that can be assigned to the register
constraint as is done for RISC-V.  This allows the compiler to either
hoist the gcvalue out of the loop, or to just use the x portion of the
relevant register.
=> morello atomic: Trim gcvalue from the spin loop of arithmetic atomics

sys/netinet/ip_input.c
=> cheri: Use container bounds when accessing sockaddr_dl from sdlbuf

include/ssp/ssp.h
lib/libc/secure and hence *_chk() libc function variants for SSP are not built when the world is compiled for the pure-capability ABI.
In such a case, don't define __SSP_FORTIFY_LEVEL, based on _FORTIFY_SOURCE, that is used to redefine libc functions to their *_chk() variants. This check matches the check in lib/libc/Makefile to exclude lib/libc/secure.
With this change, devel/m4 that uses _FORTIFY_SOURCE builds correctly.
=> include: ssp: ignore fortify for purecap

lib/libc/aarch64/gen/_setjmp.S, lib/libc/aarch64/gen/setjmp.S, lib/libc/gen/Symbol.map, lib/libc/gen/dlfcn.c, lib/libgcc_s/Makefile, lib/libgcc_s/Symbol-c18n.map, libexec/rtld-elf/Symbol-c18n.map, libexec/rtld-elf/aarch64/rtld_c18n_asm.S, libexec/rtld-elf/aarch64/rtld_c18n_machdep.h, libexec/rtld-elf/rtld_c18n.c, libexec/rtld-elf/rtld_c18n.h, libexec/rtld-elf/rtld_c18n_policy.txt, sys/arm64/include/c18n.h, sys/sys/link_elf.h
See also #2122 for a draft of this PR.
_rtld_unw_getcontext_epilogue is removed because when c18n is not enabled, the trusted stack field of the context is unused anyway, so there's no need to fill it.
The assembly stub in _rtld_unw_setcontext is removed because _rtld_unw_setcontext is now expected to be called before all registers are restored, so it does not need to restore any register anymore.
=> c18n: New {get,set}context APIs for libunwind

lib/libgcc_s/Makefile, lib/libgcc_s/Symbol-c18n.map
We've not yet imported an updated libunwind, so should keep the old
build system parts here until that's happened, otherwise we'll have
libgcc_s built without c18n support.
This partially reverts commit 6959da2853cea290b6f360311c53b8560391d861.
=> libgcc_s: Re-enable c18n support

sys/sys/param.h
Bump __CheriBSD_version to the current date to rebuild packages for dev without affecting the CheriBSD 24.05 release.
Packages for this ABI version are deployed now.
=> Bump __CheriBSD_version to 20241108

sys/vm/swap_pager.c
- **swap_pager: Transfer CHERI tags if the fast pass works**
- **swap_pager: Use swblk_lookup in CHERI helper functions**
=> swap fixes

sys/netgraph/bluetooth/include/ng_btsocket.h, sys/netgraph/ng_socket.h
In a purecap kernel built with subobject bounds, casting sockaddr to sockaddr_* structures will lead to capability bounds fault crashes when accessing data fields that fall out of struct sockaddr. 
This fixed #2279.
=> netgraph: Fix CHERI tag violations due to tight subobject bounds in sockaddr_* structs

sys/compat/freebsd64/freebsd64_vfs.c
It appears I accidently marked the path argument to kern_getfhat as a kernel pointer in the initial implementation (bbeb37ff330ab).
Fixes: #2278
=> freebsd64_getfhat: path is a userspace argument

bin/cheribsdtest/cheribsdtest.h, bin/cheribsdtest/cheribsdtest_vm.c, lib/libsys/mmap.2, sys/vm/vm_map.c, sys/vm/vm_mmap.c
Fix the underlying issue in #2252 (failed vm_map_stack_lock due to write reservations) and then forbid the MAP_STACK within an existing reservation since it's not done anywhere and doesn't make much sense.
=> MAP_STACK fixes

sys/contrib/subrepo-openzfs/cmd/zdb/zdb.c, sys/riscv/include/atomic.h
This fixes the build on 32-bit platforms.
Fixes:	dc91e7452482 ("zdb: dump ZAP_FLAG_UINT64_KEY ZAPs properly (#16334)")
=> Fix `make tinderbox`

lib/cheri-libc++/Makefile
This is only needed when enabling the libc++-internal assertions.
=> Add missing file to libc++ build

libexec/rtld-elf/aarch64/rtld_c18n_asm.S, libexec/rtld-elf/aarch64/rtld_c18n_machdep.c, libexec/rtld-elf/rtld.c, libexec/rtld-elf/rtld.h, libexec/rtld-elf/rtld_c18n.h
Improve trampolines to clear the correct number of return values during tail-call.
Improve previous uses of c18n_return_address.
=> c18n: Miscellaneous improvements

sys/cheri/cheri_sysctl.c
Rename misleading kern.features.cheriabi_kernel to kern.features.cheri_purecap_kernel and make clear that it's a pure-capaiblity kernel (not CheriABI which refers to userspace).
=> Add kern.features.cheri_purecap_kernel

sys/vm/swap_pager.c, sys/vm/swap_pager.h, sys/vm/vm_cheri_revoke.c
The procstat-related patches should perhaps be upstreamed as well, though `procstat vm` doesn't have a verbose mode in vanilla FreeBSD.
=> several caprevoke optimizations

lib/libprocstat/Symbol.map, lib/libprocstat/libprocstat.3, lib/libprocstat/libprocstat.c, lib/libprocstat/libprocstat.h, libexec/rtld-elf/rtld_c18n.c, sys/cheri/c18n.h, sys/kern/kern_proc.c, sys/sys/sysctl.h, usr.bin/procstat/Makefile, usr.bin/procstat/procstat.1, usr.bin/procstat/procstat.c, usr.bin/procstat/procstat.h, usr.bin/procstat/procstat_compartments.c
This rebases #2272 to dev and adds more features (incl. a generation counter for the compartment array to deal with races).
=> procstat: Add a 'compartments' command to list c18n compartments

lib/libprocstat/libprocstat.c
This ensures the trailing bytes of the compartment name are always
zeroed in the output buffer.
=> libprocstat: Use calloc for procstat_getcompartments output buffer

lib/csu/aarch64/Makefile, lib/csu/aarch64/caprel.h, lib/csu/aarch64/crt1_c.c, lib/csu/aarch64c/Makefile, lib/csu/aarch64c/crt1_c.c, lib/csu/common-cheri/crt_init_globals.c, libexec/rtld-elf/rtld.c, share/mk/bsd.lib.mk, share/mk/bsd.prog.mk
- **csu: Add support for ELF relocations to init caps for static binaries**
- **morello: Support R_MORELLO_RELATIVE relocations in static binaries**
- **rtld: Workaround Morello LLVM lld bug with local-caprelocs=elf**
- **Enable --local-caprelocs=elf for Morello**
=> Morello: Stop using caprelocs for static binaries

bin/cheribsdtest/cheribsdtest_malloc.c, lib/libc/stdlib/malloc/mrs/mrs.c
- Actually implement free(NULL)
- Abort on invalid pointer passed to free() including duplicates
- Add a test
=> Abort on double free

sys/sys/param.h
We must bump __CheriBSD_version to rebuild all packages with devel/llvm-morello based on LLVM 15.
=> Bump __CheriBSD_version to 20250127

usr.sbin/bsdinstall/scripts/finalconfig
Commit ac78e3e9c581 ("bsdinstall: Add "Finish" button to finalconfig")
removed the Exit entry from the menu, renamed OK to Select and added a
Finish in place of the old Exit entry. On the surface this seemed like a
good idea, as at a glance OK wasn't clear that it was selecting an entry
rather than just closing the box, Exit isn't the most obvious term
to use for proceeding through the installer without doing anything, and
it separated out the different cases of "do something extra" and
"continue". However, because bsddialog (and dialog) keep a menu entry
highlighted even when the Cancel (in this case, Finish) button is
selected, this now looks even more confusing, with users easily
believing that they are about to select the Add User option (being
either surprised when it doesn't …
=> bsdinstall: Switched back to amended single-button finalconfig

sys/arm64/arm64/identcpu.c
These are needed in order to boot bhyve guests on CheriBSD.
=> Backport upstream bug fixes for control register handling

bin/cheribsdtest/cheribsdtest_fault.c
In https://github.com/CTSRD-CHERI/llvm-project/pull/708, we decided to be consistent and always use address semantics for CFromPtr expansion, so now RISC-V LLVM matches the Morello behaviour
=> cheribsdtest: Fix nofault_cfromptr with LLVM assuming ISAv9 semantics

sys/riscv/cheri/cheri_debug.c, sys/riscv/include/frame.h, sys/riscv/riscv/exception.S, sys/riscv/riscv/genassym.c, sys/riscv/riscv/locore.S, sys/riscv/riscv/swtch.S, sys/riscv/riscv/vm_machdep.c
This mirrors how (C)TP is handled in all kernels, which has the exact
same problem. We no longer require STDC at all, though still initialise
it for good measure while it exists.
As part of this, add and improve existing comments, since the limited
number of scratch registers and lack of register banking makes this code
quite intricate.
This PR is also based on cherry-picking an upstream refactor to make this
change simpler.
=> riscv: Store kernel DDC on stack rather than in STDC while in userspace

bin/cheribsdtest/Makefile.cheribsdtest, bin/cheribsdtest/cheribsdtest_vm.c
Restricting libpthread to just the -mt variants is a very deliberate
choice in order to ensure that we test the implementations of things
like signals without libthr's interposition.
Document this clearly in the Makefile so this doesn't happen again.
Fixes:	abb906e73878 ("cheribsdtest: Add a couple of regression tests for async revocation")
=> cheribsdtest: Don't link against libpthread for non-mt variants

lib/libprocstat/libprocstat.c, usr.bin/procstat/procstat_compartments.c
libprocstat is responsible for allocating the array of compartment information that is returned to the procstat command-line tool, which is responsible for freeing it. But procstat should not attempt to free the array if libprocstat returns an error.
Also fixes a bug that might cause NULL to be dereferenced in libprocstat.
=> procstat: Fix bug with procstat compartments

sys/kern/subr_module.c
This bug was causing panics during boot in QEMU when a preloaded KLD failed to load (because of missing dependencies) and was unloaded.
=> kenv: Fix preload_delete_name() in purecap kernels

sys/dev/drm/freebsd/drm_os_freebsd.c
This should fix a crash reported by Graeme. The race is very clear from the crashdump. We have the panicking thread:
```
#3  0xffff000000589c70 in panic (fmt=0xffff000000ae7087 [rR,0xffff000000ae7087-0xffff000000ae70b4] (invalid) "vm_object_reference: Referenced dead object.") at /local/scratch/jenkins/workspace/CheriBSD-pipeline_dev@2/cheribsd/sys/kern/kern_shutdown.c:916
#4  0xffff0000008de56c in vm_object_reference (object=0xffffa08755d0fba0 [rwRW,0xffffa08755d0fba0-0xffffa08755d0fd90] (invalid)) at /local/scratch/jenkins/workspace/CheriBSD-pipeline_dev@2/cheribsd/sys/vm/vm_object.c:516
#5  0xffff0000001d8b58 in drm_fstub_do_mmap (file=<optimized out>, fops=<optimized out>, foff=0xffff000132a310a8 [rwxRWE,0xffff000132a310a8-0xffff000132a310b0] (invalid), size=4096, …
```
=> drm: Fix a race in drm_fstub_do_mmap()

libexec/rtld-elf/rtld.c
If the `name` argument is used, it needs to be duplicated to prevent it from being subsequently freed by others.
=> c18n: Duplicate string when adding compartment name

bin/cheribsdtest/Makefile.cheribsdtest, bin/cheribsdtest/cheribsdtest.c, bin/cheribsdtest/cheribsdtest.h, bin/cheribsdtest/cheribsdtest_fs.c, bin/cheribsdtest/cheribsdtest_malloc.c, bin/cheribsdtest/cheribsdtest_util.c, bin/cheribsdtest/cheribsdtest_vm.c, lib/libc/stdlib/malloc/mrs/mrs.c, libexec/Makefile, libexec/malloc_early_constructor/Makefile, libexec/malloc_early_constructor/Makefile.inc, libexec/malloc_early_constructor/malloc_early_constructor.c, libexec/malloc_early_constructor/mt-c18n/Makefile, libexec/malloc_early_constructor/purecap-benchmark-dynamic-mt/Makefile, libexec/malloc_early_constructor/purecap-benchmark-dynamic/Makefile, libexec/malloc_early_constructor/purecap-benchmark-mt/Makefile, libexec/malloc_early_constructor/purecap-benchmark/Makefile, libexec/malloc_early_constructor/purecap-dynamic-mt/Makefile, libexec/malloc_early_constructor/purecap-dynamic/Makefile, libexec/malloc_early_constructor/purecap-mt/Makefile, libexec/malloc_early_constructor/purecap/Makefile
Set a priority for the mrs constructer in the "system" range.
It's not clear to me what the right priority is. 100 works for this test, but it's seems easy to argue for something higher like 50.
=> Fix malloc & free in early constructors

lib/libcheri_caprevoke/aarch64/libcaprevoke_md.h, sys/arm64/arm64/cheri_revoke_machdep.c, sys/arm64/arm64/copyinout.S, sys/arm64/arm64/efirt_support.S, sys/arm64/arm64/freebsd64cb_sigtramp.S, sys/arm64/arm64/locore.S, sys/arm64/arm64/sigtramp.S, sys/arm64/include/asm.h
As part of deprecating including the encoding mode in -march, putting it
in .arch_extension was also deprected. However, whilst inferring the
mode from -mabi had already been added prior to that, no alternative to
.arch_extension had been, and so the corresponding warning was turned
off by default, which remains the case to this day.
Switch over to the cleaner .code directive to both simplify the code and
ensure that we're ready in case that warning ever gets enabled by
default (or even becomes an error).
=> arm64: Use .code directive over deprecated .arch_extension

bin/cheribsdtest/cheribsdtest_fptr_canon.c, bin/cheribsdtest/cheribsdtest_signal.c, lib/libcheribsdtest_dynamic/cheribsdtest_dynamic.h, lib/libcheribsdtest_dynamic/cheribsdtest_dynamic_fptr.c
Add test for global integer variables containing function addresses.
Also increases the length of signal_returncap because c18n with default-wrapped trampolines requires that.
=> cheribsdtest: Add tests in anticipation of c18n where function pointers are wrapped by default

contrib/elftoolchain/elfcopy/segments.c, libexec/rtld-elf/map_object.c, libexec/rtld-elf/rtld.c, libexec/rtld-elf/rtld.h
- **rtld: Fix error reporting when create_pcc_caps fails**
- **elftoolchain objcopy: Don't rewrite PT_CHERI_PCC and PT_C18N_NAME headers**
=> Fixes to get sub-lib c18n working on Morello

lib/libc/stdlib/malloc/jemalloc/Compartments.json, lib/libc/stdlib/malloc/jemalloc/Makefile.inc, lib/libc/stdlib/malloc/mrs/Compartments.json, lib/libc/stdlib/malloc/mrs/Makefile.inc, lib/libc/stdlib/malloc/snmalloc/Compartments.json, lib/libc/stdlib/malloc/snmalloc/Makefile.inc
Separate compartments are used for jemalloc, mrs, and snmalloc.  The
stub malloc_revoke routines are left in the default compartment.
=> libc: Add compartments for malloc backends

lib/libprocstat/libprocstat.c, lib/libprocstat/libprocstat.h, libexec/rtld-elf/rtld_c18n.c, sys/cheri/c18n.h, sys/kern/kern_proc.c, usr.bin/procstat/procstat_compartments.c
Add another column to the output of `procstat -a compartments` that indicates whether a compartment contains at least one library that is dlopened.
Meanwhile, clean up a number of inconsistent uses of error codes in c18n-related procstat functions.
=>  procstat: Print whether a compartment contains dlopened libraries 

share/mk/bsd.lib.mk, share/mk/bsd.prog.mk
There are usecases for other ABIs, but for now go ahead and confine it to purecap.  We might eventually want another knob to enable sub-library compartmentalization on hybrid for benchmarking.
=> c18n: only enable policy files on purecap

tests/sys/netmap/ctrl-api-test.c
This test starts two threads to verify that two concurrent threads
cannot enter the kernel loop on the same netmap context.  The test
even has a comment about a potential race condition where the first
thread enters the loop and is stopped before the second thread tries
to enter the loop.  It claims it is fixed by the use of a semaphore.
However, the semaphore doesn't "fix" anything.
In the CI setup for CHERI, we run the testsuite once a week against
various architectures using single CPU QEMU instances.  Across
multiple recent runs of the plain "aarch64" test the job ran for an
entire day before QEMU was killed by a timeout.  The last messages
logged were from this test:
734.881045 [1182] generic_netmap_attach     Emulated adapter for tap3312 created (prev was NULL)
734.882340 [ 321] …
=> netmap: Disable a buggy and unsafe test (sync_kloop_conflict)

libexec/rtld-elf/tests/cheri/abi-mismatch/basic_hybrid_lib/basic.c, libexec/rtld-elf/tests/cheri/abi-mismatch/basic_purecap_lib/basic.c, tools/tools/syscall_timing/syscall_timing.c
This backwards compatible change facilitates https://github.com/CTSRD-CHERI/llvm-project/pull/763.
With this change all remaining instances of `__CHERI__` are in LLVM code so should be fixed by subrepo pull.
=> `s/__CHERI__/__has_feature(capabilities)/`

lib/libc/stdlib/malloc/mrs/mrs.c
Previously we wouldn't set mrs_initialized when quarantining was disabled.  This caused ever call to malloc to rerun mrs_init_impl. This triggered an assert in free().
=> mrs_init_impl: always initialize or exit

sys/fs/p9fs/p9_client.c, sys/fs/p9fs/p9_client.h, sys/fs/p9fs/p9_protocol.h, sys/fs/p9fs/p9fs_vnops.c
Cherry pick @markjdb's last p9fs fix that hasn't been merged yet so it lands in the release.
=> p9fs: Use UNLINKAT instead of REMOVE to implement removals

share/mk/bsd.compiler.mk, share/mk/bsd.cpu.mk, share/mk/bsd.lib.mk, share/mk/bsd.prog.mk, sys/conf/kern.mk, sys/conf/kern.pre.mk
bsd.cpu.mk is included by sys.mk when in a FreeBSD port Makefile which means it's included without MK_* variables defined.  Due to the way this works (checking for ${.CURDIR}/../../Mk/bsd.port.mk) it's also from places like share/doc/IPV6/Makefile on MacOS where the mk directory matches Mk.
=> Move CHERI_CODEPTR_RELOCS to bsd.{lib,prog}.mk

sys/sys/param.h
With updated port versions this will also trigger the compiler wrapper to link with -cheri-codeptr-relocs.
=> Bump __CheriBSD_version for function pointer changes

sys/kern/kern_proc.c, sys/kern/subr_prf.c, sys/vm/device_pager.c, sys/vm/vm_mmap.c, sys/vm/vm_object.c, sys/vm/vm_object.h
- **sys: Don't crash on invalid strings passed to %s for printf**
- **device_pager: rename the un_pager.devp.dev field to handle**
- **vm_object: do not assume that un_pager.devp.dev is cdev**
=> Fix crashes extracting paths from device pager  VM objects

sys/arm64/vmm/vmm_arm64.c
I'm not sure if this might be simplistic, but it resolves a problem I see with breakpoint injection from bhyve's gdb stub. This arises when the debugger has installed a breakpoint, and the guest triggers a breakpoint exception some other way, e.g., a dtrace FBT probe.
=> arm64/vmm: Preserve PSR_C64 when injecting an exception

sys/arm64/arm64/trap.c, sys/riscv/include/pcb.h, sys/riscv/riscv/cheri_revoke_machdep.c, sys/riscv/riscv/trap.c
- **riscv: Use vm_pointer_t for pcb_onfault**
- **ricsv: Use pcb_onfault to set all of tf_sepc for purecap kernels**
- **riscv: Derive new exception PC for onfault from saved exception PC**
- **morello: Cleanup setting a new PCC from pcb_onfault**
=> Fixes to pcb_onfault handling

sys/vm/swap_pager.c
I hit this bug when trying to build ports-mgmt/pkg using Poudriere that uses tmpfs for /wrkdirs. `pkg-static` compressed by itself resulted in zeroed pages of its .data.rel.ro section (just after a 14K region of zeros) in a package archive. A simpler reproducer of this issue was just copying `pkg-static` with `cp` that calls `copy_file_range()`.
```
Correct swap_pager_seek_data so that, when the first lookup finds no valid pages, second and subsequent lookups are attempted anyway.
This was broken by db08b0b04deced766c3b5f07bcfb82333666226c.
Reported by:	marklmi@yahoo.com
Reviewed by:	kib
Tested by:	marklmi@yahoo.com
Fixes:	db08b0b04deced76 tmpfs_vnops: move swap work to swap_pager
Differential Revision:	https://reviews.freebsd.org/D47767
(cherry picked from commit …
```
=> cherry-pick: swap_pager: fix seek_data with invalid first page

libexec/rtld-elf/aarch64/reloc.c
lld has been fixed to store these relocations in .rela.dyn along with
other non-lazy relocations instead.
This reverts commit 29c8deddfdc08a717fcfe704a140b16d8cb10980.
=> Revert "rtld: Handle R_MORELLO_RELATIVE PLT relocations"

libexec/rtld-elf/rtld_c18n.c
_rtld_thr_exit destructs all thread-specific data structures and receiving a signal during this period would be very problematic.
=> c18n: Block all signals upon entering _rtld_thr_exit

libexec/rtld-elf/rtld.c, libexec/rtld-elf/rtld.h, libexec/rtld-elf/rtld_c18n.c, libexec/rtld-elf/rtld_c18n.h, sys/cheri/c18n.h, sys/kern/kern_proc.c, usr.bin/procstat/procstat_compartments.c
Add a new RTLD_LO_DLOPEN_TOP flag that is passed to load_object by dlopen but is not passed down to dependencies.
Pass down the flags from load_object down to compart_id_allocate. Rename the has_dlopened flag to just dlopened and set it if RTLD_LO_DLOPEN is set.  Add a new dlopened_explicitly flag that is set for RTLD_LO_DLOPEN_TOP.
Change procstat to use D for explicitly dlopened compartments, and d for implicitly loaded compartments.
=> c18n: Distinguish explicitly dlopened compartments from dependencies

lib/libc/gen/elf_utils.c, libexec/rtld-elf/Symbol-c18n.map, libexec/rtld-elf/rtld_c18n.c, libexec/rtld-elf/rtld_c18n_policy.txt
Expose RTLD's tramp_reflect to libc so that __elf_phdr_match_addr can use it to unwrap any function pointers passed into it.
=> c18n: Teach __elf_phdr_match_addr to unwrap trampolines

lib/libcompiler_rt/Makefile.inc
Tighten the bounds on enabling _Float16 and __bf16 to not include development 15.0.0 and development versions there of (including the release/15.x branch point).  __bf16 support was enabled very late in the 15.0.0 release cycle, just prior to rc3.  This caused problems building amd64 targets with a Morello LLVM compiler synced to near the 15.x branch point.
=> compiler-rt: improve _Float16 and __bf16 guards

sys/dev/rtwn/if_rtwn.c, sys/dev/rtwn/if_rtwn_rx.c, sys/dev/rtwn/if_rtwn_tx.c, sys/dev/rtwn/if_rtwnvar.h, sys/dev/rtwn/rtl8812a/r12a_rx.c, sys/dev/rtwn/usb/rtwn_usb_attach.c, sys/dev/rtwn/usb/rtwn_usb_ep.c, sys/dev/rtwn/usb/rtwn_usb_tx.c, sys/dev/rtwn/usb/rtwn_usb_tx.h, sys/dev/rtwn/usb/rtwn_usb_var.h, sys/net80211/ieee80211.c, sys/net80211/ieee80211_adhoc.c, sys/net80211/ieee80211_crypto_ccmp.c, sys/net80211/ieee80211_hostap.c, sys/net80211/ieee80211_ioctl.c, sys/net80211/ieee80211_radiotap.h, sys/net80211/ieee80211_sta.c, sys/net80211/ieee80211_var.h
- rtwn: ensure TX work isn't scheduled during reset / abort
- rtwn: change the USB TX transfers to only do one pending transfer per endpoint
- rtwn: enable FCS in the recive config to work around truncated frames
- rtwn: don't do 64 bit TSF extension by default
- rtwn: make sure RCR_APPFCS stays set in monitor mode / mode changes.
- net80211: crypto: ccmp: fix more hardware offload bits
- net80211: validate control frame TA/RA before further processing
- rtwn: enable reception of BAR frames
- rtwn: Disable IP/TCP/UDP checksum offloading
- rtwn: Add missing subobject bounds annotations
- net80211: Don't bound structs that extend radiotap headers
- net80211: Fix subobject bounds issue in IEEE80211_IOC_CHANINFO
=> Various fixes for working rtwn

sys/arm64/arm64/pmap.c, sys/riscv/riscv/pmap.c, sys/vm/vm_fault.c, usr.bin/procstat/procstat_cheri.c
This fixes a couple of panics that could manifest while building world on CheriBSD. For some reason they are quite hard to trigger unless library c18n is enabled (and even then it took quite a while for me). One is an upstream bug in the page fault handler, which the async revoker exposed since it faults in parallel with the application thread(s), and one is specific to CheriBSD.
While here, remove a check in vm_fault_prefault() that inhibited prefaulting when revocation is active, as I believe other existing checks are sufficient, and we were disabling prefaulting from VM objects where it ought to be safe, i.e., from shared mappings of vnodes.
=> Fix a couple of kernel bugs affecting the revoker

libexec/rtld-elf/map_object.c, libexec/rtld-elf/rtld.c, libexec/rtld-elf/rtld.h, libexec/rtld-elf/rtld_c18n.c
- **proc: Update c18n compartments sysctl handler for struct rtld_c18n_compart**
- **proc: Validate bounds of entire c18n comparts array once**
- **proc: Better handle short reads in proc_read_string_properly**
=> Don't leak compartment name pointers after dlclose()

lib/libbz2/Compartments.json, lib/libbz2/Makefile, lib/libz/Compartments.json, lib/libz/Makefile, lib/libzstd/Compartments.json, lib/libzstd/Makefile
zlib has two major parts.  The core deflate compression works entierly in memory.  There is also the gzlib portion which provides an analog to POSIX IO interfaces and uses IO underneath.
=> io compartments to compression libraries

bin/cheribsdtest/cheribsdtest_cheriabi.c, lib/libsys/mprotect.2
Documented PROT_CAP and add a test for restoring PROT_WRITE with implied PROT_CAP.
=> mprotect doc and test update

libexec/rtld-elf/rtld.c
With compartmentalized binaries, a compartment might contain a PLT
that only has IPLT stubs.  lld still emits DT_ tags for such a PLT,
but the DT_PLTRELSZ tag is zero.  To handle these, scan the Plt_Entry
structures after scanning .dynamic and drop entries with zero size.
This also handles the aarch64 special case for a Morello LLD bug.
While here, rework some of the multi-plt handling.  Detect mismatched
PLT tags sooner and return false from digest_dynamic1() for a mismatch
and remove sanity checks on PLTs from digest_dynamic2().
While here, fix rtld to die if either digest_dynamic call fails for
rtld itself.
=> rtld: Tweak handling of mismatched dynamic tags for PLTs

contrib/elftoolchain/readelf/readelf.c
This uses a similar style to reporting the interpreter path for
PT_INTERP.
Suggested by:	Jessica Clarke <jrtc27@jrtc27.com>
=> readelf: Output compartment names for PT_C18N_NAME program headers

sys/kern/kern_proc.c
- **proc: Update c18n compartments sysctl handler for struct rtld_c18n_compart**
- **proc: Validate bounds of entire c18n comparts array once**
- **proc: Better handle short reads in proc_read_string_properly**
=> Minor cleanups and fixes to kern.proc.c18n_compartments

bin/Makefile, bin/dlopen/Makefile, bin/dlopen/dlopen.1, bin/dlopen/dlopen.c
Attempts to dlopen each command line argument then sleeps. Useful for demoing the idea of plugins without a real plugin system.
TODO:
=> dlopen utility

libexec/rtld-elf/rtld.c
For object files without DT_SONAME or other names which fallback to
obj->path, trim the path to the basename to set the compartment name.
=> rtld c18n: Use basename of pathnames for compartment names

crypto/openssl/crypto/arm_arch.h, crypto/openssl/crypto/bn/asm/armv8-mont.pl, crypto/openssl/crypto/chacha/asm/chacha-armv8.pl, crypto/openssl/crypto/poly1305/asm/poly1305-armv8.pl, crypto/openssl/crypto/sha/asm/sha1-armv8.pl, crypto/openssl/crypto/sha/asm/sha512-armv8.pl, sys/crypto/openssl/aarch64/armv8-mont.S, sys/crypto/openssl/aarch64/chacha-armv8.S, sys/crypto/openssl/aarch64/poly1305-armv8.S, sys/crypto/openssl/aarch64/sha1-armv8.S, sys/crypto/openssl/aarch64/sha256-armv8.S, sys/crypto/openssl/aarch64/sha512-armv8.S, sys/crypto/openssl/arm/aesv8-armx.S, sys/crypto/openssl/arm/ghashv8-armx.S, sys/crypto/openssl/arm_arch.h
- **OpenSSL arm_arch.h: Add 32-bit support to PTR* macros**
- **OpenSSL: Load globals via GOT entries in purecap**
- **OpenSSL: Regen assembly to pull in purecap GOT indirection fixes**
=> Fix OpenSSL asm with narrowed PCC bounds

bin/cheribsdtest/cheribsdtest.h, bin/cheribsdtest/cheribsdtest_tls.c, lib/libc/gen/dlfcn.c, lib/libc/gen/tls.c, lib/libcheribsdtest_dynamic/Makefile, lib/libcheribsdtest_dynamic/cheribsdtest_dynamic_tls.c, libexec/rtld-elf/map_object.c, libexec/rtld-elf/powerpc/reloc.c, libexec/rtld-elf/powerpc64/reloc.c, libexec/rtld-elf/riscv/reloc.c, libexec/rtld-elf/rtld.c, libexec/rtld-elf/rtld.h
CHERI-RISC-V (like CHERI-MIPS) does not currently set bounds for references to TLS symbols, so dlsym(3) also did not do so. However, Morello's ABI does set bounds (albeit dynamically whenever taking a reference), so dlsym(3) should match and set bounds.
=> rtld-elf: Set bounds for dlsym(3) of a TLS symbol on Morello

lib/libc/gen/tls.c, libexec/rtld-elf/aarch64/reloc.c, libexec/rtld-elf/amd64/reloc.c, libexec/rtld-elf/arm/reloc.c, libexec/rtld-elf/i386/reloc.c, libexec/rtld-elf/powerpc/reloc.c, libexec/rtld-elf/powerpc64/reloc.c, libexec/rtld-elf/riscv/reloc.c, libexec/rtld-elf/rtld.c, libexec/rtld-elf/rtld.h, sys/sys/_tls_variant_i.h, sys/x86/include/tls.h
- **libc: Reassociate pointer arithmetic in __libc_tls_get_addr**
- **libc: Consistently use uintptr_t for TLS implementation**
- **rtld-elf: Consistently use uintptr_t for TLS implementation**
- **libc: Use variables more consistent with Variant I for Variant II TLS**
- **rtld-elf: Use variables more consistent with Variant I for Variant II TLS**
- **libc: Use struct tcb * rather than uintptr_t ** for the tcb**
- **rtld-elf: Use struct tcb * rather than uintptr_t ** for the tcb**
- **rtld-elf: Use clear pointer provenance when updating DTV pointer**
- **tls: Introduce struct dtv and struct dtv_slot**
- **rtld-elf: Use size_t rather than uintptr_t for an index**
=> Backport TLS cleanups committed upstream

sys/net80211/_ieee80211.h
When joining a 802.11n network, `ieee80211_setup_htrates` casts an object of type `struct ieee80211_htrateset` to the smaller `struct ieee80211_rateset` and passes it to `ieee80211_fix_rate`. `ieee80211_fix_rate` uses the `rs_nrates` field to index into the rates array `rs_rates` and we'll get a bounds exception, even though the access is actually correct. This PR adds an annotation to preserve the bounds of the original object before casting.
=> net80211: Preserve CHERI bounds of ieee80211_htrateset after casting

libexec/rtld-elf/aarch64/reloc.c, libexec/rtld-elf/aarch64/rtld_c18n_machdep.h, libexec/rtld-elf/aarch64/rtld_machdep.h, libexec/rtld-elf/aarch64/rtld_start.S, libexec/rtld-elf/rtld.c, libexec/rtld-elf/rtld.h, libexec/rtld-elf/rtld_c18n.c, libexec/rtld-elf/rtld_c18n.h, libexec/rtld-elf/rtld_c18n_mi.S
Previously, in _rtld_bind_c18n and _rtld_tlsdesc_dynamic, we emulate the effect of a compartment transition trampoline with hand-written assembly instructions. It turns out that it is fine to just use trampolines, greatly simplifying the code.
=> c18n: Replace manual compartment transitions with trampolines

sys/amd64/amd64/elf_machdep.c, sys/arm/arm/elf_machdep.c, sys/arm64/arm64/elf_machdep.c, sys/arm64/arm64/exception.S, sys/arm64/arm64/locore.S, sys/i386/i386/elf_machdep.c, sys/kern/link_elf.c, sys/kern/link_elf_obj.c, sys/kern/linker_if.m, sys/powerpc/powerpc/elf32_machdep.c, sys/powerpc/powerpc/elf64_machdep.c, sys/riscv/riscv/elf_machdep.c, sys/riscv/riscv/locore.S, sys/sys/linker.h
- **link_elf_obj.c: Bring over make_capability from link_elf.c**
- **link_elf: Finalize capability prior to invoking IFUNC resolver**
- **link_elf: Seal function pointer capabilities as sentries**
- **kld: Return a uintptr_t from elf_lookup functions instead of a Elf_Addr**
- **link_elf_obj: Fix some IFUNC handling on purecap**
- **elf_reloc: Use capabilities from the elf_lookup function directly**
- **link_elf: Set bounds on lf->ctors_addr**
- **link_elf: Use tighter bounds on code capabilities for the kernel**
- **arm64: Update more exception vectors for purecap**
- **arm64: Use narrower bounds for PCC in locore**
- **arm64: Narrow bounds on data capability used for early ELF relocations**
- **riscv: Actually strip permissioms from code_cap passed to init_cap_relocs**
=> Various kernel linker fixes

lib/libmalloc_simple/malloc.c
Confusingly, __simple_malloc_aligned does not set bounds (similarly for
__simple_malloc_unaligned), unlike __simple_malloc etc, so as the caller
we must do so. The non-zero offset case already had to do this due to
allocationg additional allocator-internal space, but this requirement
even for the case where no additional space is included was missed.
Fixes:	1bd421a421c2 ("libmalloc_simple: Add an implementation of __crt_aligned_alloc_offset")
=> libmalloc_simple: Set bounds for __crt_aligned_alloc_offset with offset 0

sys/dev/hyperv/vmbus/vmbus_reg.h
This value is used for an array of u_long, so we just need to to check sizeof(long). Another option would be to use uint64_t instead but this is the minimal change needed to build for Morello now that the compiler no longer defined __LP64__.
=> vmbus: check for __SIZEOF_LONG__ instead of __LP64__

libexec/rtld-elf/riscv/reloc.c, libexec/rtld-elf/riscv/rtld_start.S, sys/kern/link_elf.c, sys/riscv/riscv/elf_machdep.c
- rtld-elf/riscv: Support R_RISCV_JUMP_SLOT and lazy binding for purecap
- riscv: Support R_RISCV_JUMP_SLOT in purecap kernel linker
=> riscv: Support R_RISCV_JUMP_SLOT for purecap

sys/arm64/arm64/elf_machdep.c, sys/riscv/riscv/elf_machdep.c
The compiler might optimize out the check for 0 assuming that adding 0
is idempotent, but adding 0 is not idempotent for sealed capabilities.
Reported by:	Alex Richardson
Co-authored-by: Jessica Clarke <jrtc27@jrtc27.com>
=> kld: Check for sentries explicitly when ignoring relocation addends

Makefile.inc1
This is a local diff I've been carrying around for my pkgbase setup. Since I'm probably the only one using pkgbase on CheriBSD, I think this won't break anything.
The value for PKG_MAINTAINER is wrong of course, but I'm not sure what alternative would be appropriate.
=> pkgbase: Set a couple of package metadata variables for CheriBSD

libexec/rtld-elf/riscv/reloc.c, libexec/rtld-elf/riscv/rtld_start.S, sys/kern/link_elf.c, sys/riscv/riscv/elf_machdep.c
This will keep 25.03 building even with a toolchain that enables this by default (or doesn't even support the old approach).
=> Backport CHERI-RISC-V R_RISCV_JUMP_SLOT support

Jenkinsfile
- **Jenkinsfile: Drop purecapKernelArchitectures parameter**
- **Jenkinsfile: Remove unused name variable**
- **Jenkinsfile: Drop "suffix" terminology**
- **Jenkinsfile: Drop always-true runParallel**
- **Jenkinsfile: Pass cheribuildArgs as a List**
- **Jenkinsfile: Use cheribuildProject's parallelism rather than our own**
=> Jenkinsfile cleanups

lib/libkldelf/ef_riscv.c, libexec/rtld-elf/riscv/reloc.c, sys/riscv/riscv/elf_machdep.c, sys/sys/elf_common.h
This will allow CHERI LLVM to still build 25.03 without needing a way to opt
out of generating these relocations.
Note that 25.03 has the lax caprelocs parsing, and so will ignore all the other
permission bits for function caprelocs, thereby handling both (normal) function
and code caprelocs with no changes needed.
- **sys/elf_common.h: Sync CHERI-RISC-V relocations**
- **link_elf: Handle new R_RISCV_FUNC_RELATIVE**
- **riscv: Handle new R_RISCV_FUNC_RELATIVE**
- **libkldelf: Handle new R_RISCV_FUNC_RELATIVE**
=> Backport R_RISCV_FUNC_RELATIVE support to 25.03

sys/libkern/arm64/crc32c_armv8.S
The armv8_crc32c function uses `ldr` to load 4 bytes of data even if the remaining data could be less than 4 bytes. This causes capability bound error.
This error can be triggered, for example, when accessing files in an ext2fs partition, which requires the calculation of crc32.
This piece of code also demonstrates the problem:
```
#include <stdio.h>
#include <sys/gsb_crc32.h>
int main() {
unsigned char buf[7];
printf("%d", armv8_crc32c(0, buf, 7));
}
```
which prints `In-address space security exception (core dumped)`.
PS: I also wonder if this should be fixed upstream as well.
=> Fix possible out of bound read in armv8_crc32c
